	EXTERNAL	UFO_OPEN
	CHARACTER*40		FILE_1/'AGGL_HRS:
	1AGGL_EQUIP_2.DAT'/
	STRUCTURE/DIGFILE/
		INTEGER		POINT_REF  !POINT REFERENCE NO.
		INTEGER		COUNT	   !ACCUMULATED TIME COUNTS
		INTEGER		COUNT_1    !RESET COUNTER
		INTEGER		COUNT_2    !REFERENCE COUNTER
		INTEGER		COUNT_3
		CHARACTER*11	POINT_NO   !POINT NUMBER
		CHARACTER*32	DESCR      !ENGLISH DESCRIPTION
	END STRUCTURE
	RECORD/DIGFILE/POINT

	OPEN(1,FILE=FILE_1,STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=16,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C
	J=1
10	READ(1,REC=J,ERR=900)POINT
		TYPE*,'RECORD=',J
		TYPE*,POINT.POINT_REF,' ',
	1	POINT.COUNT/12,' ',POINT.COUNT_3/12,' ',POINT.DESCR
	J=J+1
	GOTO 10
900	CLOSE(1)
	END
