C
	INTEGER WS_ID,NUM_POINTS,NV,I,J
C
	REAL PY(4)
C
	DATA WS_ID/1/,NUM_POINTS/2/,NV/20/
C
	CALL GKS$OPEN_GKS ()
	CALL GKS$OPEN_WS (WS_ID,GKS$K_CONID_DEFAULT,GKS$K_WSTYPE_DEFAULT)
	CALL GKS$ACTIVATE_WS (WS_ID)
C
	CALL GKS$INQ_MAX_DS_SIZE(I,J,K,XXXX,YYYY,L,M)
	XMAX=MAX(XXXX,YYYY)
	IF((XXXX/XMAX).EQ.1.0) THEN 
	RATX=1.0
	RATY=YYYY/XMAX
	ELSE
	RATX=XXXX/XMAX
	RATY=1.0
	END IF
	LARGEST_VIEWPORT=1
	CALL GKS$SET_VIEWPORT(LARGEST_VIEWPORT,0.0,RATX,0.0,RATY)
	CALL GKS$SELECT_XFORM(LARGEST_VIEWPORT)
	CALL GKS$SET_WS_WINDOW(WS_ID,0.0,RATX,0.0,RATY)
	CALL GKS$SET_WS_VIEWPORT(WS_ID,0.0,XXXX,0.0,YYYY)
C
C
	CALL GKS$SET_PLINE_LINETYPE (1)
C
	QW=2
	CALL GKS$SET _PLINE_LINEWIDTH (QW)
C
	NUM_POINTS=2
	PY(1)=.1
	PY(2)=.3
	PY(3)=.5
	PY(4)=.7
	
	CALL GKS$POLYLINE (NUM_POINTS,PX,PY(1))
	CALL GKS$POLYLINE (NUM_POINTS,PX,PY(2))
	CALL GKS$POLYLINE (NUM_POINTS,PX,PY(3))
	CALL GKS$POLYLINE (NUM_POINTS,PX,PY(4))
C
    	CALL GKS$DEACTIVATE_WS (WS_ID)
	CALL GKS$CLOSE_WS (WS_ID)
	CALL GKS$CLOSE_GKS ()
	STOP
	END
c
