CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C                         
C
C
C	CONC 24 HOUR REPORT, READS CONC SHIFT DATA ALSO
C
C	PR1669 Correct Concentrator Step3 Floculant Pump Speed
C	
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	IMPLICIT NONE
C
	INTEGER UFO_OPEN,DCNT,LN,NC,MSAVE,HS,SAVEINDEX(2),XMM,MSGCNT,IS
C
	EXTERNAL UFO_OPEN
C
c	   weighting factor for recovery  (no. of lines/ by step)
	REAL WFACT(3)/3,6,6/
C
	CHARACTER SAVMD*40,MX(168)*40,H2*23
C
	CHARACTER*23 ENDATE(42),STPTM,STRTM
	REAL XBAR,UCL,LCL,UCLR,XVAL(43),RVAL(43),XSUM(18),INDNC(16)
	CHARACTER ASTT*23,BDAY*23,SAVE*64,ALN*2
	INTEGER XDAT(2),DAT2(2),INTC,INTF,R,ST(2),BONE(2),INTV(2),LA,LB,
	1	XDATX(2),DAT2X(2),INTCX,INTFX,LRB,LRE,STST(2)
	DOUBLE PRECISION CT(16,12),FT(7,3),CTX(16,12),FTX(7,3)
	REAL	REALTIME,RR,CL
C
	CHARACTER ADAY*23,AONE/'1'/
C
	INTEGER GOODPT(60),GOODPTCR(40),I,J,K,L,M,N,NN,MM,CXSTS(100)
	REAL ANVAL(1900),ANVALCR(1000),SUM,NSUM
C
	INTEGER*2 STAT
C
c
c
C
c
	structure /bozo2/
c
		character*4	key		! yymm	(primary key)
		real		msil(3,31)	! mine ind. sio2 by shift,day
		real		cr12(3,31)	! crusher +1/2 by shift,day
		real 		flfr(3,31)	! flf davis tube recovery
		real		flfs(3,31)	! flf davis tube sio2
		real		fls(3,31)	! flf sio2
		real		flts(3,31)	! flot tails sio2
		real		aeff(4,3,31)	! amine efficiency by cell
c
c
	end structure
c
	record /bozo2/ hsd
C
c
c
c
	STRUCTURE /SHIFT/
C
		CHARACTER 	DS*7		! 1-6=YYMMDD  7=SHIFT   (KEY 0)
		INTEGER		INPTIME(2)	! INPUT TIME
		CHARACTER 	FOREMAN*14
		CHARACTER 	TL*14
		CHARACTER 	OPER*14
C
		REAL		TPH(18)
		REAL		LGRIND(18)
		REAL 		OPHRS(18)
C
		INTEGER		INDEX(2,40)
		CHARACTER	DELAYS(40)*64
C
		REAL		GRINDS(3)
		REAL		CNOLA(3)
		REAL		SIL(3)
		REAL		TARG(3)
		REAL		RECV(3)
		REAL		BINS(3)
		REAL		RAW(2)
		REAL		FLOC(3)
		INTEGER		DOWN(18)	! 1=DOWN
		REAL		FLSIL
		REAL		FLFE
		REAL		AMINE
		INTEGER		BANKS(4)	! 1=DOWN
		REAL		FLREC
		REAL		CT
		REAL		FT
		INTEGER		LR		! LINES RUNNING
		REAL		AL		! AVERAGE LINES
		INTEGER		FPLUGS
		INTEGER		DIKE
		INTEGER		PIT
		CHARACTER	RES*5
		INTEGER		FLXBINLVL
		CHARACTER*4	FROTHSTAT
		INTEGER 	FLUXSTAT
		INTEGER		FLXTM(2)
		CHARACTER*3	AGBINS(5)
		INTEGER		AGTANKS(6)
		LOGICAL		SPC2,SPC3
C
		CHARACTER	MFLOSS*80
		CHARACTER	HKEEP(3)*80
		LOGICAL		SAFE
		CHARACTER	SAFEMSG*160
		CHARACTER	UTIL(3)*80
		CHARACTER	CTPROB(3)*80
C
		CHARACTER	MDOWN(168)*40
C
		INTEGER  	SST(2,2,16,20)         ! STOP TIME, START TIME
c
		REAL	       	REALTIME	 !time since beginning of shift
		LOGICAL		SPC2S,SPC3S	!in control for shift
C
		REAL		RRATIO		!RECOVERY RATIO
		REAL		LFT(7)		!FINE TAILS BY SECTION
		REAL		LCT(18)		!COARSE TAILS BY LINE
		CHARACTER	MFLOSS2*80   !added to mag loss by rjs 14mar94
		INTEGER		RGONOFF		!1-MILL ON 0-MILL OFF
		REAL		RGPOP		!%OP TIME RGRND MILL 
		REAL		FTC(8)	     !%froth to cyc.- max 8entry/shift
		REAL		FTCH(8)	     !hours for each entry
		REAL		LIMESTONE	!SHIFT LIMESTONE TONS
		REAL		LIMEGRIND	!LAST -200 GRIND FOR LIMESTONE
		REAL		LIMETPH		!LIMESTONE TPH
		CHARACTER       HIGHF(9)*81     !HI F.T. PROBLEMS BY SECTION
		CHARACTER       HIGHC(18)*81    !HI C.T. PROBLEMS BY LINE
		CHARACTER       LOWT(18)*81     !LOW TPH BY LINE
		REAL		TONS		!TOTAL RMF TONS 
		REAL		CONC		!TOTAL CONC. TONS
 	END STRUCTURE
C
	RECORD /SHIFT/ DAT,SHF(3)
C
C
C
C		CX AND ANALOG POINTS FROM CONCENTRATOR VXI
C
	INTEGER  TPH(18)/0,0,50,162,190,208,238,256,284,304,331,351,389,
	1			412,452,472,507,527/,
	1	LGRIND(18)/0,0,957,959,961,963,964,966,968,970,
	1		  972,974,976,978,980,982,984,986/,
	1	OPHRS(18)/0,0,1501,1502,1503,1504,1505,1506,1507,1508,1509,
	1		  1510,1511,1512,1513,1514,1515,1516/,
	1	GRINDS(3)/1677,1678,1679/,
	1	NSIL(2)/1305,1306/,
	1	TARG(2)/1698,1699/,
	1	RECOV(3)/1663,1664,1665/,
	1	CBIN(2)/456,457/,		!CRUSHER ANALOGS
	1	FLUXBIN/455/,                   !CRUSHER ANALOGS
	1	FFSIL/1312/,
	1	AMINELBT/1203/,
	1	FLOCSPD1(2)/648,691/,FLOCSPD2(3)/699,730,762/,
	1				FLOCSPD3(3)/795,827,1471/,
	1	ST2COMP/1755/,ST3COMP/1756/,
	1	RGAN/1614/,RGCX/764/,LIMEAN/850/,LIMET/1205/
	1	,RMFTONS(18)/0,0,1702,924,925,926,915,916,917,918,919,
	1		  920,931,936,941,946,951,956/
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C
C
	STRUCTURE /BOB/
		CHARACTER SHIFT	                  ! 1,2, OR 3    KEY
		INTEGER   RMSTAT(16)		  ! 1=UP 0=DOWN  ROD MILL CXS
		INTEGER   SST(2,2,16,20)         ! STOP TIME, START TIME
		INTEGER   FLUXUP                  ! 1=UP,0=DOWN
		INTEGER   FLUXTIME(2)             ! TIME OF LAST STATUS CHANGE
		INTEGER   FLOT(4)			! 1=UP,0=DOWN 
	END STRUCTURE
C
	RECORD /BOB/ DLY,DLYZ
C
C
C
C
	STRUCTURE /SHIFTX/
C
C
	CHARACTER*6 DATES
	INTEGER SHIFT
	INTEGER TANK(6)
	CHARACTER BINS(5)*3
	REAL    PROD(5)
	INTEGER FILOP(3)
	INTEGER FILAV(3)
	INTEGER	VAC(3)
	REAL TRIPH20(3),FILTR(3),TOT203(3),CSIO2(3),RECOV(3),GRIND(3),
	1	BTA(3),RATIO(3),RECI(3),RECO(3),GRATEHR(5),BALLHR(5),
	1	WOODT(5),COALT(5),GASCF(5),PELTYP(5),RECBAL(5),
	1	FORECAST(2),ACTUAL(2),T42
C
	REAL PTONS(5),BENT(5),MBTU(5),BT(5),AT(5),Q(5),CMP(5),M200(5),
	1	BZ(5),KE(5),PRE(5),UGR(5),DD1(5),DD2(5),GSPD(5),BED(5),
	1	HITMP(5),MICRO(5)
C
	CHARACTER EQUIP(5,5)*13,STOP(5,5)*5,START(5,5)*5,MSG(5,5)*40
C
	CHARACTER  MESSAGE(5)*80,SLOP*1482
C
	REAL FOTANK2
	REAL DDPD(5)
	REAL DDP(5)
	REAL FUELOIL(5)
	REAL FOTANK
C
	REAL DMBTU(5)
C
	CHARACTER YR*4
C
	END STRUCTURE
C
C
	RECORD /SHIFTX/ DATA,DATAZ
C
C
	integer aqq(2)
C
C
	INTEGER SHIFT,ICNT,SHIFT2
	CHARACTER ASHIFT,MON(12)*3/'JAN','FEB','MAR','APR','MAY','JUN','JUL',
	1	'AUG','SEP','OCT','NOV','DEC'/,KEY*7,KEY2*7,ASHIFT2
	REAL X,Y,XX,YY
C
C
	CHARACTER SSZ(3)*5/'22:30','06:30','14:30'/,
	1	  ESZ(3)*5/'06:29','14:29','22:29'/
C
	INTEGER IPS,KK,JJ,NSTART,MINUS6
C
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCC
C
	INTEGER FROTH_ANVAL/1727/
C
	INTEGER ST1,ST2,ST3,N1,N2,N3,MSV,IC
	REAL PCT,CHI,FHI,B270,RMAG,TTMAG,CDR
CCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C
C
	STRUCTURE /DAY/
C
		CHARACTER 	DS*6		! 1-6=YYMMDD     (KEY 0)
		INTEGER		INPTIME(2)	! INPUT TIME
		CHARACTER 	FOREMAN*14
		CHARACTER 	TL*14
		CHARACTER 	OPER*14
C
		REAL		TPH(18)
		REAL		LGRIND(18)
		REAL 		OPHRS(18)
C
		REAL		GRINDS(3)
		REAL		CNOLA(3)
		REAL		SIL(3)
		REAL		TARG(3)
		REAL		RECV(3)
		REAL		BINS(3)
		REAL		RAW(2)
		REAL		FLOC(3)
		INTEGER		DOWN(18)	! 1=DOWN
		REAL		FLSIL
		REAL		FLFE
		REAL		AMINE
		INTEGER		BANKS(4)	! 1=DOWN
		REAL		FLREC
		REAL		CT
		REAL		FT
		INTEGER		LR		! LINES RUNNING
		REAL		AL		! AVERAGE LINES
		INTEGER		FPLUGS
		INTEGER		DIKE
		INTEGER		PIT
		CHARACTER	RES*5
		INTEGER		FLXBINLVL
		CHARACTER*4	FROTHSTAT
		INTEGER 	FLUXSTAT
		INTEGER		FLXTM(2)
		CHARACTER*3	AGBINS(5)
		INTEGER		AGTANKS(6)
		LOGICAL		SPC2,SPC3
C
c
		REAL	       	REALTIME	 !time since beginning of shift
		LOGICAL		SPC2S,SPC3S	!in control for shift
C
		REAL		RRATIO		!RECOVERY RATIO
		REAL		LFT(7)		!FINE TAILS BY SECTION
		REAL		LCT(18)		!COARSE TAILS BY LINE
		CHARACTER	MFLOSS2*80   !added to mag loss by rjs 14mar94
		INTEGER		RGONOFF		!1-MILL ON 0-MILL OFF
		REAL		RGPOP		!%OP TIME RGRND MILL 
		REAL		FTC(8)	     !%froth to cyc.- max 8entry/shift
		REAL		FTCH(8)	     !hours for each entry
		REAL		LIMESTONE	!SHIFT LIMESTONE TONS
		REAL		LIMEGRIND	!LAST -200 GRIND FOR LIMESTONE
		REAL		LIMETPH		!LIMESTONE TPH
		REAL		TONS		!TOTAL RMF TONS 
		REAL		CONC		!TOTAL CONC. TONS
 	END STRUCTURE
C
	RECORD /DAY/ DAY,DAYZ
C
C
	CHARACTER ASTIM*14 /'-- 06:34:00.00'/
	INTEGER RTIM(2)
C
	REAL SFN(7),SFD(7)
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	COMMON /CNC_ANVALTBL/ANVAL,/CNC_GOODPTTBL/GOODPT
	COMMON /CRS_ANVALTBL/ANVALCR,/CRS_GOODPTTBL/GOODPTCR
	COMMON /CONTACTSCNC/CXSTS
C
	CALL SYS$BINTIM (AONE,BONE)
C
C
C
	ASTIM=ASTIM(1:3)//'23:00:00.00'
C
	CALL SYS$BINTIM (ASTIM,RTIM) !convert time to binary
C
	CALL SYS$SCHDWK (,,RTIM,BONE) !sched. a wakeup at 23:00
C
C
C
C	  get today's ascii date and time
c
1111	CALL SYS$ASCTIM (,ADAY,,)
	CALL SYS$BINTIM (ADAY,DAY.INPTIME)
C
	IF (ADAY(1:1) .EQ. ' ') ADAY(1:1)='0'
C
C
	IF (ADAY(13:17) .GE. '06:30' .AND. ADAY(13:17) .LT. '22:30') THEN
C
C
		GO TO 999
C
	ELSE IF (ADAY(13:17).GE.'22:30' .AND. ADAY(13:17).LE.'23:59') THEN
C
		DO 336 I=1,12
			IF (MON(I) .EQ. ADAY(4:6)) GO TO 337
336		CONTINUE
		STOP ' DATE SCREWUP'
C
337		WRITE (KEY(3:4),'(I2)') I
		IF (KEY(3:3) .EQ. ' ') KEY(3:3)='0'
		KEY=ADAY(10:11)//KEY(3:4)//ADAY(1:2)//'3'
C
	END IF
C
C
C
C
C
	OPEN (UNIT=31,FILE='LOGS:CNC_ACTIVE.DAT',STATUS='OLD',RECL=2,
	1	FORM='UNFORMATTED',ACCESS='DIRECT',USEROPEN=
	1	UFO_OPEN,SHARED)	
C
C
	OPEN (UNIT=32,FILE='LOGS:CNC_HOUR.DAT',STATUS='OLD',RECL=2,
	1	FORM='UNFORMATTED',ACCESS='DIRECT',USEROPEN=
	1	UFO_OPEN,SHARED)	
C
C
C
	OPEN (UNIT=33,FILE='LOGS:CNC_SHIFT.DAT',STATUS='OLD',RECL=2,
	1	FORM='UNFORMATTED',ACCESS='DIRECT',USEROPEN=
	1	UFO_OPEN,SHARED)	
C
C
	OPEN (UNIT=34,FILE='LOGS:CNC_DAY.DAT',STATUS='OLD',RECL=2,
	1	FORM='UNFORMATTED',ACCESS='DIRECT',USEROPEN=
	1	UFO_OPEN,SHARED)	
C
C
C
C
C
C	   shift report file, this file is in DESCENDING order.
C
55	OPEN (UNIT=10,FILE='USER_D:[METREP.CSHIFT]SHIFT_DELAYS3.DAT',
	1	ACCESS='KEYED',STATUS='OLD',SHARED,ERR=7080)
C
	GO TO 887
C
7080	WRITE (6,*) ' CONC SHIFT REPORT IS BEING UPDATED- TRY LATER'
	CALL LIB$WAIT (2.)
	GO TO 55
C
C
C
C	   DAILY report file, this file is in DESCENDING order.
C
887	OPEN (UNIT=11,FILE='USER_D:[METREP.CSHIFT]CONC24.DAT',
	1	ACCESS='KEYED',STATUS='OLD',SHARED,ERR=7082)
C
	GO TO 102
C
7082	WRITE (6,*) ' CONC DAILY REPORT IS BEING UPDATED- TRY LATER'
	CALL LIB$WAIT (2.)
	go to 887
C
C
C
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C
C	  read in the shift storage file
C
C
102	READ (10,KEY=KEY(1:6)//'1',IOSTAT=MM) SHF(1)
	READ (10,KEY=KEY(1:6)//'2',IOSTAT=MM) SHF(2)
	READ (10,KEY=KEY(1:6)//'3',IOSTAT=MM) SHF(3)
C
	CLOSE (10)
C
C
	READ (11,KEY=KEY(1:6),IOSTAT=MM) DAY
C
C
	IF (MM .EQ. 36) THEN
C
		DAY.DS=KEY(1:6)
C
	ELSE IF (MM .NE. 0) THEN
		STOP ' DAY FILE BO'
	END IF
C
C
C
C
	ST1=0
	ST2=0
	ST3=0
	N1=0
	N2=0
	N3=0
	DAY.TONS=0
c
	do 121 I=3,18
		DAY.TPH(I)=0
		READ (34,REC=TPH(I)) X,Y
		IF (Y .LE. 0) GO TO 3120
		DAY.TPH(I)=X/Y
C
3120		DAY.OPHRS(I)=0
		READ (34,REC=OPHRS(I)) X,Y
		IF (Y .LE. 0) GO TO 1211
		DAY.OPHRS(I)=X
C
1211		DAY.LGRIND(I)=0
		READ (34,REC=LGRIND(I)) X,Y
		IF (Y .LE. 0) GO TO 3121
		DAY.LGRIND(I)=X/Y
C
C		  total rmf tons
C
3121		READ (34,REC=RMFTONS(I)) X,Y
		IF (Y .LE. 0) GO TO 121
		DAY.TONS=DAY.TONS+X
C
121	CONTINUE
C
C
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
c
	DAY.REALTIME=24.0
ccccccccccccccccccccccccc
c           
	CL=0.
c
	DO 6101 I=1,16
C
6101		CL=CL+DAY.OPHRS(I+2)
C
		DAY.AL=CL/DAY.REALTIME
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C
	DO 122 I=1,3
		DAY.GRINDS(I)=0
		READ (34,REC=GRINDS(I)) X,Y
		IF (Y .LE. 0) GO TO 1123
		DAY.GRINDS(I)=X/Y
C
1123		DAY.RECV(I)=0
		READ (34,REC=RECOV(I)) X,Y
		IF (Y .LE. 0) GO TO 122
		DAY.RECV(I)=X/Y
122	CONTINUE
C
c
c
C
	DO 130 I=1,2
		DAY.SIL(I+1)=0
		READ (34,REC=NSIL(I)) X,Y
		IF (Y .LE. 0) GO TO 124
		DAY.SIL(I+1)=X/Y
C
124		DAY.TARG(I+1)=0
		READ (34,REC=TARG(I)) X,Y
		IF (Y .LE. 0) GO TO 130
		DAY.TARG(I+1)=X/Y
130	CONTINUE
C
C
	READ (34,REC=FFSIL) X,Y
	IF (Y .NE. 0) DAY.FLSIL=X/Y
C
	DAY.AMINE=0
	READ (34,REC=AMINELBT) X,Y
	IF (Y .NE. 0) DAY.AMINE=X/Y
C
C
CCCCCCCCCCCCCCC
C	  avg flocc. speed  (STEP 1)
C
	SUM=0
	N=0
C
	DAY.FLOC(1)=0
	READ (34,REC=FLOCSPD1(1)) X,Y
	IF (Y .NE. 0) THEN
		N=N+1
		SUM=X/Y
	END IF
C
	READ (34,REC=FLOCSPD1(2)) X,Y
	IF (Y .NE. 0) THEN
		SUM=SUM+(X/Y)
		N=N+1
	END IF
C
	IF (N .NE. 0) DAY.FLOC(1)=SUM/N
C
C
C
C	  avg flocc. speed  (STEP 2)
C
	SUM=0
	N=0
C
	DAY.FLOC(2)=0
	READ (34,REC=FLOCSPD2(1)) X,Y
	IF (Y .NE. 0) THEN
		N=N+1
		SUM=X/Y
	END IF
C
	READ (34,REC=FLOCSPD2(2)) X,Y
	IF (Y .NE. 0) THEN
		SUM=SUM+(X/Y)
		N=N+1
	END IF
C
	READ (34,REC=FLOCSPD2(3)) X,Y
	IF (Y .NE. 0) THEN
		SUM=SUM+(X/Y)
		N=N+1
	END IF
C
	IF (N .NE. 0) DAY.FLOC(2)=SUM/N
C
C
C
C	  avg flocc. speed  (STEP 3)
C
	SUM=0
	N=0
C
	DAY.FLOC(3)=0
	READ (34,REC=FLOCSPD3(1)) X,Y
	IF (Y .NE. 0) THEN
		N=N+1
		SUM=X/Y
	END IF
C
	READ (34,REC=FLOCSPD3(2)) X,Y
	IF (Y .NE. 0) THEN
		N=N+1
		SUM=SUM+(X/Y)
	END IF
C
	READ (34,REC=FLOCSPD3(3)) X,Y
	IF (Y .NE. 0) THEN
		N=N+1
		SUM=SUM+(X/Y)
	END IF
C
	IF (N .NE. 0) DAY.FLOC(3)=SUM/N
C
c
C	   determine which nola is controlling which step
c
	DAY.CNOLA(2)=SHF(3).CNOLA(2)
	DAY.CNOLA(3)=SHF(3).CNOLA(3)
C
C
C
C	   indicate if 130-02 regrind mill is presently operating
C
	DAY.RGONOFF=SHF(3).RGONOFF
C
C
c
C
C	   get shift regrind mill hours
C
	READ (34,REC=RGAN) X,Y
	DAY.RGPOP=X
C
C
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C	get limestone tons- DAY to date
C
C
C
1918	DAY.LIMESTONE=0
	READ (34,REC=LIMEAN) X,Y
	IF (Y .NE. 0) DAY.LIMESTONE=X
C
C
	DAY.LIMETPH=0
	READ (34,REC=LIMET) X,Y
	IF (Y .NE. 0) DAY.LIMETPH=X/Y
C
CCCCCCCCCCCCCCC
C
C
C
C
CCCCCCCCCCCCCCC
C
C	  read in coarse and fine tails
C
C
	OPEN (UNIT=60,FILE='USER_D:[METREP.LINEAT]TAILS2.LIS',
	1	STATUS='UNKNOWN',RECL=512,FORM='UNFORMATTED',ACCESS='DIRECT'
	2	,SHARED,USEROPEN=UFO_OPEN)
C
C
	READ (60,ERR=457,REC=1) XDAT,INTC,CT,DAT2,INTF,FT
	READ (60,ERR=457,REC=2) XDATX,INTCX,CTX,DAT2X,INTFX,FTX
C
C
C
C
	CALL SYS$ASCTIM (,H2,XDATX,)
	IF (H2(1:1) .EQ. ' ') H2(1:1)='0'
C
	IF (ADAY(1:11) .EQ. H2(1:11)) THEN
		READ (60,REC=2) XDAT,INTC,CT,DAT2,INTF,FT
		GO TO 1177
	END IF
C
C
	CALL SYS$ASCTIM (,H2,XDAT,)
	IF (H2(1:1) .EQ. ' ') H2(1:1)='0'
C
	IF (ADAY(1:11) .EQ. H2(1:11)) GO TO 1177
C
C
	WRITE (6,*) ' COARSE TAILS DATES DO NOT MATCH'
C
1177	CLOSE (60)
C
	NSUM=0
	SUM=0
	LRB=0
	LRE=0
C
	L=1
	R=12
	IF (INTC .LT. 12) R=INTC
C
C
C
C
C
C
C
	DO 400 I=1,16
	DO 400 J=L,INTC
		IF (CT(I,J) .LE. 0) GO TO 400
		SUM=SUM+CT(I,J)
		NSUM=NSUM+1
		INDNC(I)=INDNC(I)+1
		XSUM(I)=XSUM(I)+CT(I,J)
400	CONTINUE
C
C
	IF (NSUM .LE. 0) GO TO 628 
C
	SUM=SUM/NSUM
C
	DAY.CT=SUM
C
C
C
C
628	DO 3321 I=1,16
C
		IF (INDNC(I) .LE. 0) THEN
			DAT.LCT(I)=0
			GO TO 3321
		END IF
		DAY.LCT(I)=XSUM(I)/INDNC(I)
C
3321	CONTINUE
C
C
C
C
578	NSUM=0
	SUM=0
C
	DO 363 I=1,7
		SFD(I)=0
		SFN(I)=0
363	CONTINUE
C
C
	DO 405 I=1,7
C
	DO 404 J=1,INTF
		IF (FT(I,J) .EQ. 0) GO TO 404
		SUM=SUM+FT(I,J)
		NSUM=NSUM+1
		SFD(I)=SFD(I)+FT(I,J)
		SFN(I)=SFN(I)+1
C
404	CONTINUE
405	CONTINUE
C
	DO 698 I=1,7
C
		IF (SFN(I) .EQ. 0) GO TO 698
		DAY.LFT(I)=SFD(I)/SFN(I)
C
698	CONTINUE
C
	IF (NSUM .LE. 0) GO TO 457 
C
C
	DAY.FT=SUM/NSUM
C           
C
C
ccccccccccccccccccccccccccccccccccccc
c
c	  get flot tail sio2 
C
C
C
457	OPEN (UNIT=91,FILE='MET_P:HALFSIL2.DAT',STATUS='OLD',
	1	ACCESS='KEYED',SHARED,ERR=282)
C
333	READ (91,KEY=KEY(1:4),IOSTAT=M) HSD
C
	CLOSE (91)
	IF (M .NE. 0) GO TO 282
C
C
	READ (KEY(5:6),'(I2)') I
C
C
	N=0
	DO 575 IS=1,3
	IF (HSD.FLTS(IS,I) .LE. 0) GO TO 575
C
	N=N+1
	DAY.FLFE=DAY.FLFE+(-.89484*HSD.FLTS(IS,I)+72.13502)
C
575	CONTINUE
C
	IF (N .EQ. 0) GO TO 6261
C
	DAY.FLFE=DAY.FLFE/N
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C	   calculate recovery after flotation.
c
c	recov=((flot feed sio2-flot tails sio2)/(avg step comp sio2-flot tails 
c									sio2))
c  	X plant avg. recovery
C
C
C
C	   get avg. plant recov
c
6261	sum=0
	n=0
	do 79 M=1,3
		if (day.recv(M) .le. 0) go to 79
		n=n+WFACT(M)
		sum=sum+day.recv(M)*WFACT(M)
79	continue
c
	if (n .eq. 0) go to 282
c
	sum=sum/n
C
c
c	  get avg step composite sio2
c
	x=0
	y=0
	do 80 M=1,2
		if (day.sil(M+1) .le. 0) go to 80
		if (day.sil(M+1) .ge. 4.5) go to 80
		x=x+day.sil(M+1)
		y=y+1
80	continue
c
c
	if (y .le. 0) go to 282
c
c
	X=X/Y
C
C
	IF (DAY.FLSIL .LE. 0) GO TO 282
C
C
	DAY.FLREC=0
	N=0
	DO 572 IS=1,3
	IF (HSD.FLTS(IS,I) .LE. 0) GO TO 572
C
	N=N+1
	DAY.FLREC=DAY.FLREC+
	1	((DAY.FLSIL-HSD.FLTS(IS,I))/(X-HSD.FLTS(IS,I)))*SUM
c
572	CONTINUE
C
	IF (N .EQ. 0) GO TO 4336
C
	DAY.FLREC=DAY.FLREC/N
C
c
cccccccccccccccccccccc
c
c	calculate recovery ratio
C
	N=0
	DAY.RRATIO=0
4336	DO 552 I=1,3
		IF (SHF(I).RRATIO .LE. 0) GO TO 552
		DAY.RRATIO=DAY.RRATIO+SHF(I).RRATIO
		N=N+1
552     CONTINUE
C
	IF (N .GT. 0) DAY.RRATIO=DAY.RRATIO/N 
		
C
CCCCCCCCCCCCCCC
C
C
282	CONTINUE
C
C
C	calculate concentrate tons  (DAT.CONC)
C
	DAY.CONC=0
	DAY.CONC=DAY.CONC+SHF(1).CONC
	DAY.CONC=DAY.CONC+SHF(2).CONC
	DAY.CONC=DAY.CONC+SHF(3).CONC
C
	DAY.TONS=0
	DAY.TONS=DAY.TONS+SHF(1).TONS
	DAY.TONS=DAY.TONS+SHF(2).TONS
	DAY.TONS=DAY.TONS+SHF(3).TONS
C
	DAY.DIKE=SHF(3).DIKE
	DAY.PIT=SHF(3).PIT
	DAY.RES=SHF(3).RES
	DAY.BINS(2)=SHF(3).BINS(2)
	DAY.BINS(3)=SHF(3).BINS(3)
	DAY.FLOC(1)=SHF(3).FLOC(1)
	DAY.FLOC(2)=SHF(3).FLOC(2)
	DAY.FLOC(3)=SHF(3).FLOC(3)
	DAY.FLXBINLVL=SHF(3).FLXBINLVL
	DAY.FLUXSTAT=SHF(3).FLUXSTAT
	DAY.FLXTM(1)=SHF(3).FLXTM(1)
	DAY.FLXTM(2)=SHF(3).FLXTM(2)
	DAY.LIMEGRIND=SHF(3).LIMEGRIND
	DAY.LR=SHF(3).LR
C
	DO 720 I=1,5
720		DAY.AGBINS(I)=SHF(3).AGBINS(I)
C
	DO 721 I=1,6
721		DAY.AGTANKS(I)=SHF(3).AGTANKS(I)
C
	DO 722 I=3,18
722		DAY.DOWN(I)=SHF(3).DOWN(I)
C
	IF (MM .EQ. 36) THEN
		WRITE (11) DAY
	ELSE IF (MM .EQ. 0) THEN
		REWRITE (11) DAY
	END IF
c
	CLOSE (11)
C
999	CALL SYS$HIBER ()
	GO TO 1111
C
	END
C
C
C
	FUNCTION STAT(J)
	INTEGER CXSTS(100),K,L
 	INTEGER*2 STAT
	COMMON /CONTACTSCNC/CXSTS
	K=J/32+1
	L=MOD(J,32)
	IF (BJTEST(CXSTS(K),L)) THEN
		STAT=1
	ELSE
		STAT=0
	END IF
	END
