C	********************************************************************
C
C	DAYHRS		PROGRAM TO :
C			  1- TRANSFER THE 24 HOUR ACCUMULATION OF RUNNING
C			     TIME TO THE AGGL_DAY_HRS.DAT FILE IN
C			     DIRECTORY AGGL_HRS
C			  2- ZERO THE 24 HOUR ACCUMULATOR IN THE
C			     AGGL_EQUIP_2.DAT FILE IN THE SAME DIRECTORY
C
C	THERE IS A RUNNING 31 DAY ACCUMULATION OF DAILY RUNNING TIME FOR
C	EACH PIECE OF EQUIPMENT, STORED IN A 32 BYTE ARRAY HRS(32).
C	THE 32ND BYTE IS A FLAG TO MARK THE END OF THE CURRENT 31 DAYS.
C
C	THIS PROGRAM IS RUN AS A DETACHED PROCESS AT 1:10 AM EVERY DAY.
C
C	26-JAN-1995	ALPHA VERSION
C
C	*****************************************************************
C	LINK DAYHRS,USER3:[RJW.LIB]GENERAL/LIB
C	****************************************************************
C	31-MAY-1989:	CHANGED THE OPEN FOR THE EQUIPMENT FILE TO
C		NON-SHARED  TO SOLVE ACCESS CONFLICTS WITH HRAGGL2
C	16-FEB-2000 ADDED TEST FOR HRS2 > 127
C	******************************************************************
	EXTERNAL	UFO_OPEN
C
	STRUCTURE/DIGFILE/
		INTEGER		POINT_REF  !POINT REFERENCE NO.
		INTEGER		COUNT	   !ACCUMULATED TIME COUNTS
		INTEGER		COUNT_1    !RESET COUNTER
		INTEGER		COUNT_2    !REFERENCE COUNTER
		INTEGER		COUNT_3    !DAILY HRS ACCUMULATOR
		CHARACTER*11	POINT_NO   !POINT NUMBER
		CHARACTER*32	DESCR      !ENGLISH DESCRIPTION
	END STRUCTURE
	RECORD/DIGFILE/POINT
C
	BYTE		HRS(32)
	REAL		HRS1
	INTEGER		HRS2
	CHARACTER*40		FILE_1/'AGGL_HRS:
	1AGGL_EQUIP_2.DAT'/
	CHARACTER*40		FILE_2/'AGGL_HRS:
	1AGGL2_DAY_HRS.DAT'/
C
C	*** OPEN NON SHARED SO THAT HRAGGL2 CAN'T BE UPDATING AT THE SAME
C	**** TIME
10	OPEN(1,FILE=FILE_1,STATUS='OLD',ERR=500,
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=16,
	1    FORM='UNFORMATTED')
C
	OPEN(2,FILE=FILE_2,STATUS='OLD',
	1	ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=8,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C
	RECORD=1
50	READ(1,REC=RECORD,ERR=200)POINT
	HRS1=POINT.COUNT_3/12.        !CALCULATE DAILY HOURS
	HRS2=NINT(HRS1)               !NEAREST INTEGER
	POINT.COUNT_3=0               !ZERO THE COUNTER
C	
	READ(2,REC=RECORD)HRS
	DO I=1,32
		IF(HRS(I) .EQ. 127) GOTO 100  !FIND THE FLAG
	END DO
C
100	IF(HRS2 .GT. 127)HRS2=0
	HRS(I)=HRS2                   !SAVE CURRENT DAY HRS
	I=I+1
	IF(I .GT. 32) I=1
	HRS(I)=127                    !SAVE FLAG IN NEW POSITION
C
	WRITE(1,REC=RECORD)POINT
	WRITE(2,REC=RECORD)HRS
C
	RECORD=RECORD+1
	GOTO 50
C	*** OPEN ERROR ****
500	CALL LIB$WAIT(2.)
	GOTO 10		!TRY AGAIN
C	**** DONE ******
200	CLOSE(1)
	CLOSE(2)
C
	END
