	EXTERNAL	UFO_OPEN
	BYTE		HRS(32)
	INTEGER*4	RECORD
	CHARACTER*40		FILE_2/'AGGL_HRS:
	1AGGL2_DAY_HRS.DAT'/
C
	OPEN(2,FILE=FILE_2,STATUS='OLD',
	1	ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=8,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C	
	RECORD=1
10	READ(2,REC=RECORD,ERR=900)HRS
	DO I=1,32
		IF(HRS(I) .NE. 127)THEN
			IF(HRS(I) .GT. 24)THEN
				HRS(I)=24
			END IF
		END IF
	END DO
C
	WRITE(2,REC=RECORD)HRS
	RECORD=RECORD+1
	GOTO 10
C
900	CLOSE(2)
	END
