CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONFIDENTIAL
C	Property of United States Steel Corporation
C	Copyright 2011 United States Steel Corporation
C	All rights reserved.
C******************************************************************************
C	EDIT_AGGL_EQUIP_2.FOR
C******************************************************************************
C Revisions:
C	IM813566 20110511 SPA6635 New Scratch program to edit the data file:
C				  AGGL_HRS:EDIT_AGGL_EQUIP_2.DAT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

	PROGRAM	EDIT_AGGL_EQUIP_2
C
	IMPLICIT NONE
C
	INTEGER*4	UFO_OPEN,I,J,K
C
C
	STRUCTURE/DIGFILE/
		INTEGER		POINT_REF  !POINT REFERENCE NO.
		INTEGER		COUNT	   !ACCUMULATED TIME COUNTS
		INTEGER		COUNT_1    !RESET COUNTER
		INTEGER		COUNT_2    !COUNT DOWN COUNTER
		INTEGER		COUNT_3
		CHARACTER*11	POINT_NO   !POINT NUMBER
		CHARACTER*32	DESCR      !ENGLISH DESCRIPTION
	END STRUCTURE
	RECORD/DIGFILE/POINT
C
	EXTERNAL	UFO_OPEN
	INTEGER*4	REF,REC
C
	OPEN(1,FILE='AGGL_HRS:AGGL_EQUIP_2.DAT',
	1    STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=16,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C
C	DO 666 I=1,400
C
	REC=1
10 	READ(1,REC=REC,ERR=7777)POINT
C
C	IF (POINT.POINT_REF .EQ. 78)THEN
C *write record to screen
C	WRITE	(6,100)POINT.POINT_REF
100	FORMAT(' ',I15)
C	WRITE	(6,100)POINT.COUNT
C	WRITE	(6,100)POINT.COUNT_1
C	WRITE	(6,100)POINT.COUNT_2
C	WRITE	(6,100)POINT.COUNT_3
C	WRITE	(6,100)I
C	WRITE	(6,200)POINT.POINT_NO
200	FORMAT(' ',A)
C	WRITE	(6,200)POINT.DESCR
C
C	POINT.POINT_NO = ' DI608291'

C *write the changed point_ref and point_no (test)
C	WRITE	(6,200)'changed values:'	 
C	WRITE	(6,100)POINT.POINT_REF
C	WRITE	(6,100)POINT.COUNT
C	WRITE	(6,100)POINT.COUNT_1
C	WRITE	(6,100)POINT.COUNT_2
C	WRITE	(6,100)POINT.COUNT_3
C	WRITE	(6,100)I
C	WRITE	(6,200)POINT.POINT_NO
C	WRITE	(6,200)POINT.DESCR
C	REWRITE (1) POINT
C     	WRITE	(6,200)'REWRITE POINT Complete'	 
C	END IF

C	IF (POINT.POINT_REF .EQ. 79)THEN
C *write record to screen
C	WRITE	(6,100)POINT.POINT_REF
C	WRITE	(6,100)POINT.COUNT
C	WRITE	(6,100)POINT.COUNT_1
C	WRITE	(6,100)POINT.COUNT_2
C	WRITE	(6,100)POINT.COUNT_3
C	WRITE	(6,100)I
C	WRITE	(6,200)POINT.POINT_NO
C	WRITE	(6,200)POINT.DESCR
C
C	POINT.POINT_REF = 1156
C	POINT.POINT_NO = ' DI619186'

C *write the changed point_ref and point_no (test)
C	WRITE	(6,200)'changed values:'	 
C	WRITE	(6,100)POINT.POINT_REF
C	WRITE	(6,100)POINT.COUNT
C	WRITE	(6,100)POINT.COUNT_1
C	WRITE	(6,100)POINT.COUNT_2
C	WRITE	(6,100)POINT.COUNT_3
C	WRITE	(6,100)I
C	WRITE	(6,200)POINT.POINT_NO
C	WRITE	(6,200)POINT.DESCR
C	REWRITE (1) POINT
C     	WRITE	(6,200)'REWRITE POINT Complete'	 
C	GOTO 7777
C       END IF
	
	IF (POINT.POINT_REF .EQ. 1156 .AND. POINT.DESCR .EQ. '208-01-3')THEN
C *write record to screen
  		WRITE	(6,100)REC
  		WRITE	(6,100)POINT.POINT_REF
		WRITE	(6,100)POINT.COUNT
		WRITE	(6,200)POINT.POINT_NO
		WRITE	(6,200)POINT.DESCR

		POINT.POINT_REF = 9999
  		REC=REC+1
C *write the changed point_ref and point_no (test)
		WRITE	(6,200)'changed values:'	 
		WRITE	(6,100)POINT.POINT_REF
		WRITE	(6,100)POINT.COUNT
		WRITE	(6,200)POINT.POINT_NO
		WRITE	(6,200)POINT.DESCR
		REWRITE (1) POINT
	     	WRITE	(6,200)'REWRITE POINT Complete'	 
		GOTO 7777
	END IF
	REC=REC+1
	GOTO 10
C
C
7777	CONTINUE
C
	CLOSE	(UNIT=1)
C
	CALL	EXIT
C
	END
