CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONFIDENTIAL
C	Property of United States Steel Corporation
C	Copyright 2011 United States Steel Corporation
C	All rights reserved.
C******************************************************************************
C	EDIT_FILTER_MANAGE.FOR
C******************************************************************************
C Revisions:
C	IM813566 20110511 SPA6635 New Scratch program to edit the data file:
C				  AGGL_HRS:FILTER_MANAGE.DAT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

	PROGRAM	EDIT_FILTER_MANAGE
C
	IMPLICIT NONE
C
	INTEGER*4	UFO_OPEN,I,J,K
C
C	** AGGL_HOURS:FILTER_MANAGE.DAT**
	STRUCTURE/FILTER_FILE/
		CHARACTER*18	FILTER_REF
		INTEGER*4	FLAG
		INTEGER*4	POINT_REF
		INTEGER*8	DATE_IN
		INTEGER*8	DATE_OUT
		REAL*4		HRS
		REAL*4		LIFE
		INTEGER*4	VENDOR
		CHARACTER*80	COMMENT
	END STRUCTURE
	RECORD/FILTER_FILE/FILTER
	BYTE		HRS1(32)
C
	EXTERNAL	UFO_OPEN
C
 
	OPEN(10,FILE='AGGL_HRS:FILTER_MANAGE.DAT',
	1    STATUS='OLD',
	1    FORM='UNFORMATTED',
	1    ORGANIZATION='INDEXED',
	1    ACCESS='KEYED',
	1    SHARED)
C
	DO 666 I=1,200
C
 	READ(10)FILTER
C	UNLOCK(10)
	IF (FILTER.POINT_REF .EQ. 79)THEN
C *write record to screen
       		WRITE	(6,100)FILTER.POINT_REF
100		FORMAT(' ',I25)
		WRITE	(6,200)FILTER.FILTER_REF
200		FORMAT(' ',A)
C		WRITE	(6,100)FILTER.HRS

		FILTER.POINT_REF = 1156
*write the changed point_ref to the file
		WRITE (6,200)'CHANGED VALUES: '
		WRITE (6,100)FILTER.POINT_REF
		WRITE (6,200)FILTER.FILTER_REF
		REWRITE(10)FILTER
		WRITE (6,200)'REWRITE FILTER COMPLETE'
		GOTO 7777
	END IF
C
666	CONTINUE
C
7777	CONTINUE
	CLOSE	(UNIT=10)
C
	CALL	EXIT
C
	END
