C
	PROGRAM	FCX
C
C	PROGRAM PRINTS OUT THE SELECTED FILTER CAKE FILE
C
	IMPLICIT NONE
C
	INTEGER*4	UFO_OPEN,FLAG/64/
	INTEGER*4	I,J,K,L,STEP,LEN
C
	STRUCTURE	/FC/
C
		CHARACTER*23	DATX	!DATE AND TIME
		REAL*4		CAO	!% CALCIUM
		REAL*4		MGO	!% MAGNESIUM
		REAL*4		SIO2    !% SILICA
		REAL*4		ALUM    !% ALUMINA
		REAL*4		ATL     !ACTIVE TANK LEVEL
		REAL*4		PCTF    !%FLUX = (%CAO+%MGO-0.6)/0.5377
		REAL*4		RFA     !REQUIRED FLUX ADJUSTMENT
		REAL*4		AFA     !ACTUAL FLUX ADJUSTMENT
		INTEGER*4	CAT     !CALCULATED ADJUSTMENT TIME
		REAL*4		CPCTFIT !CALCULATED %FLUX INPUT INTO TANK
		REAL*4		PCTFT   !%FLUX TARGET 
		REAL*4		PCTFSP  !%FLUX SETPOINT 
C
	END STRUCTURE
C
	RECORD/FC/FC
C
	CHARACTER*4	PRINTON/' [5i'/
	CHARACTER*4	PRINTOF/' [4i'/
	CHARACTER*1	FF
	CHARACTER*11	FILE(2)/'ANA:FC2.DAT',
	1		     'ANA:FC3.DAT'/
C
	EXTERNAL	UFO_OPEN
C
	FF=CHAR(12)
	PRINTON(1:1)=CHAR(27)
	PRINTOF(1:1)=CHAR(27)
C
	OPEN	(UNIT=6,FILE='SYS$COMMAND',STATUS='UNKNOWN')
C
5	CONTINUE
C
	WRITE	(6,10)
10	FORMAT	(' ' 'TYPE STEP ... 2 OR 3...OR <RET> TO QUIT')
C
	READ	(6,20)LEN,STEP
20	FORMAT	(Q,I1)
C
	IF (LEN .EQ. 0)GOTO 9999
C
	IF (STEP .GT. 3)GOTO 5
	IF (STEP .LT. 2)GOTO 5
C
	STEP=STEP-1
C
	OPEN	(UNIT=1,FILE=FILE(STEP),STATUS='OLD',SHARED,
	1	RECL=18,RECORDTYPE='FIXED',FORM='UNFORMATTED',
	1	ACCESS='DIRECT',USEROPEN=UFO_OPEN)
C
		CALL	LIB$SPAWN('SET TERM/WIDTH=132',,,FLAG)
		CALL	LIB$SPAWN('SET TERM/FORM',,,FLAG)
C
		WRITE	(6,2040)PRINTON		!LIST GOES TO PRINTER
2040		FORMAT	(' ',A)
C
		STEP=STEP+1
C
		WRITE	(6,200)FF,STEP
200		FORMAT	(' ',A,2X,'STEP ',I1,2X,
	1		 'FLUX MIXING CALCULATION DATA',//
	1		 ' ',71X,'REQ',5X,'ACT  CALC    CALC',/
	1	' ',55X,'TANK',11X,'FLUX    FLUX   ADJ   %FLUX  %FLUX  %FLUX',/
	1	' ',8X,'DATE',15X,'%CAO',3X,'%MGO',2X,'%SIO2',
	1	2X,'%ALUM',2X,'LEVEL',2X,'%FLUX',2X,'ADJUST',2X,
	1	'ADJUST',2X,'TIME',2X,'TO TNK TARGET  SETPT'/)
C
	DO 300	I=1,64
C
		READ	(1,REC=I)FC
C
		IF (FC.DATX .EQ. '                       ')GOTO 300
C
		IF (I .EQ. 51)THEN
C
			WRITE	(6,200)FF,STEP
C
		END IF
C
		WRITE	(6,201)FC.DATX,FC.CAO,FC.MGO,FC.SIO2,FC.ALUM,
	1			FC.ATL,FC.PCTF,FC.RFA,FC.AFA,FC.CAT,
	1		         FC.CPCTFIT,FC.PCTFT,FC.PCTFSP
201		FORMAT	(' ',1X,A,4F7.2,F7.1,F7.2,2F8.1,I6,F8.1,2F7.2)
C
300	CONTINUE
C
		WRITE	(6,2040)PRINTOF		!RETURN TO SCREEN
C
		CALL	LIB$SPAWN('SET TERM/WIDTH=80',,,FLAG)
		CALL	LIB$SPAWN('SET TERM/NOFORM',,,FLAG)
C
		GOTO 5
C
9999	CONTINUE
C
	CLOSE	(UNIT=1)
C
	CALL	EXIT
C
	END
