C
	PROGRAM	FCAKE
C
C	THIS PROGRAM ALLOWS THE LAB PERSONEL TO INPUT THE 
C	FILTER CAKE SIO2'S FOR STEP2 AND STEP3 AGGLOMERATOR
C	FOR USE BY THE NOLA TARGET PROGRAM
C
	REAL*4		VALUS(2),NUM,DIFF
C
	INTEGER*4	LEN,UFO_OPEN
	CHARACTER*1	ANSWER
C
	EXTERNAL	UFO_OPEN
C
	OPEN	(UNIT=6,FILE='SYS$COMMAND',STATUS='UNKNOWN')
C
	OPEN	(UNIT=1,FILE='ANA:FCAKE.DAT',STATUS='NEW',
	1	RECL=2,RECORDTYPE='FIXED',FORM='UNFORMATTED',
	1	ACCESS='DIRECT',SHARED,USEROPEN=UFO_OPEN)
C
	READ	(1,REC=1)VALUS	!BRING IN FILTER CAKE SIO2S
C
50	CONTINUE
C
	WRITE	(6,100)
100	FORMAT	(' ','INPUT STEP 2 FILTER CAKE SILICA')
C
	READ	(6,200)LEN,NUM
200	FORMAT	(Q,F4.2)
C
	IF (LEN .EQ. 0)GOTO 500
C
	DIFF=NUM-VALUS(1)	!CALC DIFF FROM LAST VALUE
C
	IF ((DIFF .LE. -0.4).OR.(DIFF .GE. 0.4))THEN
219		CONTINUE
C
		WRITE	(6,220)
220		FORMAT	(' STEP 2 FILTER CAKE IS OUT OF LIMITS FROM'/,
	1		 ' LAST SAMPLE ... ACCEPT SAMPLE Y/N ?')
C
		ANSWER=' '
		READ	(6,222)LEN,ANSWER
222		FORMAT	(Q,A)
		IF (LEN .EQ. 0)GOTO 219
		IF (ANSWER .EQ. 'Y')GOTO 300
		IF (ANSWER .EQ. 'N')GOTO 500
		GOTO 219
	END IF
C
300	CONTINUE
C
	VALUS(1)=NUM	!CHANGE STEP 2 FILTER CAKE SIO2
C
500	CONTINUE
C
	WRITE	(6,700)
700	FORMAT	(' ','INPUT STEP 3 FILTER CAKE SILICA')
C
	READ	(6,200)LEN,NUM
C
	IF (LEN .EQ. 0)GOTO 800
C
	DIFF=NUM-VALUS(2)	!CALC DIFF FROM LAST VALUE
C
	IF ((DIFF .LE. -0.4).OR.(DIFF .GE. 0.4))THEN
719		CONTINUE
C
		WRITE	(6,720)
720		FORMAT	(' STEP 3 FILTER CAKE IS OUT OF LIMITS FROM'/,
	1		 ' LAST SAMPLE ... ACCEPT SAMPLE Y/N ?')
C
		ANSWER=' '
		READ	(6,222)LEN,ANSWER
		IF (LEN .EQ. 0)GOTO 719
		IF (ANSWER .EQ. 'Y')GOTO 400
		IF (ANSWER .EQ. 'N')GOTO 800
		GOTO 719
	END IF
C
400	CONTINUE
C
	VALUS(2)=NUM	!CHANGE STEP 3 FILTER CAKE SIO2
C
800	CONTINUE
C
	WRITE	(1,REC=1)VALUS	!SEND FILTER CAKE SIO2S BACK
C
	CLOSE	(UNIT=1)
	WRITE	(6,900)VALUS
900	FORMAT	(' STEP 2 FILTER CAKE SIO2 = ',F5.2/,
	1	 ' STEP 3 FILTER CAKE SIO2 = ',F5.2)
C
	CALL	LIB$WAIT(15.0)
	CLOSE	(UNIT=6)
C
	CALL	EXIT
C
	END
