C	TO CREATE FILTER REFEREENCE FILE
C
	STRUCTURE/FILT_REF/
		CHARACTER*8	EQUIP_NO
		INTEGER*4	POINT_REF
		CHARACTER*16	TYPE
		INTEGER*4	DUM
	END STRUCTURE
	RECORD/FILT_REF/REF
	CHARACTER*8	EQUIP_NO
C
	OPEN(1,FILE='AGGL_HRS:FILTER_REF.DAT',STATUS='OLD',
	1	FORM='UNFORMATTED',ACCESS='KEYED')
C
10	TYPE*,'ENTER EQUIP_NO'
	READ(5,100)EQUIP_NO
100	FORMAT(A8)
	READ(1,KEY=EQUIP_NO)REF
	TYPE*,REF.EQUIP_NO
	TYPE*,REF.TYPE
	TYPE*,REF.POINT_REF
	GOTO 10

	END
