C	*******************************************************************
C	FILTER_MANAGE
C	14-FEB-2000
C	 NEW VERSION OF THE PROGRAM TO KEEP TRACK OF THE AGGL FILTER
C	 BAG CHANGES
C		(BASED ON NEW_FILTER.FOR)
C	*******************************************************************
C	NOTE: LINK COMMAND MUST INCLUDE USER3:[RJW.LIB]GENERAL/LIB
C	NOTE: SET DFLAG=1 WHENEVER RETURNING TO 50 (MENU) TO TRAP CR
C	*******************************************************************
C	LINK FILTER_MANAGE
C	*******************************************************************
C	30-MAY-2000 ADDED A HINT ON THE EDIT PAGE
C	*********************************************************
C
C	  RELATED FILES:
C		1- AGGL_HRS:AGGL_EQUIP_2.DAT       !EQUIPMENT OPERATING HRS
C		2- AGGL_HRS:FILTER_MANAGE.DAT	   	!FILTER HISTORY FILE
C		3- AGGL_HRS:FILTER_VEND.DAT	   !VENDOR INFO FILE
C		4- AGGL_HRS:AGGL2_DAY_HRS.DAT   !30 DAY CIRCULAR FILE OF
C			EQUIPMENT HOURS BY DAY, USED TO BACK CALCULATE
C			WHEN A CHANGE WAS MADE.
C	*********************************************************
C	*********************************************************
C	3-SEP-1992	Switched over to the new scanner program since
C			the step 3 aggl is now on westinghouse.
C			NOTE that the old point numbers were retained
C			in the aggl_equip_2.dat file but the scanner
C			program hraggl2 uses the actual step 3 point
C			numbers.  The step 3 filters are in records
C			3 thru 14 of the file.  The correspondence
C			of the numbers is as follows.
C			filter		old# 	actual point#
C			208-06-1	9001	214
C			208-06-2	9002	215
C			208-06-3	9003	218
C			208-06-4	9004	219
C			208-06-5	9005	222
C			208-06-6	9006	224
C			208-07-1	9007	225
C			208-07-2	9008	227
C			208-07-3	9009	229
C			208-07-4	9010	232
C			208-07-5	9011	234
C			208-07-6	9012	236
C	***************************************************************
C
	IMPLICIT	INTEGER(S)
	EXTERNAL	UFO_OPEN
C
C
	STRUCTURE/FILTER_FILE/
		CHARACTER*18	FILTER_REF ! EX. 208-06-1+ DATE_REF
		INTEGER*4	FLAG	   !0=CURRENT 1=HISTORY 
		INTEGER*4	POINT_REF  !EQUIPMENT REF NUMBER
		INTEGER*8	DATE_IN	   !
		INTEGER*8	DATE_OUT
		REAL*4		HRS  	   !EQUIP HRS AT INSTALLATION
		REAL*4		LIFE       !EQUIP HRS (WHEN CHANGED)
		INTEGER*4	VENDOR	   !VENDOR NUMBER 
		CHARACTER*80	COMMENT    !
	END STRUCTURE
	RECORD/FILTER_FILE/FILTER,ZERO
C
	STRUCTURE/DIGFILE/
		INTEGER		POINT_REF  !POINT REFERENCE NO.
		INTEGER		COUNT	   !ACCUMULATED TIME COUNTS
		INTEGER		COUNT_1    !RESET COUNTER
		INTEGER		COUNT_2    !COUNT DOWN COUNTER
		INTEGER		COUNT_3
		CHARACTER*11	POINT_NO   !POINT NUMBER
		CHARACTER*32	DESCR      !ENGLISH DESCRIPTION
	END STRUCTURE
	RECORD/DIGFILE/POINT
C
C
	STRUCTURE/FILT_REF/
		CHARACTER*8	EQUIP_NO
		INTEGER*4	POINT_REF
		CHARACTER*16	TYPE
		INTEGER*4	DEFAULT_VENDOR
	END STRUCTURE
	RECORD/FILT_REF/REF
C
C
	STRUCTURE/DESCRIP/                !FOR RECORD SORTING
		INTEGER*2	LENGTH
		BYTE		DTYPE
		BYTE		CLASS
		INTEGER*4	POINTER
	END STRUCTURE
	RECORD/DESCRIP/DESC
C
C
	INTEGER*4	DMAX
	PARAMETER 	(DMAX=14)	!NUMBER OF DISPLAYS
C
	INTEGER*4	ROWS(DMAX)/24,	!MENU BASE SCREEN
	1			  7,	!MENU SCREEN
	1			  2,	!ERROR MESSAGES
	1			  3,	!ADDITIONAL INFO
	1			 24,	!HELP SCREEN
	1			 24,	!ENTRY AND DISPLAY SCREEN  6
	1			  1,	!EQUIPMENT NUMBER          7
	1			  1,	!DATE INSTALLED            8
	1			  1,    !HRS AT INSTALLATION       9
	1			  1,    !VENDOR                    10
	1			  1,    ! COMMENT                  11
	1			  1,	!STATUS  CURRENT OR HISTORY 12
	1			  1,	!DATE REMOVED               13
	1			  1/	!HRS AT REMOVAL             14
C
	INTEGER*4	COLUMNS(DMAX)/80,	!MENU BASE SCREEN
	1			    40, !MENU SCREEN
	1			    50,	!ERROR MESSAGES
	1			    42,	!ADDITIONAL INFO
	1			    80,	!HELP SCREEN
	1			    80,	!ENTRY AND DISPLAY SCREEN
	1			    24,	!EQUIPMENT NO
	1			    11,	!DATE INSTALLED
	1			     9,	!HRS AT INSTALLATION
	1			    19,	!VENDOR
	1			  80,    ! COMMENT                  11
	1			  7,	!STATUS  CURRENT OR HISTORY 12
	1			  11,	!DATE REMOVED               13
	1			  9/	!HRS AT REMOVAL             14
C
C
C
	INTEGER*4	D(DMAX)		!DISPLAY IDENTIFIER
	INTEGER*4	VATTR(DMAX)/0,2,2,2,0,0,2,2,2,2,
	1			2,2,2,2/
C		  		       !VIDEO ATTRIBUTES    
	INTEGER*4	DATTR(DMAX)/0,1,0,1,0,0,1,1,1,1,
	1			0,1,1,1/                                    
	INTEGER*4	R,C	!CURSOR POSITION ROW AND COLUMN
	INTEGER*4	SAVE_ROW !SAVE CORSOR ROW NUMBER
	INTEGER*4	CHOICE	!MENU CHOICE
	INTEGER*4	COL	!NO. OF COLUMNS TO CHANGE RENDITION
	INTEGER*4	ROW	!ROW TO DISPLAY OLD VALUES
	INTEGER*4	ROW_1	!ROW FOR INPUT OF NEW VALUES
	INTEGER*2	TERM	!TERMINATION CHARACTER
	INTEGER*4	PASTE1  !PASTBOARD ID
	INTEGER*4	KB1	!KEYBOARD ID
	INTEGER*4	IOS	!IO STATUS
	INTEGER*4	WIDTH
	INTEGER*4	FIELD,MIN_FIELD,MAX_FIELD
	INTEGER*4	FD,LD
	INTEGER*4	TTD(7)/12,8,13,9,14,10,11/ !FIELD ARRANGEMENT
C
	INTEGER*4	GET_DATE,GET_NUM_PINT,GET_STRING
	INTEGER*4	GET_NUM_PFLOAT
	INTEGER*4	DATE_REF,NUM,ACCESS,DELETE
	INTEGER*4	DFLAG
	INTEGER*8	BIN,BIN2
C
	CHARACTER*1	ESC/27/
	CHARACTER*1	CR/13/
	CHARACTER*1	LF/10/
	CHARACTER*1	FF/12/
	CHARACTER*3	PRINT_ON1/'[5i'/
	CHARACTER*3	PRINT_OFF1/'[4i'/
	CHARACTER*4	PRINT_ON,PFLEET
	CHARACTER*4	PRINT_OFF
	CHARACTER*3	PITCH1_5/'[5w'/
	CHARACTER*4	PITCH_5
	CHARACTER*2	PITCH1_10/'[w'/
	CHARACTER*3	PITCH_10
	CHARACTER*80	DASHES/'------------------------------
	1--------------------------------------------------'/
	CHARACTER*1	INIT,DUM/' '/
	CHARACTER*2	PTEMP2
	CHARACTER*4	PTEMP4
	CHARACTER*5	PTEMP5
	CHARACTER*6	PTEMP6
	CHARACTER*9	PTEMP9
	CHARACTER*11	PTEMP11,DATE
	CHARACTER*10	PTEMP10
	CHARACTER*23	PTEMP23,CURRENT_TIME, DATE1,DATE_IN,DATE_OUT
	CHARACTER*80	PTEMP80
C
	INTEGER*4	POINT_REF(40),VEND_1,VEND,REF_SAVE
	INTEGER*4	POINT_REC,RECORD,DAYS_BEFORE
	INTEGER*4	EDIT(7)	!FIELD EDIT FLAGS
	INTEGER*4	FILTER_STATUS
	INTEGER*4	LINE_NO,END_FLAG
	REAL*4		HOURS_CURRENT, FTEMP
C
	REAL*4		AVG,HOURS,HRS_CURRENT,LEFT,BAG_HRS
	REAL*4		HRS_SUBT
	REAL*4		START,EXPEC,HOURS_SINCE,OFFSET
	REAL*4		TOTAL_HRS
	REAL*4		CURRENT(40)
	REAL*4		CURRENT_LIFE
	REAL*4		INSTALL_HRS,REMOVE_HRS
	CHARACTER*25	DESCR_REF(40)
	INTEGER*4	VENDOR(40)
	CHARACTER*4	PHRS_SINCE
	CHARACTER*9	PSTART_HRS,PCURRENT_LIFE
	CHARACTER*6	PHRS_CURRENT
	CHARACTER*5	PEXPEC_HRS,PLEFT,PAVE,PRECORD
	CHARACTER*3	PEQUIP
	CHARACTER*8	PEQUIP1/'208-01-1'/
	CHARACTER*16	VENDOR_NAME(0:24),VENDOR_NAME1              
	CHARACTER*7	CUR_HIST(0:1)/'CURRENT','HISTORY'/
	CHARACTER*2	PVENDOR
	CHARACTER*18	FILTER_REF
C
	SMG$M_BORDER=1
 	SMG$M_UP=1
	SMG$M_DOWN=2
	SMG$M_BOLD=1
	SMG$M_REVERSE=2
	SMG$M_BLINK=4
	SMG$M_UNDERLINE=8
	SMG$M_INVISIBLE=16
C
	PRINT_ON=ESC//PRINT_ON1
	PRINT_OFF=ESC//PRINT_OFF1
	PITCH_10=ESC//PITCH1_10
	PITCH_5=ESC//PITCH1_5
C
C
	OPEN(1,FILE='AGGL_HRS:AGGL_EQUIP_2.DAT',
	1    STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=16,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C
 	OPEN(3,FILE='AGGL_HRS:VENDOR.DAT',STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='SEQUENTIAL',
	1    RECORDTYPE='FIXED',
	1    RECL=4,
	1    USEROPEN=UFO_OPEN,SHARED,
	1    FORM='UNFORMATTED')
C
	DO I=1,24
		READ(3,ERR=9000)VENDOR_NAME(I)
	END DO
	CLOSE(3)
	VENDOR_NAME(0)='  NONE          '
C
	OPEN(4,FILE='AGGL_HRS:AGGL2_DAY_HRS.DAT',
	1    STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=8,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C
C
	OPEN(5,FILE='AGGL_HRS:FILTER_REF.DAT',STATUS='OLD',
	1	FORM='UNFORMATTED',
	1	ORGANIZATION='INDEXED',
	1	ACCESS='KEYED',
	1	SHARED)
C
	I=1
10001	ACCESS=0
10005	READ(5,IOSTAT=IOS,ERR=10900,END=10002)REF
	UNLOCK(5)
	POINT_REF(I)=REF.POINT_REF
	DESCR_REF(I)(1:8)=REF.EQUIP_NO
	DESCR_REF(I)(9:9)=' '
	DESCR_REF(I)(10:)=REF.TYPE
	VENDOR(I)=REF.DEFAULT_VENDOR
	I=I+1
	GOTO 10001
C
C	*** ERROR READING EQUIPMENT NUMBER ***************    
10900	IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'RECORD UNAVAILABLE #10900!')
			GOTO 9000
		END IF 
		GOTO 10005
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER REFERENCE FILE ERROR #10900!')
		GOTO 9000
	END IF
C
C
10002	OPEN(10,FILE='AGGL_HRS:FILTER_MANAGE.DAT',STATUS='OLD',
	1	FORM='UNFORMATTED',
	1	ORGANIZATION='INDEXED',
	1	ACCESS='KEYED',
	1	SHARED)
C	**** CREATE THE PASTEBOARD AND KEYBOARD ***********************
	STATUS=SMG$CREATE_PASTEBOARD(PASTE1,'SYS$COMMAND')
C                                     
C	STATUS=SMG$CHANGE_PBD_CHARACTERISTICS(PASTE1,80)
	STATUS=SMG$CREATE_VIRTUAL_KEYBOARD(KB1,'SYS$COMMAND')
	STATUS=SMG$SET_KEYPAD_MODE(KB1,0)     
C
	DO I=1,DMAX
		STATUS=SMG$CREATE_VIRTUAL_DISPLAY
	1	(ROWS(I),COLUMNS(I),D(I),DATTR(I),VATTR(I),)
	END DO
C	******** FILL MENU *********************************
	STATUS=SMG$PUT_CHARS_HIGHWIDE(D(1),'FILTER',1,25)
	STATUS=SMG$PUT_CHARS_HIGHWIDE(D(1),'MANAGEMENT',3,20)
	STATUS=SMG$PUT_CHARS(D(1),'USE ARROW KEYS TO SELECT',16,34)
	STATUS=SMG$PUT_CHARS(D(1),'OR TYPE SELECTION NUMBER',17,36)
C	  ***** CHOICES *************
	STATUS=SMG$PUT_LINE(D(2),'1- Display Current Filter Status')
	STATUS=SMG$PUT_LINE(D(2),'2- Enter Bag Changes')
	STATUS=SMG$PUT_LINE(D(2),'3- Print Individual Filter History')
	STATUS=SMG$PUT_LINE(D(2),'4- Edit the Database')
	STATUS=SMG$PUT_LINE(D(2),'5- Edit the Vendor List or Default')
	STATUS=SMG$PUT_LINE(D(2),'Q- QUIT')
C
	STATUS=SMG$LABEL_BORDER(D(2),'CHOICES',,,0,2)
C	**** PASTE MENU BACKGROUND AND CHOICES ********************
10	SAVE_ROW=1           
50	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(1),PASTE1,1,1)
C
C
 	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(2),PASTE1,8,19)
C
C	**** GET MENU CHOICE **************************************
C
	STATUS=SMG$SET_CURSOR_ABS(D(2),SAVE_ROW,1) !MOVE CURSOR TO CHOICES
	STATUS=SMG$RETURN_CURSOR_POS(D(2),R,C)
	STATUS=SMG$CHANGE_RENDITION(D(2),R,1,1,40,0,2)
C
C	**** READ KEYSTROKE **********************************
C
100	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,)
C                            
	IF(TERM .EQ.274) THEN        !UP ARROW PRESSED
		DFLAG=0
		J=-1
		STATUS=SMG$SET_CURSOR_REL(D(2),J,0)
		STATUS=SMG$RETURN_CURSOR_POS(D(2),R,C)
		STATUS=SMG$CHANGE_RENDITION(D(2),R,1,1,40,0,2)
		STATUS=SMG$CHANGE_RENDITION(D(2),(R+1),1,1,40,2,0)
		GOTO 100
	ELSE  IF(TERM .EQ. 275)THEN   !DOWN ARROW PRESSED
		DFLAG=0
		J=1
		STATUS=SMG$SET_CURSOR_REL(D(2),J,0)
		STATUS=SMG$RETURN_CURSOR_POS(D(2),R,C)
		STATUS=SMG$CHANGE_RENDITION(D(2),R,1,1,40,0,2)
		STATUS=SMG$CHANGE_RENDITION(D(2),(R-1),1,1,40,2,0)
		GOTO 100
	ELSE IF(TERM.EQ.81.OR.TERM.EQ.113)THEN  !Q OR q PRESSED
		GOTO 9000	!QUIT
	ELSE IF(TERM .EQ. 13) THEN	!RETURN PRESSED
		IF(DFLAG .EQ.1)THEN
			DFLAG=0
			GOTO 100
		ELSE
		 S=SMG$RETURN_CURSOR_POS(D(2),CHOICE,C) !CHOICE=CURSOR
		 S=SMG$READ_FROM_DISPLAY(D(2),PTEMP11,,CHOICE)
		 IF(PTEMP11(1:1).EQ.'Q')GOTO 9000
		 IF(PTEMP11(1:2).EQ.'  ')GOTO 100
		 SAVE_ROW=CHOICE              
		 GOTO 200	!SELECTION MADE
		END IF
	ELSE IF(TERM .EQ. 509)THEN
		GOTO 9000		!TIMED OUT AFTER 5 MINUTES
	ELSE IF(TERM .GE. 49 .AND. TERM .LE. 55) THEN
		DFLAG=0
		CHOICE=TERM - 48
		STATUS=SMG$RETURN_CURSOR_POS(D(2),R,C)
		STATUS=SMG$CHANGE_RENDITION(D(2),R,1,1,40,2,0)
		SAVE_ROW=CHOICE
		GOTO 200
	ELSE
		GOTO 100	!INVALID KEY
	END IF
C
C	*** BRANCH BASED ON CHOICE *************
200	STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(1),PASTE1)
	STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(2),PASTE1)
C
	GOTO (1000,2000,4000,4000,6000)CHOICE
C*************************************************************************
C	*** DISPLAY ALL CURRENT FILTERS  ****
1000	S=SMG$ERASE_DISPLAY(D(6))
	S=SMG$ERASE_DISPLAY(D(4))
	S=SMG$PUT_CHARS(D(6),'+++ FILTER  REPORT +++',1,21)
	S=SMG$PUT_CHARS(D(6),'CURRENT',3,39)
C
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(6),PASTE1,1,1)
	S=SMG$PUT_CHARS(D(4),'Press S to print to the screen...',1,1)
	S=SMG$PUT_CHARS(D(4),'or press <RETURN> for the printer...',2,1)
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,10,15)
	S=SMG$SET_CURSOR_ABS(D(4),1,37)
	S=SMG$RING_BELL(D(4))
1001	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
C
	IF(TERM .EQ. 296)THEN	!DO PRESSED SO QUIT
1002		DO I=4,6
			STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(I),PASTE1)
		END DO
		GOTO 50		
	ELSE IF (TERM .EQ. 509)THEN
		GOTO 1002
	ELSE IF(TERM .EQ.83.OR.TERM.EQ.115)THEN
		PRINT=0
	ELSE
		PRINT=1
	END IF
C
	IF(PRINT .EQ.1)THEN  !PRINT TO THE PRINTER
		OPEN(6,FILE='SYS$COMMAND',RECL=132,STATUS='UNKNOWN')
		S=SYS$ASCTIM(,CURRENT_TIME,,)
		WRITE(6,1605)PRINT_ON         !SWITCH TO CONTROLLER MODE
		WRITE(6,1607)FF     !FORM FEED
		WRITE(6,4700)CURRENT_TIME(1:17)
		WRITE(6,1610)
	END IF
C
1605	FORMAT(' ',A4)
1607	FORMAT(' ',A1)
1609	FORMAT(' ',A17,9X,'+++ FILTER  REPORT +++',/)
1610	FORMAT(' ',21X,'VENDOR',14X,'CURRENT HRS')
1612	FORMAT(' ',A80)
1614	FORMAT(' ',' ')
C
	S=SMG$UNPASTE_VIRTUAL_DISPLAY(D(4),PASTE1)
C
	CLOSE(10)
C
	OPEN(10,FILE='AGGL_HRS:FILTER_MANAGE.DAT',STATUS='OLD',
	1	FORM='UNFORMATTED',
	1	ORGANIZATION='INDEXED',
	1	ACCESS='KEYED',
	1	SHARED)
C	*** GET CURRENT HOURS FOR ALL FILTERS ***
	RECORD=3
1100	READ(1,REC=RECORD,ERR=1102)POINT
 		DO I=1,40
			IF(POINT.POINT_REF .EQ. POINT_REF(I))THEN
			  CURRENT(I)=FLOAT(POINT.COUNT)/12.
			  RECORD=RECORD+1
			  GOTO 1100
			END IF
		END DO
	RECORD=RECORD+1
	GOTO 1100	
C
1102	REF_SAVE=0
	ROW=3
1200	ACCESS=0
1202	READ(10,IOSTAT=IOS,ERR=1900,END=1800)FILTER
	UNLOCK(10)
	IF(FILTER.FLAG .NE. 0)GOTO 1200 !* NOT CURRENT 
C       ** NEW AGGL LINE STARTING ?
	PTEMP2=FILTER.FILTER_REF(5:6)
	S=OTS$CVT_TI_L(PTEMP2,J)
	IF(REF_SAVE .NE.J)THEN
		REF_SAVE=J
		IF(PRINT .EQ. 0)THEN
			ROW=ROW+1
		ELSE
		  WRITE(6,1614)
		END IF
		IF(ROW .GT. 23)GOTO 1500
	END IF
C
	PTEMP80=' '
	DO I=1,40
		IF(FILTER.POINT_REF .EQ. POINT_REF(I))THEN
		  PTEMP80(1:12)=DESCR_REF(I)(1:12)
		  PTEMP80(14:19)=DESCR_REF(I)(19:25)
		  PTEMP80(21:36)=VENDOR_NAME(FILTER.VENDOR)
		  J=NINT(CURRENT(I))
		  K=NINT(FILTER.HRS)
		  L=J-K
		  S=OTS$CVT_L_TI(L,PTEMP5)
		  PTEMP80(40:44)=PTEMP5
		  S=SYS$ASCTIM(,PTEMP23,FILTER.DATE_IN,)
		  PTEMP80(46:56)=PTEMP23(1:11)
		  IF(PRINT .EQ. 0)THEN
		    S=SMG$PUT_CHARS(D(6),PTEMP80,ROW,1)	
		  ELSE
		    WRITE(6,1612)PTEMP80
		  END IF
		END IF
	END DO
	ROW=ROW+1
	IF(ROW .GT. 23.AND.PRINT .EQ.0)THEN
1500		S=SMG$PUT_CHARS(D(6),
	1'**Press Q to Quit or any other key to continue **',
	1	24,1,,2)
		S=SMG$SET_CURSOR_ABS(D(6),ROW,1)
		S=SMG$RING_BELL(D(6))
		S=SMG$READ_KEYSTROKE(KB1,TERM,,300)
		IF(TERM .EQ. 81 .OR. TERM .EQ. 113)THEN
			GOTO 1002
		ELSE
			S=SMG$ERASE_DISPLAY(D(6),4,1,23,80)
			ROW=4
		END IF
	END IF
	GOTO 1200
C
1800	IF(PRINT .EQ.1)THEN
		WRITE(6,1605)PRINT_OFF         !SWITCH OFF
		CLOSE(6)
	ELSE
	  S=SMG$PUT_CHARS(D(6),
	1'**End of Report ** press any key                         ',
	1	24,1,,2)
	  S=SMG$SET_CURSOR_ABS(D(6),ROW,1)
	  S=SMG$RING_BELL(D(6))
	  S=SMG$READ_KEYSTROKE(KB1,TERM,,300)
	END IF
	GOTO 1002
C
1900	IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER FILE ERROR 1900A!')
			GOTO 2001
		END IF 
		GOTO 1202
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER REFERENCE FILE ERROR #1900B!')
		GOTO 2001
	END IF
C	**** ENTER BAG CHANGES ********************************
2000	DO I=6,11
		S=SMG$ERASE_DISPLAY(D(I))
	END DO
	DO I=1,7
		EDIT(I)=0
	END DO
C	**** FILL ENTRY AND DISPLAY SCREEN **************
	S=SMG$PUT_CHARS_WIDE(D(6),'ENTER BAG CHANGES',1,5)
	S=SMG$PUT_CHARS(D(6),'EQUIPMENT NUMBER',3,3)
	S=SMG$PUT_CHARS(D(6),'DATE INSTALLED',7,3)
	S=SMG$PUT_CHARS(D(6),'CURRENT HOURS',11,1)
	S=SMG$PUT_CHARS(D(6),'EQUIP HRS AT INSTALL:',11,40)
	S=SMG$PUT_CHARS(D(6),'VENDOR',15,3)
	S=SMG$PUT_CHARS(D(6),'COMMENT',19,3)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(6),PASTE1,1,1)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(7),PASTE1,5,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(8),PASTE1,9,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(9),PASTE1,13,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(10),PASTE1,17,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(11),PASTE1,21,1)
	S=SMG$PUT_CHARS(D(6),
	1'  * Or Press Q to Quit *',24,1,1,1)  
	S=SMG$PUT_CHARS(D(6),
	1'* Enter Filter number: Example 2-1 for 208-02-1 *',
	1	23,5,,2)
	IF(CHOICE .EQ. 4)GOTO 2010
C	**** ASK FOR FILTER NUMBER *****
2005	STATUS=SMG$SET_CURSOR_ABS(D(7),1,1)
	S=SMG$RING_BELL(D(7))	
2001	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
C
	IF(TERM .EQ. 296.or.TERM .EQ. 81.OR.TERM.EQ.113)THEN	!DO PRESSED SO BACK TO MENU
		DO I=6,12
			STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(I),PASTE1)
		END DO
		GOTO 50		
	 ELSE IF(TERM .LT. 20 .OR. TERM .GT. 122)THEN
		 GOTO 2001 
	ELSE IF (TERM .EQ. 509)THEN
		GOTO 9000
	ELSE
		INIT=CHAR(TERM)
	CALL INPUT(D(7),KB1,3,1,1,0,INIT,PEQUIP,3,DUM,STATUS)
		PEQUIP1(6:)=PEQUIP
		ACCESS=0
2003		READ(5,KEY=PEQUIP1,IOSTAT=IOS,ERR=2900)REF
		UNLOCK(5)
		GOTO 2010
	END IF
C	*** DISPLAY FILTER EQUIP NUMBER ***
2010	S=SMG$PUT_CHARS(D(7),REF.EQUIP_NO,1,1)
	S=SMG$PUT_CHARS(D(7),REF.TYPE,1,10)
	S=SMG$SET_CURSOR_ABS(D(7),1,1)
	S=SMG$SET_CURSOR_ABS(D(8),1,1)
	IF(CHOICE .EQ.2)THEN
	  S=OTS$CVT_L_TI(REF.DEFAULT_VENDOR,PVENDOR,%VAL(2))
	  S=SMG$PUT_CHARS(D(10),PVENDOR,1,1)
	  VEND=REF.DEFAULT_VENDOR
	  S=SMG$PUT_CHARS(D(10),VENDOR_NAME(VEND),1,4)
	  S=SMG$SET_CURSOR_ABS(D(10),1,1)
	  EDIT(2)=1
	END IF
	RECORD=3
2012	READ(1,REC=RECORD,ERR=9000)POINT
 		DO I=1,40
			IF(POINT.POINT_REF .EQ. REF.POINT_REF)THEN
			  HRS_CURRENT=FLOAT(POINT.COUNT)/12.
			  POINT_REC=RECORD
			  GOTO 2014
			END IF
		END DO
	RECORD=RECORD+1
	GOTO 2012	
2014	CONTINUE
	S=SMG$PUT_CHARS(D(6),
	1'* Use the TAB key or Arrow keys to move up and down',
	1	23,1,1,1)
	S=SMG$PUT_CHARS(D(6),
	1'* Press <DO> or F10 to Save or Press Q to Quit *',
	1	24,1,1,2)
	FIELD=8
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	MIN_FIELD=8  !FIRST FIELD CURSOR GOES TO
	IF(CHOICE .EQ. 2)THEN
		MAX_FIELD=11 !LAST FIELD CURSOR GOES TO
	ELSE
		MAX_FIELD=11 !LAST FIELD CURSOR GOES TO
	END IF
2101	STATUS=SMG$RETURN_CURSOR_POS(D(FIELD),R,C)  
	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300,D(FIELD))
	IF(TERM .EQ. 296.OR.TERM .EQ. 290)THEN	!DO  OR F10
		S=SMG$ERASE_DISPLAY(D(4))
		S=SMG$PUT_CHARS(D(4),'SAVE THE CHANGES (Y/N)...',
	1				1,1)
		S=SMG$SET_CURSOR_ABS(D(4),1,26)
		S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,10,20)
		S=SMG$RING_BELL(D(4))	
		S=SMG$READ_KEYSTROKE(KB1,TERM,,300)
		IF(TERM.EQ.89.OR.TERM.EQ.121)GOTO 2300  !SAVE
2102		DO I=4,11
			STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(I),PASTE1)
		END DO
		GOTO 50		
	ELSE IF(TERM .EQ. 509.OR.TERM .EQ. 81.OR. TERM .EQ. 113)THEN
		GOTO 9000		!TIMED OUT  OR QUIT
	ELSE IF(TERM .EQ. 9)THEN   !* TAB
		  FIELD=FIELD+1
		  IF(FIELD .GT. MAX_FIELD)FIELD=MIN_FIELD
		  S=SMG$SET_CURSOR_ABS(D(FIELD))
		  GOTO 2101
	ELSE IF(TERM .EQ. 274 .OR. TERM .EQ. 275)THEN 
C		*******  MOVE TO VARIOUS FIELDS ************
		IF(TERM .EQ. 275) THEN
		  FIELD=FIELD+1
		  IF(FIELD .GT. MAX_FIELD)FIELD=MIN_FIELD
		ELSE IF(TERM .EQ. 274) THEN
		  FIELD=FIELD-1
		  IF(FIELD .LT. MIN_FIELD)FIELD=MAX_FIELD
		END IF
C
		STATUS=SMG$SET_CURSOR_ABS(D(FIELD))
		GOTO 2101
	ELSE IF(TERM .GT.32.AND.TERM.LT.123)THEN     !
		 GOTO(2100,2130,2120,2140)
	1			(FIELD-7)   
	ELSE
		GOTO 2101
	END IF
C	**** EDIT VARIOUS FIELDS *****
C	*** GET INSTALLATIN DATE ****
2100	INIT=CHAR(TERM)
	CALL INPUT(D(FIELD),KB1,11,1,1,5,INIT,DATE,11,DUM,STATUS)
	IF(STATUS .EQ. 2)THEN
		S=SMG$ERASE_CHARS(D(FIELD),11,1,1)
		IF(CHOICE.EQ.2)THEN
			GOTO 2101
C		ELSE IF(CHOICE .EQ. 4)THEN
C			GOTO 4201
		END IF
	END IF
	CALL DAYS_1(DATE,DATE_ERR,DATE_REF,DATE,BIN)
	IF(DATE_ERR .GT. 0)THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,D(FIELD),1,1,
	1	  'INCORRECT DATE FORMAT!') 
		S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
		EDIT(1)=0
		IF(CHOICE.EQ.2)THEN
			GOTO 2101
		ELSE IF(CHOICE .EQ. 4)THEN
			GOTO 4201
		END IF
	END IF
	S=SMG$PUT_CHARS(D(FIELD),DATE,1,1)
	EDIT(1)=1
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
C
	CALL DATE_CHECK(DATE_REF,STATUS,DAYS_BEFORE)
	IF(STATUS .GT. 0)THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,D(10),0,0,    
	1	'GREATER THAN 30 DAYS')
		S=SMG$ERASE_DISPLAY(D(4))
		S=SMG$PUT_CHARS(D(4),'ENTER ESTIMATE OF THE NUMBER OF HOURS',
	1				1,1)
		S=SMG$PUT_CHARS(D(4),'RUN SINCE '//DATE//' :',2,1)
		S=SMG$SET_CURSOR_ABS(D(4),2,24)
		S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,10,20)
		S=SMG$READ_KEYSTROKE(KB1,TERM,,300)
		INIT=CHAR(TERM)
	  CALL INPUT(D(4),KB1,4,2,24,0,INIT,PHRS_SINCE,4,DUM,STATUS)
		S=OTS$CVT_TI_L(PHRS_SINCE,ISTART_HRS,,%VAL(1))
		START=HRS_CURRENT-FLOAT(ISTART_HRS)
		IF(START .LT. 1)THEN
		  CALL ERR_MSG(PASTE1,D(3),KB1,D(9),1,1,    
	1		'HRS ENTERED GREATER THAN CURRENT HOURS!')
		  S=SMG$ERASE_DISPLAY(D(8))
		  S=SMG$UNPASTE_VIRTUAL_DISPLAY(D(4),PASTE1)
		  IF(CHOICE.EQ.2)THEN
			GOTO 2101
		  ELSE IF(CHOICE .EQ. 4)THEN
			GOTO 4201
		  END IF
		END IF
		HRS_SUBT=FLOAT(ISTART_HRS)
		S=SMG$UNPASTE_VIRTUAL_DISPLAY(D(4),PASTE1)
		GOTO 2215
	END IF
C
	IF(DAYS_BEFORE .LT. 0)THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,D(9),1,1,    
	1		'DATE ENTERED IS AFTER PRESENT DATE!')
		 S=SMG$ERASE_DISPLAY(D(8))
		S=SMG$SET_CURSOR_ABS(D(8),1,1)
		IF(CHOICE.EQ.2)THEN
			GOTO 2101
		ELSE IF(CHOICE .EQ. 4)THEN
			GOTO 4201
		END IF
	END IF
	IF(DAYS_BEFORE .EQ. 0)THEN
		START=HRS_CURRENT
		HRS_SUBT=0
	ELSE
		CALL EST_HRS(DAYS_BEFORE,POINT_REC,HRS_SUBT)
		START=HRS_CURRENT-HRS_SUBT
	END IF
2215	WRITE(PSTART_HRS,2020)START
2020	FORMAT(F9.1)
	IF(CHOICE .EQ.4)GOTO 4406
	S=SMG$PUT_CHARS(D(6),PSTART_HRS,11,62)
C	*** DISPLAY CURREENT LIFE BASED ON THE DATE ENTERED
C	**    IF CURRENT DATE IS ENTERED IT WILL BE ZERO
	CURRENT_LIFE=HRS_CURRENT-START
	WRITE(PCURRENT_LIFE,2020)CURRENT_LIFE
	FIELD=9
	S=SMG$PUT_CHARS(D(FIELD),PCURRENT_LIFE,1,1)
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	IF(CHOICE .EQ. 2)THEN
		FIELD=10
	ELSE
		FIELD=10
	END IF
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	IF(CHOICE.EQ.2)THEN
		GOTO 2101
	END IF
C	*** ENTER VENDOR ****
2120	INIT=CHAR(TERM)
	CALL INPUT(D(FIELD),KB1,2,1,1,0,INIT,PVENDOR,2,DUM,STATUS)
	S=OTS$CVT_TI_L(PVENDOR,VEND,,%VAL(1))
	IF(VEND .LT.1 .OR.VEND .GT.24)THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,D(FIELD),1,1,    
	1		'VENDOR NUMBERS 1-24!')
		IF(CHOICE.EQ.2)THEN
			S=SMG$SET_CURSOR_ABS(D(10),1,1)
			GOTO 2101
		ELSE IF(CHOICE .EQ. 4)THEN
			GOTO 4201
		END IF
	END IF
	S=SMG$ERASE_DISPLAY(D(FIELD))
	S=OTS$CVT_L_TI(VEND,PVENDOR,%VAL(2),%VAL(1))
	S=SMG$PUT_CHARS(D(FIELD),PVENDOR,1,1)
	S=SMG$PUT_CHARS(D(FIELD),VENDOR_NAME(VEND),1,4)
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	IF(CHOICE .EQ.2)THEN
		FIELD=11
	END IF
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	IF(CHOICE.EQ.2)THEN
		GOTO 2101
	ELSE IF(CHOICE .EQ. 4)THEN
		GOTO 4201
	END IF
C	*** EDIT CURRENT HOURS **
2130	S=SMG$ERASE_DISPLAY(D(FIELD))
	INIT=CHAR(TERM)
	S=GET_NUM_PFLOAT(PASTE1,D(3),D(FIELD),KB1,1,1,INIT,8,1,CURRENT_LIFE)
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	IF(CHOICE .EQ. 2)THEN
		GOTO 2101
	ELSE
		GOTO 4201
	END IF
C
C	*********** EDIT THE COMMENT
2140	INIT=CHAR(TERM)
	S=GET_STRING(PASTE1,D(3),D(FIELD),KB1,1,1,INIT,80,1)
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	IF(CHOICE .EQ.2)THEN
		GOTO 2101	
	ELSE
		GOTO 4201
	END IF
C	**** SAVE THE BAG CHANGE ****
2300	S=SMG$UNPASTE_VIRTUAL_DISPLAY(D(4),PASTE1)
C       ** IS THERE AN INSTALL DATE?
	S=SMG$READ_FROM_DISPLAY(D(8),PTEMP11,,1)
	IF(PTEMP11 .EQ. '           ')THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,
	1	'DATE REQUIRED!') 
		STATUS=SMG$SET_CURSOR_ABS(D(8),1,1)
		GOTO 2101
	END IF
C	*** IS THERE A VENDOR?
	S=SMG$READ_FROM_DISPLAY(D(10),PTEMP11,,1)
	IF(PTEMP11(1:2) .EQ. '   ')THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,
	1	'VENDOR REQUIRED!') 
		STATUS=SMG$SET_CURSOR_ABS(D(10),1,1)
		GOTO 2101
	END IF
C	*** GET THE COMMENT *** 
	S=SMG$READ_FROM_DISPLAY(D(11),PTEMP80,,1)
C	*** GET THE CURRENT LIFE FROM THE DISPLAY AND USE IT
C		TO CALCULATE THE HRS AT INSTALL
	S=SMG$READ_FROM_DISPLAY(D(9),PTEMP9,,1)
	READ(PTEMP9,2020)FTEMP
	INSTALL_HRS=HRS_CURRENT -FTEMP
C
C	*** FIRST SEE IF THERE IS A CURRENT RECORD ***
C	    IF THERE IS RESAVE IT AS HISTORY
C	
	FILTER_REF=' '
	FILTER_REF(1:8)=PEQUIP1
	FILTER_REF(9:18)='0000000000'
	ACCESS=0
2310	READ(10,KEYGE=FILTER_REF,IOSTAT=IOS,ERR=2902)FILTER
	GOTO 2400
C
2320	ACCESS=0
2330	READ(10,IOSTAT=IOS,ERR=2904,END=2420)FILTER
2400	IF(FILTER.FILTER_REF(1:8) .NE. FILTER_REF(1:8))GOTO 2420 !* no current rec
	IF(FILTER.FLAG .EQ. 0)THEN
		FILTER.FLAG=1     !* SET TO HISTORY
		FILTER.DATE_OUT=BIN
		FILTER.LIFE=INSTALL_HRS
		REWRITE(10)FILTER
2420		CALL LIB$DAY(J,BIN,) !* SAVE THE NEW CURRENT RECORD
		S=OTS$CVT_L_TI(J,PTEMP10,%VAL(10))
		FILTER_REF(9:18)=PTEMP10
		FILTER.FILTER_REF=FILTER_REF
		FILTER.FLAG=0
		FILTER.POINT_REF=REF.POINT_REF
		FILTER.DATE_IN=BIN
		FILTER.DATE_OUT=0
		FILTER.HRS=INSTALL_HRS
		FILTER.LIFE=0.0
		FILTER.VENDOR=VEND
		FILTER.COMMENT=PTEMP80
		WRITE(10)FILTER
		GOTO 2102
	ELSE
		GOTO 2320
	END IF
C	*** ERROR INVALID EQUIPMENT NUMBER ***************    
2900	IF(IOS .EQ. 36)THEN
		STATUS=SMG$RING_BELL(D(7),3)
		CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,
	1	'INVALID FILTER NUMBER!') 
		STATUS=SMG$SET_CURSOR_ABS(D(7),1,1)
		GOTO 2001
	ELSE IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER FILE ERROR 2900A!')
			GOTO 2001
		END IF 
		GOTO 2003
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER FILE ERROR #290OB!')
		GOTO 2001
	END IF
C
2902	IF(IOS .EQ. 36)THEN
		GOTO 2420 !* NO CURRENT RECORD
	ELSE IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER FILE ERRO 2902A!')
			GOTO 2001
		END IF 
		GOTO 2310
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER REFERENCE FILE ERROR #2902B!')
		GOTO 2001
	END IF
C
2904	IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER FILE ERRO 2904A!')
			GOTO 2001
		END IF 
		GOTO 2330
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER REFERENCE FILE ERROR #2904B!')
		GOTO 2001
	END IF
C*********************************************************************
C	***** EDIT OR DELETE AN ENTRY *****
4000	DO I=6,14
		S=SMG$ERASE_DISPLAY(D(I))
	END DO
	S=SMG$ERASE_DISPLAY(D(4))
C
	IF(CHOICE.EQ.4)THEN
	  S=SMG$PUT_CHARS_WIDE(D(6),'EDIT or DELETE FILTER RECORDS',1,5)
	  S=SMG$PUT_CHARS(D(6),'EQUIPMENT #:',2,1)
	  S=SMG$PUT_CHARS(D(6),'DATE',5,1)
	  S=SMG$PUT_CHARS(D(6),'HRS AT',4,14)
	  S=SMG$PUT_CHARS(D(6),'INSTALL',5,14)
	  S=SMG$PUT_CHARS(D(6),'VENDOR',5,24)
	  S=SMG$PUT_CHARS(D(6),'STATUS',5,41)
	ELSE IF(CHOICE.EQ.3)THEN
	  S=SMG$PUT_CHARS_WIDE(D(6),'PRINT FILTER RECORDS',1,5)
	END IF
C
4003	S=SMG$PUT_CHARS(D(4),'ENTER FILTER NUMBER...',1,1)
	S=SMG$PUT_CHARS(D(4),' or Q to Quit',4,1)
C
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(6),PASTE1,1,1)	
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,9,15)
C
4005	S=SMG$SET_CURSOR_ABS(D(4),1,23)
	S=SMG$RING_BELL(D(4))	
C	**** ASK FOR FILTER NUMBER *****
4001	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
C
	IF(TERM .EQ. 296.OR.TERM.EQ. 81.OR.TERM.EQ.113)THEN	!DO PRESSED SO QUIT
4002		DO I=4,6
			STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(I),PASTE1)
		END DO
		GOTO 50		
	ELSE IF (TERM .EQ. 509)THEN
		GOTO 4002
	 ELSE IF(TERM .LT. 20 .OR. TERM .GT. 122)THEN
		 GOTO 4001 
	ELSE
		GOTO 4010
	END IF
C
4010	INIT=CHAR(TERM)
	CALL INPUT(D(4),KB1,3,1,23,0,INIT,PEQUIP,3,DUM,STATUS)
	IF(STATUS .EQ. 2)THEN
		GOTO 4002
	END IF
	PEQUIP1(6:)=PEQUIP
	ACCESS=0
4012	READ(5,KEY=PEQUIP1,IOSTAT=IOS,ERR=4900)REF
	UNLOCK(5)
	IF(CHOICE.EQ.5)GOTO 6510
C
	RECORD=3
4760	READ(1,REC=RECORD,ERR=9000)POINT
 		DO I=1,40
			IF(POINT.POINT_REF .EQ. REF.POINT_REF)THEN
			  HRS_CURRENT=FLOAT(POINT.COUNT)/12.
			  POINT_REC=RECORD
			  GOTO 4762
			END IF
		END DO
	RECORD=RECORD+1
	GOTO 4760	
4762	CONTINUE
	INSTALL_HRS=0.0
	REMOVE_HRS=0.0
C	*** DISPLAY FILTER EQUIP NUMBER ***
	S=SMG$PUT_CHARS(D(6),REF.EQUIP_NO,2,13)
	S=SMG$PUT_CHARS(D(6),REF.TYPE,2,22)
C
C	*** CURRENT OR ALL? ****
	S=SMG$PUT_CHARS(D(4),'Enter A for ALL or <RETURN> for CURRENT...',
	1			2,1)
	S=SMG$SET_CURSOR_ABS(D(4),2,43)
	S=SMG$RING_BELL(D(4))
	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
C
	IF(TERM .EQ. 296.OR.TERM.EQ.81.OR.TERM.EQ.113)THEN	!DO PRESSED SO QUIT
		GOTO 4002
	ELSE IF(TERM .EQ. 65.OR.TERM.EQ. 97)THEN
		FILTER_STATUS=1
	ELSE
		FILTER_STATUS=0
	END IF
C	*** READ THE FILE ****
C
	CLOSE(10)
C
	OPEN(10,FILE='AGGL_HRS:FILTER_MANAGE.DAT',STATUS='OLD',
	1	FORM='UNFORMATTED',
	1	ORGANIZATION='INDEXED',
	1	ACCESS='KEYED',
	1	SHARED)
C
	IF(CHOICE.EQ.4)THEN
	  S=SMG$UNPASTE_VIRTUAL_DISPLAY(D(4),PASTE1)
	  END_FLAG=0
	  LINE_NO=6
	ELSE IF(CHOICE .EQ.3)THEN  !PRINT TO THE PRINTER
		COUNT=0
		OPEN(6,FILE='SYS$COMMAND',RECL=132,STATUS='UNKNOWN')
		S=SYS$ASCTIM(,CURRENT_TIME,,)
		WRITE(6,1605)PRINT_ON         !SWITCH TO CONTROLLER MODE
		WRITE(6,1607)FF     !FORM FEED
		WRITE(6,4700)CURRENT_TIME(1:17)
		WRITE(6,4702)REF.EQUIP_NO,REF.TYPE
		WRITE(6,4704)
		WRITE(6,4706)
	END IF
4700	FORMAT(' ',A17,9X,'+++ FILTER  RECORDS +++',/)
4702	FORMAT(' ',A8,2X,A16,/)
4704	FORMAT(' ',2X,'DATE',9X,'DATE',8X,'HRS')
4706	FORMAT(' ',3X,'IN',11X,'OUT',6X,'CUR/LIFE',4X,'VENDOR',
	1	14X,'STATUS',/)
C
4708	ACCESS=0
4710	READ(10,IOSTAT=IOS,ERR=4902,END=4100)FILTER
	UNLOCK(10)
	IF(FILTER_STATUS.GT.0)GOTO 4021
	IF(FILTER.FLAG.NE.0)THEN
		GOTO 4708        !WRONG STATUS
	END IF
C
4021	IF(FILTER.POINT_REF .NE.REF.POINT_REF)THEN
		GOTO 4708        !WRONG FILTER
	END IF
C	*** DISPLAY THE RECORD ***
	IF(PRINT .EQ. 0)THEN
	 PTEMP80=' '
	 S=SYS$ASCTIM(,DATE1,FILTER.DATE_IN,)
	 DATE=DATE1(1:11)
	 PTEMP80(1:11)=DATE
	 WRITE(PSTART_HRS,2020)FILTER.HRS
	 PTEMP80(13:21)=PSTART_HRS
	 S=OTS$CVT_L_TI(FILTER.VENDOR,PVENDOR,%VAL(2))
	 PTEMP80(25:26)=PVENDOR
	 PTEMP80(28:43)=VENDOR_NAME(FILTER.VENDOR) 
	 PTEMP80(45:51)=CUR_HIST(FILTER.FLAG)    
	END IF
	IF(CHOICE .EQ. 3)THEN
9999		IF(FILTER.DATE_IN .GT.0)THEN
		  S=SYS$ASCTIM(,DATE_IN,FILTER.DATE_IN,)
		ELSE
			DATE_IN=' '
		END IF
		IF(FILTER.DATE_OUT .GT.0)THEN
		  S=SYS$ASCTIM(,DATE_OUT,FILTER.DATE_OUT,)
		ELSE
			DATE_OUT=' '
		END IF
		IF(FILTER.FLAG .EQ.1)THEN
		  FTEMP=FILTER.LIFE - FILTER.HRS
		ELSE
		  FTEMP=HRS_CURRENT - FILTER.HRS
		END IF
	 	WRITE(PSTART_HRS,2020)FTEMP
		WRITE(6,4720)DATE_IN(1:11),
	1		DATE_OUT(1:11),
	1		PSTART_HRS,
	1		FILTER.VENDOR,
	1		VENDOR_NAME(FILTER.VENDOR),
	1		CUR_HIST(FILTER.FLAG) 
		WRITE(6,4721)FILTER.COMMENT
		COUNT=COUNT+1
		IF(COUNT.GT.48)THEN
		  COUNT=0
		  WRITE(6,1607)FF     !FORM FEED
		  WRITE(6,4700)CURRENT_TIME(1:17)
		  WRITE(6,4702)REF.EQUIP_NO,REF.TYPE
		  WRITE(6,4704)
		  WRITE(6,4706)
		END IF
		GOTO 4708
	END IF
4720	FORMAT(' ',A11,2X,A11,1X,A9,2X,I2,1X,A16,2X,A7)
4721	FORMAT(' ',A80)
	S=SMG$PUT_CHARS(D(6),PTEMP80,LINE_NO,1)
	LINE_NO=LINE_NO+1
	IF(LINE_NO .GT. 23)THEN
		GOTO 4120
	END IF
	GOTO 4710
4100	IF(CHOICE.EQ. 3)THEN
		WRITE(6,1605)PRINT_OFF         !SWITCH OFF
		GOTO 4002
	END IF
C
	END_FLAG=1
4120	IF(END_FLAG .EQ.1)THEN
		S=SMG$PUT_CHARS(D(6),
	1'** END-OF-FILE **  Use ^v keys to move  <SELECT> to view a
	1 record   Q to Quit',24,1,,2)
	ELSE
		S=SMG$PUT_CHARS(D(6),
	1'<NEXT SCREEN>  or  Use ^v keys to move  <SELECT> to view a
	1 record   Q to Quit',24,1,,2)
	END IF
	S=SMG$CHANGE_RENDITION(D(6),6,1,1,40,0,2)
	S=SMG$SET_CURSOR_ABS(D(6),6,1)
	S=SMG$RING_BELL(D(4))	
4122	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
	IF(TERM .EQ. 296.OR.TERM.EQ.509.OR.TERM .EQ. 81.OR.TERM.EQ.113)THEN
		GOTO 4002
	ELSE IF (TERM .EQ.274) THEN        !UP ARROW PRESSED
		STATUS=SMG$RETURN_CURSOR_POS(D(6),R,C)
		IF(R.EQ.6)GOTO 4122
		J=-1
		STATUS=SMG$SET_CURSOR_REL(D(6),J,0)
		STATUS=SMG$RETURN_CURSOR_POS(D(6),R,C)
		STATUS=SMG$CHANGE_RENDITION(D(6),R,1,1,59,0,2)
		STATUS=SMG$CHANGE_RENDITION(D(6),(R+1),1,1,59,0,0)
		GOTO 4122
	ELSE  IF(TERM .EQ. 275)THEN   !DOWN ARROW PRESSED
		STATUS=SMG$RETURN_CURSOR_POS(D(6),R,C)
		IF(R.EQ.23)GOTO 4122
		J=1
		STATUS=SMG$SET_CURSOR_REL(D(6),J,0)
		STATUS=SMG$RETURN_CURSOR_POS(D(6),R,C)
		STATUS=SMG$CHANGE_RENDITION(D(6),R,1,1,59,0,2)
		STATUS=SMG$CHANGE_RENDITION(D(6),(R-1),1,1,59,0,0)
		GOTO 4122
	ELSE IF(TERM .EQ.316.AND.END_FLAG.EQ.0)THEN
		S=SMG$ERASE_DISPLAY(D(6),6,1)
		LINE_NO=6
		GOTO 4710
	ELSE IF(TERM .EQ.314)THEN
		STATUS=SMG$RETURN_CURSOR_POS(D(6),R,C)
		S=SMG$READ_FROM_DISPLAY(D(6),PTEMP80,,R)
		IF(PTEMP80(1:8) .EQ. '        ')GOTO 4122  
		PTEMP23=' '
		PTEMP23(1:11)=PTEMP80(1:11)
		S=SYS$BINTIM(PTEMP23,BIN)
		CALL LIB$DAY(J,BIN)
		S=OTS$CVT_L_TI(J,PTEMP10,%VAL(10),,)
		FILTER_REF(9:18)=PTEMP10
		FILTER_REF(1:8)=REF.EQUIP_NO
		IF(J.EQ.0)THEN
			GOTO 4122
		ELSE
			GOTO 4130   !READ THE RECORD
		END IF
	ELSE
		GOTO 4122
	END IF
C	** REREAD THE RECORD ***
4130	ACCESS=0
4132	READ(10,KEY=FILTER_REF,IOSTAT=IOS,ERR=4904)FILTER
	UNLOCK(10)
	FILTER_STATUS=FILTER.FLAG
	VEND=FILTER.VENDOR
C	*** DISPLAY THE RECORD ON THE EDIT SCREEN ***
	DO I=6,14
		S=SMG$ERASE_DISPLAY(D(I))
	END DO
C
C	**** FILL DISPLAY SCREEN **************
	S=SMG$PUT_CHARS_WIDE(D(6),'* Edit or delete a Filter Record *',1,1)
	S=SMG$PUT_CHARS(D(6),'EQUIPMENT NUMBER',3,3)
	S=SMG$PUT_CHARS(D(6),'DATE INSTALLED',7,3)
	S=SMG$PUT_CHARS(D(6),'DATE REMOVED',7,40)
	S=SMG$PUT_CHARS(D(6),'EQUIP HRS AT INSTALL:',11,1)
	S=SMG$PUT_CHARS(D(6),'EQUIP HRS AT REMOVAL:',11,40)
	S=SMG$PUT_CHARS(D(6),'VENDOR',15,3)
	S=SMG$PUT_CHARS(D(6),'COMMENT',19,3)
	S=SMG$PUT_CHARS(D(6),
	1'STATUS: H History  C Current',3,40)
	S=SMG$PUT_CHARS(D(6),
	1'* Note: Installation date cannot be changed.',15,30)
	S=SMG$PUT_CHARS(D(6),
	1'*  If necessary, delete the record and re-enter it.',16,30)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(6),PASTE1,1,1)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(7),PASTE1,5,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(8),PASTE1,9,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(9),PASTE1,13,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(10),PASTE1,17,5)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(11),PASTE1,21,1)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(12),PASTE1,5,40)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(13),PASTE1,9,40)
	STATUS=SMG$PASTE_VIRTUAL_DISPLAY(D(14),PASTE1,13,40)
C	
	S=SMG$PUT_CHARS(D(6),
	1'* Use the TAB key or Arrow keys to move ',
	1	23,1,1,1)
	S=SMG$PUT_CHARS(D(6),
	1'* Press <DO> or F10 to Save or Press Q to Quit *',
	1	24,1,1,2)
C
	S=SMG$PUT_CHARS(D(7),FILTER.FILTER_REF(1:8),1,1)
	S=SMG$PUT_CHARS(D(12),CUR_HIST(FILTER.FLAG),1,1)    
C
	S=SYS$ASCTIM(,DATE1,FILTER.DATE_IN,)
	DATE=DATE1(1:11)
	S=SMG$PUT_CHARS(D(8),DATE,1,1)
C
	IF(FILTER.DATE_OUT .NE.0)THEN
	  S=SYS$ASCTIM(,DATE1,FILTER.DATE_OUT,)
	  DATE=DATE1(1:11)
	  S=SMG$PUT_CHARS(D(13),DATE,1,1)
	END IF
	WRITE(PSTART_HRS,2020)FILTER.HRS
	S=SMG$PUT_CHARS(D(9),PSTART_HRS,1,1)
C
	WRITE(PSTART_HRS,2020)FILTER.LIFE
	S=SMG$PUT_CHARS(D(14),PSTART_HRS,1,1)
	S=OTS$CVT_L_TI(FILTER.VENDOR,PVENDOR,%VAL(2))
	S=SMG$PUT_CHARS(D(10),PVENDOR,1,1)
	S=SMG$PUT_CHARS(D(10),VENDOR_NAME(FILTER.VENDOR),1,4)
	S=SMG$PUT_CHARS(D(12),CUR_HIST(FILTER.FLAG),1,1)
	S=SMG$PUT_CHARS(D(11),FILTER.COMMENT,1,1)
C
C	** NOTE THAT THE INSTALL DATE CONNOT BE CHANGED BECAUSE IT
C		PART OF THE KEY. IF IT NEEDS TO BE CAHNGED THE RECORD HAS TO 
C		BE DELETED AND RE-ENTERED
	DO I=8,14
		S=SMG$SET_CURSOR_ABS(D(I),1,1)
	END DO
	F=1
	FIELD=TTD(F)
	MIN_FIELD=1  !FIRST FIELD CURSOR GOES TO
	MAX_FIELD=7 !LAST FIELD CURSOR GOES TO
4200	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	STATUS=SMG$RETURN_CURSOR_POS(D(FIELD),R,C)  
	S=SMG$RING_BELL(D(8))	
4201	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300,D(FIELD))
	IF(TERM .EQ. 296.OR.TERM .EQ. 290)THEN	!DO ALONE PRESSED SO CONTINUE
		DELETE=0
		S=SMG$ERASE_DISPLAY(D(4))
		S=SMG$PUT_CHARS(D(4),'Press <REMOVE>  to Delete',
	1				1,1)
		S=SMG$PUT_CHARS(D(4),'or SAVE THE CHANGES (Y/N)...',
	1				2,1)
		S=SMG$SET_CURSOR_ABS(D(4),2,29)
		S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,10,20)
		S=SMG$RING_BELL(D(4))
		S=SMG$READ_KEYSTROKE(KB1,TERM,,300)
		IF(TERM.EQ.89.OR.TERM.EQ.121)THEN
			GOTO 4300
		ELSE IF(TERM .EQ.313)THEN
		  S=SMG$ERASE_DISPLAY(D(4))
		  S=SMG$PUT_CHARS(D(4),'DELETE THE RECORD!',
	1				1,1)
		  S=SMG$PUT_CHARS(D(4),'ARE YOU SURE (Y/N)?...',
	1				2,1)
		  S=SMG$SET_CURSOR_ABS(D(4),2,23)
		  S=SMG$RING_BELL(D(4),3)
		  DELETE=0
		  S=SMG$READ_KEYSTROKE(KB1,TERM,,300)
		  IF(TERM.EQ.89.OR.TERM.EQ.121)THEN
			DELETE=1
			GOTO 4300
		  ELSE 
			DELETE=0
		  END IF
		END IF
4202		DO I=4,14
			STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(I),PASTE1)
		END DO
		GOTO 50		
	ELSE IF(TERM .EQ. 509.OR.TERM.EQ.81 .OR.TERM.EQ.113)THEN
		GOTO 4202		!TIMED OUT AFTER 5 MINUTES
	ELSE IF(TERM .EQ. 9)THEN   !* TAB
		F=F+1
		IF(F .GT. MAX_FIELD)F=MIN_FIELD
		FIELD=TTD(F)
		GOTO 4200
	ELSE IF(TERM .EQ. 276 .OR. TERM .EQ. 277)THEN 
C		*******  MOVE TO VARIOUS FIELDS ************
		IF(TERM .EQ. 277) THEN
		  F=F+1
		  IF(F .GT. MAX_FIELD)F=MIN_FIELD
		ELSE IF(TERM .EQ. 276) THEN
		  F=F-1
		  IF(F .LT. MIN_FIELD)F=MAX_FIELD
		END IF
		FIELD=TTD(F)
		STATUS=SMG$SET_CURSOR_ABS(D(FIELD))
		GOTO 4201
	ELSE IF(TERM .GT.32.AND.TERM.LT.123)THEN     !
		 GOTO(4400,4201,4404,4201,4201,2120,2140)
	1			(F)   
	ELSE
		GOTO 4201
	END IF
C
C	*** EDIT STATUS FLAG ***
4400	IF(TERM .EQ. 67 .OR. TERM.EQ. 99)THEN !* C FOR CURRENT
		FILTER_STATUS=0
	ELSE IF(TERM .EQ. 72.OR.TERM .EQ. 104)THEN !* H FOR HISTORY
		FILTER_STATUS=1
	ELSE
		GOTO 4201
	END IF
	S=SMG$PUT_CHARS(D(FIELD),CUR_HIST(FILTER_STATUS),1,1)
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	GOTO 4201
C       *** GET DATE AND CALC HOURS BASED ON DATE ***
4404	GOTO 2100
4406	IF(FIELD .EQ. 8)THEN
		S=SMG$PUT_CHARS(D(9),PSTART_HRS,1,1)
		INSTALL_HRS=START
	ELSE IF(FIELD .EQ. 13)THEN
		S=SMG$PUT_CHARS(D(14),PSTART_HRS,1,1)
		REMOVE_HRS=START
	END IF
	S=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
	GOTO 4201
C	*** SAVE OR DELETE ****
C
C	*** GET THE COMMENT *** 
4300	S=SMG$UNPASTE_VIRTUAL_DISPLAY(D(4),PASTE1)
	S=SMG$READ_FROM_DISPLAY(D(11),PTEMP80,,1)
C
C	*** IS THERE A VENDOR?
	S=SMG$READ_FROM_DISPLAY(D(10),PTEMP11,,1)
	IF(PTEMP11(1:2) .EQ. '   ')THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,
	1	'VENDOR REQUIRED!') 
		F=6
		FIELD=TTD(F)
		STATUS=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
		GOTO 4201
	END IF
C	** IF HISTORY CHECK FOR REMOVE DATE **
	IF(FILTER_STATUS .EQ. 1)THEN
	  S=SMG$READ_FROM_DISPLAY(D(13),PTEMP11,,1)
	  IF(PTEMP11(1:2) .EQ. '   ')THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,
	1	'REMOVAL DATE REQUIRED!') 
		F=3
		FIELD=TTD(F)
		STATUS=SMG$SET_CURSOR_ABS(D(FIELD),1,1)
		GOTO 4201
	  END IF
	END IF
	CALL DAYS_1(PTEMP11,STATUS,J,PTEMP11,BIN2)
C	**     REREAD THE RECORD ****
C
	ACCESS=0
4302	READ(10,KEY=FILTER_REF,IOSTAT=IOS,ERR=4906)FILTER
C
	IF(DELETE .EQ. 1)THEN
		DELETE(10)
		GOTO 4202
	ELSE     !** SAVE CHANGES
		FILTER.COMMENT=PTEMP80
		FILTER.FLAG=FILTER_STATUS
		FILTER.VENDOR=VEND
		FILTER.DATE_OUT=BIN2
		IF(INSTALL_HRS .GT. 0.0)THEN
			FILTER.HRS=INSTALL_HRS
		END IF
		IF(REMOVE_HRS .GT. 0.0)THEN
			FILTER.LIFE=REMOVE_HRS
		END IF
		IF(FILTER.FLAG .EQ.0)THEN
		  FILTER.LIFE=0.0
		  FILTER.DATE_OUT=0
		END IF
		REWRITE(10)FILTER
	END IF
	GOTO 4202
C	*** ERROR INVALID EQUIPMENT NUMBER ***************    
4900	IF(IOS .EQ. 36)THEN
		STATUS=SMG$RING_BELL(D(4),3)
		CALL ERR_MSG(PASTE1,D(3),KB1,D(4),1,23,
	1	'INVALID FILTER NUMBER!') 
		STATUS=SMG$SET_CURSOR_ABS(D(4),1,23)
		GOTO 4001
	ELSE IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'RECORD UNAVAILABLE 4900A!')
			GOTO 4002
		END IF 
		GOTO 4012
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'FILTER REFERENCE FILE ERROR #4900B!')
		GOTO 4002
	END IF
C
4902	IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'RECORD UNAVAILABLE 4902A!')
			GOTO 4002
		END IF 
		GOTO 4710
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'FILTER FILE ERROR #4902B!')
		GOTO 4002
	END IF
C
4904	IF(IOS .EQ. 36)THEN
		STATUS=SMG$RING_BELL(D(4),3)
		CALL ERR_MSG(PASTE1,D(3),KB1,D(4),1,23,
	1	'ERROR 4904-1: WAS DELETED!') 
		STATUS=SMG$SET_CURSOR_ABS(D(4),1,23)
		GOTO 4001
	ELSE IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'RECORD UNAVAILABLE 4904A!')
			GOTO 4002
		END IF 
		GOTO 4132
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'FILTER REFERENCE FILE ERROR #4904B!')
		GOTO 4002
	END IF
C
4906	IF(IOS .EQ. 36)THEN
		STATUS=SMG$RING_BELL(D(4),3)
		CALL ERR_MSG(PASTE1,D(3),KB1,D(4),1,23,
	1	'ERROR 4906-1: WAS DELETED!') 
		STATUS=SMG$SET_CURSOR_ABS(D(4),1,23)
		GOTO 4001
	ELSE IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'RECORD UNAVAILABLE 4906A!')
			GOTO 4002
		END IF 
		GOTO 4302
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'FILTER REFERENCE FILE ERROR #4906B!')
		GOTO 4002
	END IF
C*****************************************************************************
C	**** EDIT THE VENDOR LIST OR SET A DEFAULT VENDOR ***
6000	S=SMG$ERASE_DISPLAY(D(6))
	S=SMG$ERASE_DISPLAY(D(4))
	S=SMG$PUT_CHARS(D(4),'Enter D to set a DEFAULT Vendor',1,1)
	S=SMG$PUT_CHARS(D(4),'or <RETURN> to Edit the Vendor list...',2,1)
	S=SMG$PUT_CHARS(D(6),'OR press Q to cancel and return to the Menu',
	1	24,1,,2)
C
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(6),PASTE1,1,1)	
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,9,15)
C
	S=SMG$SET_CURSOR_ABS(D(4),2,39)
	S=SMG$RING_BELL(D(4))	
6001	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
C
	IF(TERM .EQ. 509 .OR.TERM .EQ. 81 .OR.TERM.EQ. 113)THEN
		GOTO 6002
	ElSE IF(TERM .EQ. 68.OR.TERM.EQ.100)THEN !* D PRESSED- SET DEFAULT
		FLAG=1
	ELSE IF(TERM .EQ. 13)THEN  !* EDIT VENDOR LIST
		FLAG=0
	ELSE
6002		DO I=4,6
			STATUS=SMG$UNPASTE_VIRTUAL_DISPLAY(D(I),PASTE1)
		END DO
		GOTO 50		
	END IF
C
	S=SMG$UNPASTE_VIRTUAL_DISPLAY(D(4),PASTE1)
	IF(FLAG .EQ. 1)THEN
	  S=SMG$PUT_CHARS_WIDE(D(6),'SET a Vendor Default',1,5)
	ELSE
	  S=SMG$PUT_CHARS_WIDE(D(6),'Edit the Vendor list',1,5)
	END IF
C
	CLOSE(3)
 	OPEN(3,FILE='AGGL_HRS:VENDOR.DAT',STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=4,
	1    USEROPEN=UFO_OPEN,SHARED,
	1    FORM='UNFORMATTED')
C
	DO I=1,24
		READ(3,REC=I,ERR=9000)VENDOR_NAME(I)
	END DO
C
	DO I=1,12
		S=OTS$CVT_L_TI(I,PTEMP2)
		S=SMG$PUT_CHARS(D(6),PTEMP2,(I+2),1)
		S=SMG$PUT_CHARS(D(6),VENDOR_NAME(I),(I+2),4)
	END DO
	DO I=13,24
		S=OTS$CVT_L_TI(I,PTEMP2)
		S=SMG$PUT_CHARS(D(6),PTEMP2,((I-12)+2),24)
		S=SMG$PUT_CHARS(D(6),VENDOR_NAME(I),((I-12)+2),27)
	END DO
	IF(FLAG .EQ. 1)GOTO 6500
C	*** EDIT VENDOR LIST ***
	S=SMG$ERASE_DISPLAY(D(4))
	S=SMG$PUT_CHARS(D(4),'Enter Vendor number to edit...',1,1)
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,19,9)
	S=SMG$RING_BELL(D(4))	
	S=SMG$SET_CURSOR_ABS(D(4),1,31)
6010	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
	IF(TERM .EQ. 509 .OR.TERM .EQ. 81 .OR.TERM.EQ. 113)THEN
		GOTO 6002
	ELSE IF(TERM .GT.47.AND.TERM.LT.58)THEN
		GOTO 6020
	ELSE
		GOTO 6010
	END IF
C
6020	INIT=CHAR(TERM)
	CALL INPUT(D(4),KB1,2,1,31,0,INIT,PTEMP2,2,DUM,STATUS)
	S=OTS$CVT_TI_L(PTEMP2,RECORD,,%VAL(1))
	IF(RECORD .EQ. 0.OR.RECORD.GT.24)THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,D(4),1,31,
	1	  'INCORRECT VENDOR NUMBER!') 
		S=SMG$SET_CURSOR_ABS(D(4),1,31)
		GOTO 6010
	END IF
C
	I=RECORD
	S=OTS$CVT_L_TI(I,PTEMP2)
	IF(I.LT.13)THEN
		S=SMG$PUT_CHARS(D(6),PTEMP2,(I+2),1,,2)
		S=SMG$PUT_CHARS(D(6),VENDOR_NAME(I),(I+2),4,,2)
	ELSE
		S=SMG$PUT_CHARS(D(6),PTEMP2,((I-12)+2),24,,2)
		S=SMG$PUT_CHARS(D(6),VENDOR_NAME(I),((I-12)+2),27,,2)
	END IF
	S=SMG$PUT_CHARS(D(4),'Enter the NEW Vendor (16 chars max)',2,1)
	S=SMG$SET_CURSOR_ABS(D(4),3,1)
6030	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
	IF(TERM .EQ. 509 .OR.TERM .EQ. 81 .OR.TERM.EQ. 113)THEN
		GOTO 6002
	ELSE IF(TERM .LT. 48 .OR.TERM .GT. 125)THEN
		GOTO 6030
	END IF
	INIT=CHAR(TERM)
	CALL INPUT(D(4),KB1,16,3,1,2,INIT,VENDOR_NAME1,16,DUM,STATUS)
	IF(STATUS.EQ.2)GOTO 6002
	IF(I.LT.13)THEN
		S=SMG$PUT_CHARS(D(6),PTEMP2,(I+2),1,,2)
		S=SMG$PUT_CHARS(D(6),VENDOR_NAME1,(I+2),4,,2)
	ELSE
		S=SMG$PUT_CHARS(D(6),PTEMP2,((I-12)+2),24,,2)
		S=SMG$PUT_CHARS(D(6),VENDOR_NAME1,((I-12)+2),27,,2)
	END IF
	S=SMG$ERASE_DISPLAY(D(4))
	S=SMG$PUT_CHARS(D(4),'SAVE CHANGES (Y\N)??',1,1)
	S=SMG$SET_CURSOR_ABS(D(4),1,21)
	S=SMG$RING_BELL(D(4),3)
C	*** SAVE THE CHANGES
	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
	IF(TERM.EQ.89.OR.TERM.EQ.121)THEN
		GOTO 6100
	ELSE
		GOTO 6002
	END IF
C
6100	WRITE(3,REC=RECORD,ERR=9000)VENDOR_NAME1
	CLOSE(3)
 	OPEN(3,FILE='AGGL_HRS:VENDOR.DAT',STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='SEQUENTIAL',
	1    RECORDTYPE='FIXED',
	1    RECL=4,
	1    USEROPEN=UFO_OPEN,SHARED,
	1    FORM='UNFORMATTED')
C
	DO I=1,24
		READ(3,ERR=9000)VENDOR_NAME(I)
	END DO
	CLOSE(3)
	VENDOR_NAME(0)='  NONE          '
	GOTO 6002
C	*** SET A VENDOR DEFAULT ***
6500	S=SMG$ERASE_DISPLAY(D(4))
	S=SMG$PUT_CHARS(D(4),'ENTER FILTER NUMBER...',1,1)
	S=SMG$PASTE_VIRTUAL_DISPLAY(D(4),PASTE1,19,9)
	S=SMG$SET_CURSOR_ABS(D(4),1,31)
	GOTO 4005
6510	S=SMG$PUT_CHARS(D(6),REF.EQUIP_NO,16,1)
	S=SMG$PUT_CHARS(D(6),REF.TYPE,16,10)
	S=SMG$PUT_CHARS(D(6),'DEFAULT VENDOR:',17,1)
	S=SMG$PUT_CHARS(D(6),VENDOR_NAME(REF.DEFAULT_VENDOR),17,17,,2)
	S=SMG$PUT_CHARS(D(4),'Enter new Vendor number...',2,1)
	S=SMG$SET_CURSOR_ABS(D(4),2,27)
6512	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
	IF(TERM .EQ. 509 .OR.TERM .EQ. 81 .OR.TERM.EQ. 113)THEN
		GOTO 6002
	ELSE IF(TERM .GT.47.AND.TERM.LT.58)THEN
		GOTO 6520
	ELSE
		GOTO 6512
	END IF
C
6520	INIT=CHAR(TERM)
	CALL INPUT(D(4),KB1,2,2,27,0,INIT,PTEMP2,2,DUM,STATUS)
	S=OTS$CVT_TI_L(PTEMP2,RECORD,,%VAL(1))
	IF(RECORD .EQ. 0.OR.RECORD.GT.24)THEN
		CALL ERR_MSG(PASTE1,D(3),KB1,D(4),2,27,
	1	  'INCORRECT VENDOR NUMBER!') 
		S=SMG$SET_CURSOR_ABS(D(4),2,27)
		GOTO 6512
	END IF
	S=SMG$PUT_CHARS(D(6),VENDOR_NAME(RECORD),17,17,,2)
	S=SMG$ERASE_DISPLAY(D(4))
	S=SMG$PUT_CHARS(D(4),'SAVE CHANGES (Y\N)??',1,1)
	S=SMG$SET_CURSOR_ABS(D(4),1,21)
	S=SMG$RING_BELL(D(4),3)
C	*** SAVE CHANGES ***
	STATUS=SMG$READ_KEYSTROKE(KB1,TERM,,300)
	IF(TERM.EQ.89.OR.TERM.EQ.121)THEN
		GOTO 6600
	ELSE
		GOTO 6002  !* QUIT
	END IF
C
6600	ACCESS=0
6602	READ(5,KEY=PEQUIP1,IOSTAT=IOS,ERR=6900)REF
	REF.DEFAULT_VENDOR=RECORD
	REWRITE(5,ERR=9000)REF
	CLOSE(5)
C
	OPEN(5,FILE='AGGL_HRS:FILTER_REF.DAT',STATUS='OLD',
	1	FORM='UNFORMATTED',
	1	ORGANIZATION='INDEXED',
	1	ACCESS='KEYED',
	1	SHARED)
C
	I=1
6700	ACCESS=0
6702	READ(5,IOSTAT=IOS,ERR=6902,END=6704)REF
	UNLOCK(5)
	POINT_REF(I)=REF.POINT_REF
	DESCR_REF(I)(1:8)=REF.EQUIP_NO
	DESCR_REF(I)(9:9)=' '
	DESCR_REF(I)(10:)=REF.TYPE
	VENDOR(I)=REF.DEFAULT_VENDOR
	I=I+1
	GOTO 6700
C
6704	GOTO 6002
C
6900	IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'RECORD UNAVAILABLE!')
			GOTO 6002
		END IF 
		GOTO 6602
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'FILTER REFERENCE FILE ERROR #6900!')
		GOTO 6002
	END IF
C
6902	IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			CALL ERR_MSG(PASTE1,D(3),KB1,0,0,0,    
	1		'RECORD UNAVAILABLE!')
			GOTO 9000
		END IF 
		GOTO 6702
	ELSE
		CALL ERR_MSG(PASTE1,D(3),KB1,D(7),1,1,    
	1		'FILTER REFERENCE FILE ERROR #6902!')
		GOTO 9000
	END IF
C*****************************************************************************
C**********************************************************************
9000	S=SMG$DELETE_PASTEBOARD(PASTE1)
C	DO I=1,11
C		CLOSE(I)
C	END DO
	END
C************************************************************************
C
	SUBROUTINE	INPUT(D,K,W,R,C,IT,IC,BACK,LEN1,SPECIAL,
	1			STATUS)
C
	IMPLICIT	INTEGER(A-Z)
C
	INTEGER*4	D	!DISPLAY ID
	INTEGER*4	K	!KEYBOARD ID
	INTEGER*4	W	!DISPLAY MAX WIDTH
	INTEGER*4	R	!DISPLAY ROW
	INTEGER*4	C	!DISPLAY COLUMN
	INTEGER*4	IT	!TYPE OF INPUT
	INTEGER*4	LEN1	!LENGTH OF INPUT
	INTEGER*4	STATUS	!	
	INTEGER*2	TERM_CHAR
	INTEGER*4	OFLAG
	CHARACTER*(*)	BACK
	CHARACTER*80	LINE,TEMP
	CHARACTER*1	CHARACTER,IC
	CHARACTER*10	DIGITS/'0123456789'/
	CHARACTER*12	INTEGERS/'-+0123456789'/
	CHARACTER*13	FLOATING/'+-.0123456789'/
	CHARACTER*31	DATES/'ABCDEFGJLMNOPRSTUVY
	1-0123456789:'/
	CHARACTER*(*)	SPECIAL
C
	OFLAG=0
	LINE='                                        
	1                                        '
	TEMP='                                        
	1                                        '
	S=SMG$PUT_CHARS(D,IC,R,C)
	I=C+1
	LINE(C:C)=IC
	S=SMG$SET_CURSOR_ABS(D,R,I)
100	STATUS=SMG$READ_KEYSTROKE(K,TERM_CHAR,,600)
	IF(TERM_CHAR .EQ. 13)THEN
		GOTO 200
	ELSE IF(TERM_CHAR .EQ. 274)THEN
		GOTO 200
	ELSE IF(TERM_CHAR .EQ. 275)THEN
		GOTO 200
	ELSE IF(TERM_CHAR .EQ. 296)THEN
		STATUS=2
		RETURN
	ELSE IF(TERM_CHAR .EQ. 509)THEN
		STATUS=2
		RETURN
	ELSE IF(TERM_CHAR .EQ. 127.AND.OFLAG.EQ.0)THEN
		I=I-1
		IF(I.LT.C)THEN
			I=C
			GOTO 100
		END IF
		S=SMG$PUT_CHARS(D,' ',R,I)
		S=SMG$SET_CURSOR_ABS(D,R,I)
		LINE(I:I)=' '
		GOTO 100
	ELSE IF(TERM_CHAR .EQ. 127.AND.OFLAG.EQ.1)THEN
		IF(I.EQ.1)GOTO 100
		TEMP(1:(W-I+1))=LINE(I:)
		LINE((I-1):(W-1))=TEMP(1:(W-I+1))
		LINE(W:W)=' '
		S=SMG$PUT_CHARS(D,LINE,R,C)
		I=I-1
		IF(I.LT.C)THEN
			I=C
			GOTO 100
		END IF
		S=SMG$SET_CURSOR_ABS(D,R,I)
		GOTO 100
	ELSE IF(TERM_CHAR.EQ.276)THEN
		I=I-1
		IF(I.LT.C)THEN
			I=C
			GOTO 100
		END IF
		S=SMG$SET_CURSOR_ABS(D,R,I)
		GOTO 100
	ELSE IF(TERM_CHAR.EQ.277)THEN
		I=I+1
		IF(I.GT.(W+C-1))THEN
			I=W+C-1
			GOTO 100
		END IF
		S=SMG$SET_CURSOR_ABS(D,R,I)
		GOTO 100
	ELSE IF(TERM_CHAR.LT.20.OR.TERM_CHAR.GT.126)THEN
		GOTO 100
	ELSE
		GOTO 104
	END IF
C	*** TEST CHARACTERS ******
104	CHARACTER=CHAR(TERM_CHAR)
	IF(IT .EQ. 0)GOTO 105
	GOTO(110,120,130,140,150)IT
C	*** INTEGER TEST ****
105	INDEX=STR$FIND_FIRST_NOT_IN_SET(CHARACTER,INTEGERS)
	IF(INDEX .GE. 1)GOTO 100
	GOTO 180
C	*** FLOATING POINT TEST ****
110	INDEX=STR$FIND_FIRST_NOT_IN_SET(CHARACTER,FLOATING)
	IF(INDEX .GE. 1)GOTO 100
	GOTO 180
C	*** ANY CHARACTER TEST ***
120	GOTO 180
C	*** CHARACTER LIMITED SET  *****
130	INDEX=STR$FIND_FIRST_NOT_IN_SET(CHARACTER,SPECIAL)
	IF(INDEX .GE. 1)GOTO 100
	GOTO 180
C	*** NUMERIC DIGITS ONLY ***
140	INDEX=STR$FIND_FIRST_NOT_IN_SET(CHARACTER,DIGITS)
	IF(INDEX .GE. 1)GOTO 100
	GOTO 180
C	*** DATE ***
150	S=STR$UPCASE(CHARACTER,CHARACTER)
	INDEX=STR$FIND_FIRST_NOT_IN_SET(CHARACTER,DATES)
	IF(INDEX .GE. 1)GOTO 100
C
C
180	IF(OFLAG .EQ. 0)THEN
		LINE(I:I)=CHARACTER
		S=SMG$PUT_CHARS(D,CHARACTER,R,I)
		I=I+1
		IF(I.GT.(W+C-1))THEN
			BACK=LINE(C:(C+LEN1))
			RETURN
		END IF
		GOTO 100
	ELSE IF(OFLAG .EQ. 1)THEN
		LINE(I+1:)=LINE(I:)
		LINE(I:I)=CHARACTER
		S=SMG$PUT_CHARS(D,LINE,R,1)
		I=I+1
		IF(I.GT.(W+C-1))THEN
			BACK=LINE(C:(C+LEN1))
			RETURN
		END IF
		S=SMG$SET_CURSOR_ABS(D,R,I)
		GOTO 100
	ELSE
		GOTO 100
	END IF
200	BACK=LINE(C:(C+LEN1))
	RETURN
	END
C	*********************************************************************
C	SUBROUTINE DATE_CHECK
C
	SUBROUTINE	DATE_CHECK(REF,STATUS,DAYS_BEFORE)
C
	INTEGER*4	REF,REF1,STATUS,BIN(2),DAYS_BEFORE
	CHARACTER*23	NOW
C
	CALL LIB$DATE_TIME(NOW)
	CALL SYS$BINTIM(NOW,BIN)
	CALL LIB$DAY(REF1,BIN,)
C
	DAYS_BEFORE=REF1-REF
	IF((REF1-REF) .GT. 30)THEN
		STATUS=1
	ELSE
		STATUS=0
	END IF
	RETURN
	END
C***********************************************************************
C	SUBROUTINE ESTIMATED HOURS
C
	SUBROUTINE  EST_HRS(DAYS_BEFORE,RECORD,HRS)
C
	INTEGER*4	DAYS_BEFORE,RECORD,TEMP_HRS
	REAL*4		HRS
	BYTE		HRS1(32)
C
	READ(4,REC=RECORD,ERR=9000)HRS1
C
	DO K=1,32
		IF(HRS1(K) .EQ. 127)GOTO 10
	END DO
C       *** DETERMINE QUANTITY OF HOURS TO SUBTRACT ****
10	TEMP_HRS=0
12	K=K-1
	IF(K .LT. 1)K=32
	TEMP_HRS=TEMP_HRS+HRS1(K)	
	DAYS_BEFORE=DAYS_BEFORE-1
	IF(DAYS_BEFORE .LE. 0)THEN
		HRS=FLOAT(TEMP_HRS)  !DONE
		RETURN
	ELSE
		GOTO 12
	END IF
9000	HRS=0.
	RETURN
	END
