C
	integer ufo_OPEN,ndat(2)
	character aone/'1'/
	integer bone(2),btim(2)
	character atim*23
	EXTERNAL UFO_OPEN
	INCLUDE 'SYS$LIBRARY:GKSDEFS.FOR'
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
	CHARACTER*4	BDOCK,BACCT,BGRADE
	CHARACTER MON(12)*3/'JAN','FEB','MAR','APR','MAY','JUN','JUL',
	1	'AUG','SEP','OCT','NOV','DEC'/,ADAT*11,A2*2
	1,ASCD*11,LDAT*23,adate*8,key*6
	INTEGER	BDATEX,BLK,BCNTR,TIM(2),BADBOAT
	
C
	REAL XV(43)
	INTEGER DTX(2,43,6),ITIME
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	LOGICAL*1	ESC/"033/
	INTEGER*4	SCRLUN/6/
C
C
	CHARACTER CSI/155/,exp*4/'?43h'/,com*4/'?431'/,col*4/'?44h'/,
	1	prn*2/'?i'/,PCO*2/'5i'/,PCF*2/'4i'/,o5*5,o3*3,GDATE*23
CCCCCCCCCCCCC
	CHARACTER ES/27/,BSL/'\'/,ASQ,RSIDE*12,CPA*6,CPKA*6,AS(6)*5,
	1	RRSIDE*18,DX23*23,RSV*5,label*40
CCCCCCCCCCCCC
C
	REAL SD(5),SDA(5),SDR(5),SDRA(5),AVG(5)
	INTEGER	FC,BD,CPR,STAT,STATUS,FA
C
	REAL  TOPX,TOPR
	DATA 	TOPX /.81375/	!TOP OF X GRAPH 
	DATA	TOPR /.39375/	!TOP OF R GRAPH
C
	INTEGER*2 TDATA(7),STD(7),STD6(7),FILD(7)
C
C
	DOUBLE PRECISION T,TA,
	1		 SX,SX2,SUMB,SUMA,NC,SDN,SXR,SX2R,SDNR
	1		 SXA,SX2A,SDNA,SXRA,SX2RA,SDNRA
C
	REAL  YPB(42,3),YPA(21,5),YRB(42,3),X(2),PTBL(42)
c
C
C
	INTEGER IS,IH,DAT(2),PTNUM/21/,DTS(2,43)
C
	REAL PTX(21),PTY(21),AB(21),AA(21),R(21)
	CHARACTER MAT(2)*4/'FLUX','ACID'/,DTIM*23,DATT(30)*11,DX1*6,DAX*2,
	1	DX11*9
C
	INTEGER WS_ID,NUM_POINTS,NV,I,J
	CHARACTER ASC(3)/'1','2','3'/,RY(5)*3/'0.0','1.0','2.0','3.0','4.0'/
	CHARACTER AO*6
	REAL PX(2),PY(8),Y(2),XAX(42),YPB3(21),YRB3(21),AP3(21),
	1	AR3(21),xcc(2),ycc(2)
C
	character ascn*5,ascr*5,SPCA*27
c
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
	REAL YAXB/10/
	REAL YAXE/27.5/
	REAL YAXRB/0.00/
	REAL YAXRE/3.0/
C
	REAL XVAL(43,3)
	REAL RVAL(43,3)
C
	INTEGER DTM(2,43)
C
	REAL XBAR /2.51/
	REAL UCL /3.61/
	REAL LCL /1.41/
	REAL STDV /.46/
C
	REAL RBAR /.41/
	REAL UCLR /1.35/
	REAL LCLR /0.00/
	REAL STDVR /0.0/
C
	INTEGER CSH
C
C
	CHARACTER FILES(3)*2/'BT','AT','CM'/
C
	REAL CP,CPK
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
	DATA PX /0.1,.95/
	DATA PY /.225,.225,.39375,.39375,.42,.42,.81375,.81375/
	DATA WS_ID/1/,NUM_POINTS/2/,NV/20/
C
	character string*255
C
C
	STRUCTURE /FOREMAN/
C
		CHARACTER DATE*6        ! KEY 0  DATE (YYMMDD)
		CHARACTER  NAME(3,2)*10	! names by shift
		REAL TONS(5,3)          ! pellet tons
		REAL TIME(5,3)          ! grate hours
		CHARACTER FA(5,3)	! F=FLUX, A=ACID
		REAL MBTU(5,3)          ! btus/ton
		REAL BENT(5,3)          ! bent. lbs/ton
C
		REAL BT(5,3)		! before tumble +1/4
		REAL AT(5,3)		! after tumble +1/4
		REAL COMP(5,3)          ! compression
		REAL PBA(5,3)           ! filter b/a
		REAL PSIL(5,3)		! non-existent
		REAL FCR(2,3)           ! filter cake ratio
C
	END STRUCTURE
C
	RECORD /FOREMAN/ FOR,ZFOR
C
C
C
C
C
	OPEN   (UNIT=50,FILE='USER_D:[METREP.ASHIFT]FORFILE.DAT',
	1	STATUS='UNKNOWN',ORGANIZATION='INDEXED',ACCESS='KEYED',
	1	FORM='UNFORMATTED',RECL=256,KEY=(1:6:CHARACter),SHARED)
C
cccccccccccccccccccccccc
c
	MBA=0
	KEY='960119'
398	READ (50,KEY=KEY) FOR
C
	FOR.MBTU(2,1)=0
	FOR.MBTU(4,1)=0
	REWRITE (50) FOR
	STOP
	END
