C
	PROGRAM	GCP_EU	!GOOD COMBUSTION PLAN EMISSION UNITS
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONFIDENTIAL
C	Property of United States Steel Corporation
C	Copyright 2007 United States Steel Corporation
C	All rights reserved.
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	REVISION HISTORY
C
C	SERVICE CENTER TICKET NUMBER:  PM735951
C	PLANVIEW ID NUMBER:            55352
C	PROGRAM AUTHOR:	BILL BABICH
C
	IMPLICIT NONE
C
	INTEGER*4	GRATE(5)/1229,362,569,349,356/
	INTEGER*4	FLAG(5),I,J,K,L,M,N,BIT
	INTEGER*4	CXSTS(100)
	INTEGER*4	CXSTS_AG3(100)
	INTEGER*4	UFO_OPEN,ADRS(2)
	INTEGER*4	TCS(5)/366,367,0368,685,686/
C
	REAL*4		ANVAL(1200)
	REAL*4		ANVAL_AG3(1000)
	REAL*4		VALU
C
	CHARACTER*8	TIM/'0 0:0:10'/	!10 SEC RUN TIME

C
	EXTERNAL	UFO_OPEN
C
	COMMON/ANVALTBL/ANVAL
	COMMON/AG3_ANVALTBL/ANVAL_AG3
C
	COMMON/CONTACTS/CXSTS
	COMMON/CONTACTSAG3/CXSTS_AG3
C
	CALL	SYS$BINTIM(TIM,ADRS)
	CALL	SYS$SCHDWK(,,ADRS,ADRS)	!SCHEDULE 10 SEC WAKEUP
C
100	CONTINUE
C
	OPEN	(UNIT=1,FILE='ANA:GCP_EU.DAT',STATUS='OLD',
	1	ACCESS='DIRECT',RECL=5,RECORDTYPE='FIXED',
	1	FORM='UNFORMATTED',SHARED,USEROPEN=UFO_OPEN)
C
	READ	(1,REC=1)FLAG	!READ IN INDICATIONS
C
	DO 555	I=1,5	!CHECK TO SEE IF LINE IS RUNNING NORMAL
C
		M=(GRATE(I)/32)+1		!WORD IN CX TABLE
		N=MOD(GRATE(I),32)		!BIT IN WORD
		IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
		IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
		IF (BIT .EQ. 0)THEN
			FLAG(I)=0	!GRATE IS OFF
			GOTO 555
		END IF
C
		IF (I .EQ. 1)VALU=ANVAL(TCS(I))
		IF (I .EQ. 2)VALU=ANVAL(TCS(I))
		IF (I .EQ. 3)VALU=ANVAL(TCS(I))
		IF (I .EQ. 4)VALU=ANVAL_AG3(TCS(I))
		IF (I .EQ. 5)VALU=ANVAL_AG3(TCS(I))
C
		IF (VALU .LE. 0)THEN
			FLAG(I)=0
			GOTO 555
		END IF
C
999	CONTINUE
C
		IF (FLAG(I) .LT. 540)FLAG(I)=FLAG(I)+1 !10 SECONDS OF RUN TIME
C
555	CONTINUE
C
	WRITE	(1,REC=1)FLAG	!WRITE OUT INDICATIONS
C
	CLOSE	(UNIT=1)
C
	CALL	SYS$HIBER()	!DELAY TILL WAKEUP
C
	GOTO 100
C
	END
C
