	EXTERNAL	UFO_OPEN
C
	INTEGER*4	DAYS_BEFORE,RECORD,TEMP_HRS
	REAL*4		HRS
	BYTE		HRS1(32)
C
C
	OPEN(4,FILE='AGGL_HRS:AGGL2_DAY_HRS.DAT',
	1    STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=8,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)

	RECORD=1
10	READ(4,REC=RECORD,ERR=9000)HRS1
C
	DO K=1,32
		IF(HRS1(K) .GT. 24 .AND. HRS1(K).NE. 127)THEN
		  TYPE*,RECORD,' ',HRS1(K),'K=',K  
		END IF
	END DO
	DO I=1,32
		IF(HRS1(I) .EQ.127)THEN
			TYPE*,'RECORD=',RECORD,' ',I, HRS1(I)
		END IF
	END DO
	RECORD=RECORD+1
	GOTO 10
9000 	CLOSE(1)
	END
