	PROGRAM KLNBRG3 
C
C	(KILN BEARINGS STEP 3 AGGLOMERATOR)
C
C	THIS PROGRAM WILL ALERT THE CONTROL ROOM  
C	TO ANY RAPID RISE IN TEMPERATURE FOR ANY ONE 
C	OF THE 66 BEARINGS LISTED BELOW.  IF A KILN BEARING 
C	TEMPERATURE SHOULD RISE AT LEAST 5 DEGREES IN
C	30 MINUTES OR LESS AN ALARM MSG IS PRINTED.
C
C	PLEASE NOTE!!!!! IF A FAN BEARING TEMPERATURE 
C       SHOULD RISE AT LEAST 10 DEGREES IN 30 MINUTES OR
C	LESS AN ALARM MSG IS PRINTED
C
C	FAN BEARING TEMPERATURES ARE CHECKED ONLY ABOVE 100
C	DEGREES.
C
C	PLEASE NOTE THAT THIS PROGRAM MONITORS BEARING
C	TEMPERATURES OTHER THAN KILN BEARINGS... (BALL MILL
C	AND PROCESS FANS).
C
C	REVISION HISTORY
C
C	THIS PROGRAM HAS BEEN REVISED ON 12-02-2004 TO PROVIDE
C	A SPECIFIC NOTIFICATION OF ALARM IS SENT TO THE STEP3
C	AGGLOMERATOR DCS WHEN AN INDIVIDUAL BEARING GOES INTO ALARM.
C	THIS IS DONE BY MEANS OF PACKED GROUP POINTS (GP RECORD TYPES)
C	AND SETTING THE CORRESPONDING BIT FOR EACH OF THE 66 BEARINGS.
C	A TOTAL OF 5 GP POINTS ARE USED (0-15) TO INDIVIDUALLY ALARM 
C	ALL 66 BEARINGS.  LOGIC IN THE DCS CONVERTS EACH ALARM BIT
C	TO A DL RECORD TYPE POINT TO ALARM THE OPERATOR. 
C
C	PLANVIEW ID
C	REVISION XX-XX-XXXX THE FOLLOWING MODIFICATIONS HAVE BEEN
C	MADE PER BILL SIMONSON:  A BASELINE OF 70 DEGREES FAHRENHEIT FOR ALL
C	MILL AND KILN BEARINGS. A RELATED CONTACT CHECK HAS BEEN ADDED FOR 
C	ALL BEARINGS.  IF THE RELATED CONTACT IS OPEN THE 30 MINUTE TABLE FOR
C	THE ASSOCIATED BEARING IS ZEROED OUT.  ONLY TEMPERATURES ABOVE THE 
C	BASELINE WHEN THE RELATED CONTACT IS CLOSED WILL BE USED TO CALCULATE
C	RAPID RISE ALARMS
C
C	FORT/NOOP/NOALIGN/WARN=NOALIGN/FLOAT=D_FLOAT KLNBRG3
C
C	LINK KLNBRG3,KLNBRG3/OPT,WESAPI_LIB:WESAPI/OPT
C
	IMPLICIT NONE
C
	INCLUDE 'WESAPI:SPD.DCL'
	INCLUDE 'WESAPI:SHC_defines.DCL'
	INCLUDE 'WESAPI:SHC_err.DCL'
C
	INTEGER*4	LIB$SYS_TRNLOG
	INTEGER*4 	status
	CHARACTER*20	highway
	CHARACTER*40    spd_filename
	CHARACTER*80	c_ascii_val
	INTEGER*2	spd_filename_len
	CHARACTER*2     field_name/'TB'/
	INTEGER*2	spd_fd
	INTEGER*2       c_short_val
	INTEGER*2	length
	INTEGER*2	access_type
	CHARACTER*8	pt_name
	BYTE		extended_flag
	BYTE		gp_bit_num
	BYTE		inactive_flag
	INTEGER*4	gp_sid,SID(2)
	INTEGER*2       gp_op_mask
	INTEGER*2       gp_val_mask(5)
C
	INTEGER*2	PUT_DIGITAL_VAL
C
	CHARACTER*8	PNT(2)/'DV800014','DV800015'/
	CHARACTER*8	GPNT(5)/'GP800001','GP800002','GP800003',
	1			'GP800004','GP800005'/
C
	REAL*4		TEMPS(30),VALUE,DIFF,ANVAL(1000)
	INTEGER*4	I,J,K,M,N,P,ADDRESS(2)
	INTEGER*4	NORM(4)/'33'O,'133'O,'62'O,'167'O/
	INTEGER*4	LARG(4)/'33'O,'133'O,'70'O,'167'O/
	INTEGER*4	UFO_OPEN,GSID(5)
	INTEGER*4	POINT_QUALITY
C
	INTEGER*4	BRGS(66)/58,229,59,228,60,231,
	1			 61,230,62,233,63,232,
	1			 64,235,57,234,49,221,
	1			 50,220,51,223,52,222,
	1			 53,225,54,224,55,227,
	1			 56,226,35,206,34,209,
	1			 37,208,36,207,42,215,
	1			 41,214,40,213,39,212,
	1			 73,246,72,245,71,244,
	1			 70,243,45,218,44,217,
	1			 76,248,75,247,29,30/
C
	INTEGER*4	RCXM(66)/399,421,399,421,399,421,399,421,
	1			 399,421,399,421,399,421,399,421,
	1			 399,421,399,421,399,421,399,421,
	1			 399,421,399,421,399,421,399,421,
	1			 371,373,371,373,371,373,371,373,
	1			 375,379,375,379,375,379,375,379,
	1			 377,380,377,380,377,380,377,380,
	1			 382,384,382,384,383,385,383,385,
	1			 341,341/
C
	INTEGER*4	RCXE(66)/412,434,412,434,412,434,412,434,
	1			 412,434,412,434,412,434,412,434,
	1			 412,434,412,434,412,434,412,434,
	1			 412,434,412,434,412,434,412,434,
	1			 0,0,0,0,0,0,0,0,
	1			 0,0,0,0,0,0,0,0,
	1			 0,0,0,0,0,0,0,0,
	1			 0,0,0,0,0,0,0,0,
	1			 0,0/
C
	CHARACTER*16	FILE/'GP:BRGTEMPS3.DAT'/
	CHARACTER*30	ED		!ENGLISH DESCRIPTION OF ANALOG
	CHARACTER*6	EU		!ENGINEERING UNITS
	CHARACTER*8	PN		!WDPF POINT NUMBER
	CHARACTER*23	DATETIME
	CHARACTER*8	TIME/'0 0:1:00'/
	CHARACTER*1	BELL,NORMX(4),LARGX(4)
	CHARACTER*1	TYP(66)/'K','K','K','K','K','K',
	1			'K','K','K','K','K','K',
	1			'K','K','K','K','K','K',
	1			'K','K','K','K','K','K',
	1			'K','K','K','K','K','K',
	1			'K','K','F','F','F','F',
	1			'F','F','F','F','F','F',
	1			'F','F','F','F','F','F',
	1			'F','F','F','F','F','F',
	1			'F','F','F','F','F','F',
	1			'F','F','F','F','M','M'/
C
	EXTERNAL	UFO_OPEN
C
	COMMON/AG3_ANVALTBL/ANVAL
	VOLATILE	ANVAL
C
	BELL=CHAR(007)
	DO 10 I=1,4
		NORMX(I)=CHAR(NORM(I))	!CONTROL SEQ FOR NORM PRINT
		LARGX(I)=CHAR(LARG(I))	!CONTROL SEQ FOR LARGE PRINT
10	CONTINUE
C
	OPEN	(UNIT=2,NAME=FILE,FORM='UNFORMATTED',SHARED,
	1	ACCESS='DIRECT',STATUS='OLD',RECL=30,
	1	RECORDTYPE='FIXED')
C
	DO 150 I=1,66			!FOR EACH BEARING
		K=BRGS(I)		!LOAD BEARING TEMP	
		DO 100 J=1,30		!AND INITIALIZE 30 MIN TABLE
			TEMPS(J)=ANVAL(K)
100		CONTINUE
		WRITE (2,REC=I)TEMPS	!SEND TABLE TO FILE
150	CONTINUE
C
 	CLOSE	(UNIT=2)	
C
C
C  Use the wesapi highway number to form the name of the wesapi logical that
C  names the highway 0 point directory file and get file name from the logical
        status = LIB$SYS_TRNLOG('WESAPI_PDIR_1',
     1			spd_filename_len,spd_filename,,,)

C  Put a NULL character (0) at the end of the file name string.  This is
C  necessary because the spd library functions expect string arguments
C  to be NULL terminated strings.
C
	spd_filename(spd_filename_len+1:) = CHAR(0)

C  Call the spd open file function to get access to the point directory file
C
        access_type = RUNTIME
        spd_fd = SPD_open_file(%ref(spd_filename), access_type)
C
	DO 102	J=1,2	!GET THE 2 CONTACT OUTPUT SIDS
C
C  Call the get sid function.  The point name argument must have a NULL (0)
C  at the end.
C
	        status = SPD_get_sid(spd_fd, %ref(PNT(J)//char(0)), SID(J),
     x		             gp_sid, gp_bit_num, extended_flag, inactive_flag)

C
102	CONTINUE
C
	DO 103	J=1,5	!GET THE 5 PACKED GROUP SIDS
C
C  Call the get sid function.  The point name argument must have a NULL (0)
C  at the end.
C
	        status = SPD_get_sid(spd_fd, %ref(GPNT(J)//char(0)), GSID(J),
     x		             gp_sid, gp_bit_num, extended_flag, inactive_flag)

C
103	CONTINUE
C  Close the point directory connection
C
	status = SPD_close_file(spd_fd)
C
C  Open the connection to SHC memory for WESAPI access
	status = SHC_open_memory()
	IF (status .NE. SHC_OK) THEN
		IF (status .EQ. SHC_E_MEMOPEN)GOTO 88
C
		OPEN	(UNIT=22,FILE='GP:KLNBRG3.ERR',STATUS='UNKNOWN',
	1		 ACCESS='APPEND')
C
		WRITE	(22,77)status
77		FORMAT	(' SHC open memory failure - error =',I4)
C
		CLOSE	(UNIT=22)
C
	   GO TO 99999
	ENDIF

88	CONTINUE
C
	status = SHC_put_point_quality( SID(1), point_quality)
	status = SHC_put_point_quality( SID(2), point_quality)
C
	field_name='ED'
	length=30
	c_ascii_val='LINE 6 BEARING TEMP RAPID RISE'
C
	STATUS=	SHC_CHANGE_ASCII_ATTRIBUTE(SID(1),%REF(FIELD_NAME),
	1		LENGTH,%REF(C_ASCII_VAL))
C
	c_ascii_val='LINE 7 BEARING TEMP RAPID RISE'
C
	STATUS=	SHC_CHANGE_ASCII_ATTRIBUTE(SID(2),%REF(FIELD_NAME),
	1		LENGTH,%REF(C_ASCII_VAL))
C
	CALL	SYS$BINTIM(TIME,ADDRESS)
	CALL	SYS$SCHDWK(,,ADDRESS,ADDRESS)
C
250	CONTINUE
C
	gp_val_mask(1)=0
	gp_val_mask(2)=0
	gp_val_mask(3)=0
	gp_val_mask(4)=0
	gp_val_mask(5)=0
C
	gp_op_mask=65535	 !AFFECT ALL BITS
C
	PUT_DIGITAL_VAL=0
	status = SHC_put_digital_val( SID(1), put_digital_val) 
	status = SHC_put_digital_val( SID(2), put_digital_val) 
C
	OPEN	(UNIT=2,NAME=FILE,FORM='UNFORMATTED',SHARED,
	1	ACCESS='DIRECT',STATUS='OLD',RECL=30,
	1	RECORDTYPE='FIXED',USEROPEN=UFO_OPEN)
C
	DO 350 I=1,66			!UPDATE EACH BEARING'S TABLE
		READ (2,REC=I)TEMPS	!BRING IN BRG RECORD
		K=BRGS(I) 		!BRG'S ANVAL NUMBER
		VALUE=ANVAL(K)		!LOAD TEMP FOR THIS BEARING
C
		IF (TYP(I) .NE. 'F')GOTO 222	!IF NOT FAN BRG SKIP
C
		IF (VALUE .LT. 100)GOTO 320	!SKIP CHECK BELOW 100
C
C	HAS THERE BEEN A 5 DEGREE RISE IN TEMP IN LAST 30 MINUTES?
C
222		CONTINUE
C
		DO 300 J=1,30
			DIFF=VALUE-TEMPS(J)
			IF (TYP(I) .NE. 'F')THEN
				IF (DIFF .GE. 5.0)GOTO 500!YES THERE HAS
				GOTO 300	!NO ALARM
			END IF
C
			IF (TYP(I) .EQ. 'F')THEN
				IF (DIFF .GE. 10.0)GOTO 500!YES THERE HAS
				GOTO 300	!NO ALARM
			END IF
C
300		CONTINUE
C
C		NO ALARM FOR THIS BEARING....SHUFFLE IN NEWEST
C		TEMP INTO TOP OF 30 MIN TABLE
C
320		CONTINUE
C
		DO 325 J=29,1,-1
			TEMPS(J+1)=TEMPS(J)
325		CONTINUE
		TEMPS(1)=VALUE		!NEW TEMP THIS MINUTE
C
345		WRITE (2,REC=I)TEMPS	!WRITE THIS BRG RECORD BACK
350	CONTINUE
C
	CLOSE	(UNIT=2)
C
	status = SHC_put_pkd_group_val(GSID(1),gp_op_mask, gp_val_mask(1))
	status = SHC_put_pkd_group_val(GSID(2),gp_op_mask, gp_val_mask(2))
	status = SHC_put_pkd_group_val(GSID(3),gp_op_mask, gp_val_mask(3))
	status = SHC_put_pkd_group_val(GSID(4),gp_op_mask, gp_val_mask(4))
	status = SHC_put_pkd_group_val(GSID(5),gp_op_mask, gp_val_mask(5))
C
C	DELAY FOR 1 MINUTE
C
400	CONTINUE
	CALL	SYS$HIBER()
	GOTO 250			!GO RUN AGAIN		
C
C	WE HAVE AN ALARM ... PRINT MSG AND LOAD TABLE
C
500	CONTINUE
	OPEN	(UNIT=3,FILE='ANA:AG3PHR.DAT',FORM='FORMATTED',
	1	ACCESS='DIRECT',STATUS='OLD',RECL=44,
	1	USEROPEN=UFO_OPEN,SHARED,
	1	CARRIAGECONTROL='LIST',RECORDTYPE='FIXED')
C
	OPEN	(UNIT=4,FILE='LTA071:',STATUS='UNKNOWN')
C
	CALL	LIB$DATE_TIME(DATETIME)	!GET CURRENT DATE AND TIME
C
	READ	(3,530,REC=K)PN,ED,EU	!GET ANAMOD DATA
530	FORMAT	(A,A,A)
	CLOSE	(UNIT=3)
C
	IF (ED(5:6) .EQ. '06')THEN	!LINE 6 ALARM
		PUT_DIGITAL_VAL=1
		status = SHC_put_point_quality( SID(1), point_quality)
		status = SHC_put_digital_val( SID(1), put_digital_val) 
	END IF
C
	IF (ED(5:6) .EQ. '07')THEN	!LINE 7 ALARM
		PUT_DIGITAL_VAL=1
		status = SHC_put_point_quality( SID(2), point_quality)
		status = SHC_put_digital_val( SID(2), put_digital_val) 
	END IF
C
	WRITE	(4,549,ERR=575)LARGX		!SET PRINT TYPE TO LARGE
549	FORMAT	(' ',A,A,A,A)
C
	WRITE	(4,550,ERR=575)BELL,BELL,BELL,PN,TEMPS(J),VALUE,DATETIME,ED
550	FORMAT	(' ',A,A,A,'A',1X,A,' RAPID TEMPERATURE RISE ',2F6.1,
	1	1X,A,1X,A)
C
	WRITE	(4,549,ERR=575)NORMX		!SET PRINT TYPE TO NORMAL
C
575	CONTINUE
C
	CLOSE	(UNIT=4)
C
	DO 600 M=1,30
		TEMPS(M)=VALUE		!INIT TABLE WITH NEW VALUE
600	CONTINUE
C
C	SET BIT IN GP POINT TO ALARM PER POINT
C
	N=((I-1)/16)+1	!CALCULATE WHICH PACKED GROUP POINT
	P=MOD(I-1,16)	!CALCULATE WHICH BIT TO SET
	gp_val_mask(N)=IBSET(gp_val_mask(N),P)	!SET THE BIT
C
	GOTO 345		!GO WRITE TABLE BACK...CONTINUE PROCESSING
C
99999	CONTINUE
C
	CALL	EXIT
C
	END
