C
	IMPLICIT NONE
	EXTERNAL UFO_OPEN
C
	INTEGER JJ,I,J,JX,M,TBT(2),IH,IT,L,MILL,IR,K,MM,MX
	CHARACTER SN(5)*1/'1','2','3','4','5'/,PN(3)*1/'1','2','3'/
C
	REAL A,B,ASAV,OHRS(2),OHRS2(2),SUM
	CHARACTER ENUM*12,KY*13,ENUM2*12,AM*2
C
	DOUBLE PRECISION U(120),V(120),W(120),X(91),Y(120),Z(120)
C
	INTEGER PTR(91),BD(2),RTIM(2),INTV(2),YSTRDAY(2),PTC2(120),PTC3(120),
	1	CNC2(120),CNC3(120)
C
	CHARACTER MON(12)*3/'JAN','FEB','MAR','APR','MAY','JUN','JUL',
	1			'AUG','SEP','OCT','NOV','DEC'/,ASC2*2
C
C
C	   structure for all indexed files
C
	STRUCTURE /SCREEN/
C				   KEY 0
C				1440511
	CHARACTER*13 SCREENDAT	!POSITION 1:7=EQUIP NO. & PANEL NO. 1440953  
C				!POSITION 8:13=OFF DATE
C
	INTEGER      		VENDOR	!CODE FOR VENDOR NAME
C
	CHARACTER*6  ONDATE		!DATE ON    mmddyy
C
	INTEGER      		DQ(2)	!date of daily HOURS 
	DOUBLE PRECISION	DT	!daily HOURS from WJB,these are
C					! added each day to DT
C
C
	END STRUCTURE
C
C
	RECORD /SCREEN/ REC,ZREC,REC2
C
C
CCCCCCCCCCCCCCCCCCCCCCCC
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCC
	CHARACTER ASTIM*14 /'-- 23:40:00.00'/, AINTV*1 /'1'/,
	1	FN(6)*21 /'USER_D:[METREP]AMBMCC','USER_D:[METREP]AMICRS',
	1	'USER_D:[METREP]BMICRS','USER_D:[METREP]AMICON',
	1	'USER_D:[METREP]BMICON','USER_D:[METREP]BMHFIL'/,  
	1	DAT*4/'.DAT'/,
	1       AD*23, FNM*34, AYSTR*23 ,FNDSTRNG*33,FNM2*34,FNM3*34,
	1	FNM4*34,FNM5*34,TDAY*23,RAT*23,FNM6*34
C
	INTEGER RST(2)
C
	DOUBLE PRECISION SCANT(8)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                      
	CALL SYS$BINTIM (ASTIM,RTIM) !convert 23:40 time to binary
C
	CALL SYS$BINTIM (AINTV,INTV) !convert 24 hr interval to binary
C
	CALL SYS$SCHDWK (,,RTIM,INTV) !sched. a wakeup at 23:40 every day
C
C	
C
C
2500	CALL SYS$GETTIM (BD)
	CALL SYS$ASCTIM (,AD,,)	!get current date-time in ascii
C
C
	AD='20-OCT-1991 23:02'
C
		IF (AD(1:1) .EQ. ' ') AD(1:1)='0'
C
		AYSTR=AD
C
	IF (AD(13:14) .EQ. '23') THEN
C
C
		FNM=FN(1)//AD(1:2)//DAT
		FNM2=FN(2)//AD(1:2)//DAT
		FNM3=FN(3)//AD(1:2)//DAT
		FNM4=FN(4)//AD(1:2)//DAT
		FNM5=FN(5)//AD(1:2)//DAT
		FNM6=FN(6)//AD(1:2)//DAT
C
	ELSE IF (AD(13:14) .GT. '06') THEN
C
		STOP
C
	ELSE IF (AD(13:14) .EQ. '06') THEN
C
		IF (ad(16:17).gt.'29') STOP
		GO TO 1166
C
	ELSE 
C
C
1166	CALL LIB$ADDX (BD,INTV,YSTRDAY,) 	!subtract 24 hrs from todays
C							date
C
C
	CALL SYS$ASCTIM (,AYSTR,YSTRDAY,)     	!cnvt ystrdays time to ascii
C
		IF (AYSTR(1:1) .EQ. ' ') AYSTR(1:1)='0'
C
		FNM=FN(1)//AYSTR(1:2)//DAT  
		FNM2=FN(2)//AYSTR(1:2)//DAT  
		FNM3=FN(3)//AYSTR(1:2)//DAT  
		FNM4=FN(4)//AYSTR(1:2)//DAT  
		FNM5=FN(5)//AYSTR(1:2)//DAT  
		FNM6=FN(6)//AYSTR(1:2)//DAT  
C
		BD(1)=YSTRDAY(1)
		BD(2)=YSTRDAY(2)
C                             
C
C
	END IF
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C	SECTION TO TRANSFER WJB'S 147 PUMP HOURS TO FINE SCREEN FILES
C
	OPEN (UNIT=10,FILE='USER_D:[CHARGE]SCREEN12.DAT',
	1	STATUS='UNKNOWN',ACCESS='KEYED',FORM='UNFORMATTED',
	1	ORGANIZATION='INDEXED',RECORDTYPE='FIXED',
	1	RECL=24,KEY=(1:13:CHARACTER),err=99)
C
	OPEN (77,FILE='PUMPS:PMP_CLOCK.DAT',ACCESS='DIRECT',STATUS='OLD',
	1 SHARED,USEROPEN=UFO_OPEN,FORM='FORMATTED',RECORDTYPE='FIXED',
	1 RECL=24)
C
	DO 500 I=1,274
C
		READ (77,808,REC=I,ERR=99) ENUM,OHRS
808	format (A,2F6.2)
C
		IF (ENUM(1:3) .NE. '147') GO TO 500
C
		DO 501 M=I,274,2
C
		READ (77,808,REC=M,ERR=99) ENUM,OHRS
		READ (77,808,REC=M+1,ERR=99) ENUM2,OHRS2
C
	IF (ENUM(5:6) .NE. ENUM2(5:6)) GO TO 99
	IF (.NOT.((ENUM(8:8) .EQ. '1') .AND. (ENUM2(8:8) .EQ. '2')))GO TO 99
C
		SUM=OHRS(2)+OHRS2(2)	!TOTAL 147 PUMP HOURS
C
		IF (SUM  .GT. 24.00) GO TO 501
C
C
C
C
			DO 89 J=1,5
			DO 89 K=1,3
C
C
				KY='144'//ENUM(5:6)//SN(J)//PN(K)//'999999'
				READ (10,KEY=KY,IOSTAT=MM) REC
C
				CALL SYS$ASCTIM (,AD,REC.DQ,)
				IF (AYSTR(1:11).EQ.AD(1:11)) GO TO 89
C
				REC.SCREENDAT=KY
				DO 66 MX=1,12
					IF (AYSTR(4:6).EQ.MON(MX))GOTO 118
66				CONTINUE
				STOP
118				WRITE(AM,'(I2)')MX
				IF (AM(1:1) .EQ. ' ')AM(1:1)='0'
				REC.ONDATE=AM//AYSTR(1:2)//AYSTR(10:11)
				REC.DT=REC.DT+SUM
C
				CALL SYS$BINTIM (AYSTR,REC.DQ)
C
C
				IF (MM .EQ. 0) THEN
					REWRITE (10) REC
				ELSE IF (MM .EQ. 36) THEN
					WRITE (10) REC
				ELSE
					GO TO 89
				END IF
C
C
89			CONTINUE
C
C
C
C		
501		CONTINUE
C
C
C
C
500	CONTINUE
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
99	CONTINUE
C
	STOP
	END
