C
	PROGRAM		MACT15M	!MINNTAC MACT 15 MINUTE SCANNER
C
C	MAXIMUM ACHIEVABLE CONTROL TECHNOLOGY
C
C	FORT/ALIGN=NONE/WARN=NOALIGN/FLOAT=D_FLOAT MACT15M
C
C	LINK MACT15M,MACT15M/OPT
C
C	THIS PROGRAM RUNS EVERY 15 MINUTES AND MONITORS
C	ALL DUST COLLECTORS COVERED UNDER MINNTAC'S MACT
C
C	EACH 15 MINUTE RUN THE PROGRAM WILL SHIP A RECORD TO THE 
C	PLANT ORACLE DATABASE FOR EACH DUST COLLECTOR COVERED UNDER
C	THE MACT WHICH WILL CONSIST OF THE FOLLOWING COLUMNS:
C
C	1.	EQUIPMENT NUMBER
C	2.	READING NUMBER
C	3.	READING TIMESTAMP
C	4.	PROCESS VALUE PRESSURE
C	5.	PROCESS VALUE FLOW
C	6.	READING INDICATION
C
C	REVISION HISTORY
C
C
C       PROCESS CHANGE: 1466                                    
C       REVISION DATE:  01-27-2021                             
C       MODIFIED BY:    BLA1122                       
C       DESCRIPTION OF CHANGES                                 
C       CHANGED COUNT VALUE FROM 540 TO 1

C	PROJECT REQUEST SYSTEM NUMBER: 2144
C	SERVICE CENTER TICKET NUMBER:  PM556362
C	PLANVIEW ID NUMBER:            39851
C	PROGRAM AUTHOR:	BILL BABICH
C
C	SERVICE CENTER TICKET NUMBER:  PM712609
C	PLANVIEW ID NUMBER:            53236
C	ADD TOTAL CONCENTRATE SETPOINT LOGIC TO ALL AGGLOMERATOR GRATE
C	AND COOLER DUST COLLECTORS (CHANGES MADE BY BILL BABICH)
C
	IMPLICIT NONE
C
	STRUCTURE /DUST_COLL/	!DUST COLLECTOR
C
		CHARACTER*12	EN	!EQUIPMENT NUMBER
		CHARACTER*2	TYPE	!DUST COLLECTOR TYPE
		CHARACTER*6	PLANT	!PLANT LOCATION
C
		INTEGER*4	ONSCAN	!SCAN FLAG
		INTEGER*4	MR(2)	!MOTOR RUN CX'S
		INTEGER*4	FLOW	!H2O FLOW TAG
		INTEGER*4	PRESS	!PRESS TAG
		INTEGER*4	TAGS(6)	!SERVICE TAGS
C
		REAL*8	FLL		!H2O FLOW LOW LIMIT
		REAL*8	FHL		!H2O FLOW HIGH LIMIT
		REAL*8	PLL		!PRESS LOW LIMIT
		REAL*8	PHL		!PRESS HIGH LIMIT
C
	END STRUCTURE
C
	RECORD/DUST_COLL/DC,TCS
C
	STRUCTURE /DUST_DATA/	!DUST COLLECTOR
C
		REAL*4		FLOW		!H2O FLOW READING
		REAL*4		PRES		!PRESSURE READING
		CHARACTER*23   	FPDATEX		!PROCESS READINGS DATE
		INTEGER*4	DC_FLAG		!DC RUN INDICATION
		INTEGER*4	EU_FLAG		!EU RUN INDICATION
		INTEGER*4	READNO		!DAILY READING NUMBER 0-96
C
	END STRUCTURE
C
	RECORD/DUST_DATA/DCX,DCZ,DC15
C
	INTEGER*4	ADRS(2),DAYFLG,MCX,TEMP
	INTEGER*4	UFO_OPEN,I,J,K,L,M,N,CX,TAG
	INTEGER*4	BIT,POINT,MR1,MR2,PNT,MIN,SEC,HRS
	INTEGER*4	CXSTS_CRS(100)
	INTEGER*4	CXSTS_CNC(100)
	INTEGER*4	CXSTS(100)
	INTEGER*4	CXSTS_AG3(100)
	INTEGER*4	FLAG(5),RND,RNDX,RNO
C
	REAL*4		ANVAL_CRS(1000)
	REAL*4		ANVAL_CNC(1900)
	REAL*4		ANVAL(1200)
	REAL*4		ANVAL_AG3(1000)
	REAL*4		VALU,SECF,RSECS
C
	CHARACTER*9	TIM/'0 0:15:00'/	!15 MIN RUN TIME
	CHARACTER*23	DATETIME
	CHARACTER*5	STRTM/'02:00'/	!START OF MONITOR TIME
	CHARACTER*5	DAYTM/'22:30'/	!END OF DAY TIME
	CHARACTER	TIME*5		!STORAGE FOR TIME OF DAY
	CHARACTER*21	DFILE/'ANA:DCDD-MMM-YYYY.DAT'/
C
	EXTERNAL	UFO_OPEN
C
	COMMON/CRS_ANVALTBL/ANVAL_CRS
	COMMON/CNC_ANVALTBL/ANVAL_CNC
	COMMON/ANVALTBL/ANVAL
	COMMON/AG3_ANVALTBL/ANVAL_AG3
C
	COMMON/CONTACTSCRS/CXSTS_CRS
	COMMON/CONTACTSCNC/CXSTS_CNC
	COMMON/CONTACTS/CXSTS
	COMMON/CONTACTSAG3/CXSTS_AG3
C
C
C	ESTABLISH READING NUMBER FOR THIS 15 MINUTE RUN EVERY TIME THE 
C	PROGRAM IS STARTED
C
	OPEN	(UNIT=2,FILE='ANA:MACT15M.DAT',STATUS='OLD',
	1	ACCESS='DIRECT',RECL=11,RECORDTYPE='FIXED',
	1	FORM='UNFORMATTED',SHARED,USEROPEN=UFO_OPEN)
C
	READ	(2,REC=1)DCX	!BRING IN DC DATA
C
	CLOSE	(UNIT=2)
C
	IF (DCX.READNO .EQ. 0)THEN !ESTABLISH READING NUMBER
		RNO=1
	ELSE
		RNO=RNO+1
	END IF
C
	CALL	LIB$DATE_TIME(DATETIME)	!GET CURRENT TIME
	READ	(DATETIME(16:17),'(I2)')MIN	!CONVERT MINUTES
	READ	(DATETIME(19:20),'(I2)')SEC	!CONVERT SECONDS
	I=MIN/15
	I=(I*15)-1
	IF (MIN .GE. 15)MIN=MIN-I-1
	IF (MIN .LT. 15)MIN=MIN+1
	SEC=60-SEC
	SEC=SEC+((15-MIN)*60)
	SECF=SEC	!FLOATING POINT SECONDS
	CALL	LIB$WAIT(SECF)	!WAIT TILL BEGINNING OF NEXT 15 MIN INTERVAL
C
	CALL	SYS$BINTIM(TIM,ADRS)
	CALL	SYS$SCHDWK(,,ADRS,ADRS)	!SCHEDULE 15 MINUTE WAKEUP
C
100	CONTINUE
C
	OPEN	(UNIT=1,FILE='ANA:WGS.DAT',STATUS='OLD',
	1	ACCESS='DIRECT',RECL=5,RECORDTYPE='FIXED',
	1	FORM='UNFORMATTED',SHARED,USEROPEN=UFO_OPEN)
C
	READ	(1,REC=1)FLAG	!READ IN INDICATIONS FOR WASTE GAS SCRUBBERS
C
	CLOSE	(UNIT=1)
C
	CALL	LIB$DATE_TIME(DATETIME)	!GET CURRENT TIME
	TIME=DATETIME(13:17)		!ISOLATE HOURS AND MINUTES
C
	READ	(DATETIME(13:14),'(I2)')HRS	!CONVERT HRS
	READ	(DATETIME(16:17),'(I2)')MIN	!CONVERT MINUTES
	TEMP=HRS+MIN          !NO MATTER WHAT, IF THIS IS FIRST RUN OF DAY
	IF (TEMP .EQ. 0)RNO=1 !READING NUMBER STARTS AT 1	
C
	OPEN	(UNIT=3,FILE='ANA:MACTPHR.DAT',FORM='UNFORMATTED',
	1	ACCESS='DIRECT',STATUS='OLD',RECL=24,SHARED,
	1	RECORDTYPE='FIXED',USEROPEN=UFO_OPEN)
C
	OPEN	(UNIT=2,FILE='ANA:MACT15M.DAT',STATUS='OLD',
	1	ACCESS='DIRECT',RECL=11,RECORDTYPE='FIXED',
	1	FORM='UNFORMATTED',SHARED,USEROPEN=UFO_OPEN)
C
	OPEN	(UNIT=1,FILE='ANA:MACTTCS.DAT',FORM='UNFORMATTED',
	1	ACCESS='DIRECT',STATUS='OLD',RECL=24,SHARED,
	1	RECORDTYPE='FIXED',USEROPEN=UFO_OPEN)
C
	DO 666	I=1,150 	!PROCESS ALL DUST COLLECTORS
C
		READ	(3,REC=I)DC	!BRING IN A DUST COLLECTOR
		READ	(1,REC=I)TCS	!BRING IN TOT CONCENTRATE SETPT REC
		IF (DC.ONSCAN .EQ. 0)GOTO 666	!IF OFF SCAN THEN SKIP
		READ	(2,REC=I)DCX	!BRING IN DC DATA
C
		DCX.DC_FLAG=0
		DCX.EU_FLAG=0
C
		DCX.FPDATEX='                       '
C
C	CHECK TO SEE IF DUST COLLECTOR OR WET SCRUBBER IS RUNNING
C
		MR1=0
		MR2=0
C
		POINT=DC.MR(1)		!FIRST MOTOR RUN CX
		M=(POINT/32)+1		!WORD IN CX TABLE
		N=MOD(POINT,32)		!BIT IN WORD
		IF (DC.PLANT(1:2) .EQ. 'CC')MR1=JIBITS(CXSTS_CRS(M),N,1)
		IF (DC.PLANT(1:2) .EQ. 'FC')MR1=JIBITS(CXSTS_CRS(M),N,1)
		IF (DC.PLANT(1:4) .EQ. 'CONC')MR1=JIBITS(CXSTS_CNC(M),N,1)
		IF (DC.PLANT(1:5) .EQ. 'AGGL2')MR1=JIBITS(CXSTS(M),N,1)
		IF (DC.PLANT(1:5) .EQ. 'AGGL3')MR1=JIBITS(CXSTS_AG3(M),N,1)
C
	IF (DC.MR(2) .NE. 0)THEN	!IF DC HAS 2ND MOTOR RUN CX CHECK IT
		POINT=DC.MR(2)		!SECOND MOTOR RUN CX
		M=(POINT/32)+1		!WORD IN CX TABLE
		N=MOD(POINT,32)		!BIT IN WORD
		IF (DC.PLANT(1:2) .EQ. 'CC')MR2=JIBITS(CXSTS_CRS(M),N,1)
		IF (DC.PLANT(1:2) .EQ. 'FC')MR2=JIBITS(CXSTS_CRS(M),N,1)
		IF (DC.PLANT(1:4) .EQ. 'CONC')MR2=JIBITS(CXSTS_CNC(M),N,1)
		IF (DC.PLANT(1:5) .EQ. 'AGGL2')MR2=JIBITS(CXSTS(M),N,1)
		IF (DC.PLANT(1:5) .EQ. 'AGGL3')MR2=JIBITS(CXSTS_AG3(M),N,1)
	END IF
C
		MCX=0
		IF (MR1 .EQ. 1)MCX=1
		IF (MR2 .EQ. 1)MCX=1
		DCX.DC_FLAG=MCX	!GET DC RUN INDICATION
C
222	CONTINUE
C
C		WE MUST CHECK TO SEE IF IT HAS
C		ANY EMISSION UNITS THAT ARE ON... IF IT HAS AN EMISSION
C		UNIT THAT IS ON WE INDICATE EU'S ARE ON... IF IT HAS
C		NO EMISSION UNITS THEN WE WILL STILL INDICATE EU'S ARE ON
C
		BIT=0
C
		IF (I .EQ. 129)THEN	!PROCESS 247-03-1 WGS
C			IF (FLAG(1) .GE. 540)THEN !HAS LINE RUN FOR 90 MIN
                        IF (FLAG(1) .GE. 1)THEN !HAS LINE RUN FOR 10 SEC 
                                BIT=1       !YES
			END IF
			DCX.EU_FLAG=BIT	!GET EU RUN INDICATION
			GOTO 556
		END IF
C
		IF (I .EQ. 100)THEN	!PROCESS 247-04-1 WGS
C			IF (FLAG(2) .GE. 540)THEN !HAS LINE RUN FOR 90 MIN
                        IF (FLAG(2) .GE. 1)THEN !HAS LINE RUN FOR 10 SEC
				BIT=1       !YES
			END IF
			DCX.EU_FLAG=BIT	!GET EU RUN INDICATION
			GOTO 556
		END IF
C
		IF (I .EQ. 108)THEN	!PROCESS 247-05-1 WGS
C			IF (FLAG(3) .GE. 540)THEN !HAS LINE RUN FOR 90 MIN
                        IF (FLAG(3) .GE. 1)THEN !HAS LINE RUN FOR 10 SEC
				BIT=1       !YES
			END IF
			DCX.EU_FLAG=BIT	!GET EU RUN INDICATION
			GOTO 556
		END IF
C
		IF (I .EQ. 119)THEN	!PROCESS 247-06-1 WGS
C			IF (FLAG(4) .GE. 540)THEN !HAS LINE RUN FOR 90 MIN
                        IF (FLAG(4) .GE. 1)THEN !HAS LINE RUN FOR 10 SEC
				BIT=1       !YES
			END IF
			DCX.EU_FLAG=BIT	!GET EU RUN INDICATION
			GOTO 556
		END IF
C
		IF (I .EQ. 125)THEN	!PROCESS 247-07-1 WGS
C			IF (FLAG(5) .GE. 540)THEN !HAS LINE RUN FOR 90 MIN
                        IF (FLAG(5) .GE. 1)THEN !HAS LINE RUN FOR 10 SEC
				BIT=1       !YES
			END IF
			DCX.EU_FLAG=BIT	!GET EU RUN INDICATION
			GOTO 556
		END IF
C
		TAG=0
		BIT=0
C
		DO 555	J=1,6	!CHECK ALL SIX SERVICE TAGS
			IF (DC.TAGS(J) .EQ. 0)GOTO 555
			TAG=1	!FOUND A SERVICE TAG ...CHECK IT
			PNT=DC.TAGS(J)
			M=(PNT/32)+1		!WORD IN CX TABLE
			N=MOD(PNT,32)		!BIT IN WORD
			IF (DC.PLANT(1:2) .EQ. 'CC')
	1			CX=JIBITS(CXSTS_CRS(M),N,1)
			IF (DC.PLANT(1:2) .EQ. 'FC')
	1			CX=JIBITS(CXSTS_CRS(M),N,1)
			IF (DC.PLANT(1:4) .EQ. 'CONC')
	1			CX=JIBITS(CXSTS_CNC(M),N,1)
			IF (DC.PLANT(1:5) .EQ. 'AGGL2')
	1			CX=JIBITS(CXSTS(M),N,1)
			IF (DC.PLANT(1:5) .EQ. 'AGGL3')
	1			CX=JIBITS(CXSTS_AG3(M),N,1)
C
			IF (CX .EQ. 1)THEN
				BIT=1	!SERVICE TAG IS RUNNING
			END IF
C
555		CONTINUE
C
		IF (TAG .EQ. 0)THEN !DC HAS NO EMISSION UNITS
			DCX.EU_FLAG=1	!SET EU'S RUNNING TO 1
			GOTO 556
		END IF
C
		IF (TAG .EQ. 1)THEN !DC HAS EMISSION UNITS
C
			IF (TCS.TAGS(1) .NE. 0)THEN	!DO WE HAVE TCS
C
				IF (BIT .EQ. 0)THEN	!IF COOLER/GRATE OFF
					DCX.EU_FLAG=0	!SET EU'S OFF TO 0
					GOTO 556
				END IF
C
				PNT=TCS.TAGS(1)	!WDPF DEC TAG NUMBER
				IF (TCS.PLANT(1:5) .EQ. 'AGGL2')
	1			VALU=ANVAL(PNT)
				IF (TCS.PLANT(1:5) .EQ. 'AGGL3')
	1			VALU=ANVAL_AG3(PNT)
				IF (VALU .GT. 0)THEN !IF TCS NON ZERO
					DCX.EU_FLAG=1	!SET EU'S RUNNING TO 1
				ELSE
					DCX.EU_FLAG=0	!SET EU'S OFF TO 0
				END IF
				GOTO 556
			END IF
C
			IF (BIT .EQ. 1)THEN	!THEY ARE ON
				DCX.EU_FLAG=1	!SET EU'S RUNNING TO 1
			ELSE
				DCX.EU_FLAG=0	!SET EU'S OFF TO 0
			END IF
			GOTO 556
C
		END IF
C
556	CONTINUE
C
		IF (DC.FLOW .NE. 0)THEN	!WE HAVE A FLOW METER OR PAMPS
			PNT=DC.FLOW
			IF (DC.PLANT(1:2) .EQ. 'CC')
	1		VALU=ANVAL_CRS(PNT)
			IF (DC.PLANT(1:2) .EQ. 'FC')
	1		VALU=ANVAL_CRS(PNT)
			IF (DC.PLANT(1:4) .EQ. 'CONC')
	1		VALU=ANVAL_CNC(PNT)
			IF (DC.PLANT(1:5) .EQ. 'AGGL2')
	1		VALU=ANVAL(PNT)
			IF (DC.PLANT(1:5) .EQ. 'AGGL3')
	1		VALU=ANVAL_AG3(PNT)
C
			DCX.FLOW=VALU		!RECORD FLOW
C
		END IF
C
		IF (DC.PRESS .NE. 0)THEN	!WE HAVE A PRES OR AMPS XMTR
			PNT=DC.PRESS
			IF (DC.PLANT(1:2) .EQ. 'CC')
	1			VALU=ANVAL_CRS(PNT)
			IF (DC.PLANT(1:2) .EQ. 'FC')
	1			VALU=ANVAL_CRS(PNT)
			IF (DC.PLANT(1:4) .EQ. 'CONC')
	1			VALU=ANVAL_CNC(PNT)
			IF (DC.PLANT(1:5) .EQ. 'AGGL2')
	1			VALU=ANVAL(PNT)
			IF (DC.PLANT(1:5) .EQ. 'AGGL3')
	1			VALU=ANVAL_AG3(PNT)
C
			DCX.PRES=VALU		!RECORD PRESS
C
		END IF
C
		DCX.FPDATEX=DATETIME	!RECORD TIME AND DATE
		DCX.READNO=RNO	!READING NUMBER
C
663	CONTINUE
C
	WRITE	(2,REC=I)DCX	!SAVE DC DATA
C
665	CONTINUE
C
666	CONTINUE
C
	CLOSE	(UNIT=2)	!CLOSE 15 MINUTE DATA FILE
	CLOSE	(UNIT=3)	!CLOSE PHRASE FILE
	CLOSE	(UNIT=1)	!CLOSE TCS FILE
C
C	WRITE	(6,777)DATETIME,RNO
777	FORMAT	(' ',A,2X,I3)
C
	RNO=RNO+1	!BUMP READING NUMBER
C
999	CONTINUE
C
	CALL	SYS$HIBER()	!DELAY TILL WAKEUP
C
	GOTO 100
C
	END
C
