C
	PROGRAM MAINGAS
C
C	THIS PROGRAM RUNS EVERY 30 SECONDS AND ACCUMULATES
C	SMCF OF GAS FOR LINES 3-7 AND MAIN TURBINES FOR
C	LOGGING EVERY HOUR ON THE HOUR
C
C	THIS PROGRAM WILL ALSO CALCULATE TONS PRODUCED
C	FROM BURNING THE VARIOUS FUELS AND STUFFS THEM
C	INTO THE ANVAL TABLE
C
C	THIS PROGRAM ALSO CALCULATES THE AMOUNT OF WOOD
C	CONSUMED PER LINE FROM THE WOOD AUGER SPEED (3-7)
C
C	THIS PROGRAM ALSO CALCULATES STANDARD GAS FOR LINES
C	6 AND 7 GAS METERS AND STUFFS THEM INTO THE ANVAL TABLE
C
C	THIS PROGRAM ALSO PERFORMS A MASS FLOW CALCULATION 
C       AND STUFFS IT INTO THE ANVAL TABLE
C
C	PROGRAM WAS REVISED ON 9-29-97 TO OUTPUT 24 GAS LOG AT 9:00 AM
C
C	LINK MAINGAS,MAINGAS/OPT,WESAPI_LIB:WESAPI/OPT
C
	IMPLICIT NONE
C
	INCLUDE	'($PRCDEF)'
C
	INTEGER*4	HCNTR,	!COUNTS 30 SEC RUNS PER HR
	1		DCNTR	!COUNTS HRS GONE THIS DAY
C
	INTEGER*4	HR,MIN,SEC,ADRS(2),I,J,K,L
	INTEGER*4	LIST(6)/1070,1051,1052,951,332,333/
	INTEGER*4	UFO_OPEN
C
	INTEGER*4	TONSX(3)/867,339,340/,
	1		GASX(3)/1070,1051,1052/,
	1		OILX(3)/853,537,538/,
	1		GTONS(3)/1074,1041,1042/,
	1		OTONS(3)/1073,1043,1044/,
	1		WOODX(5)/1071,1047,1048,911,912/,
	1		WTONS(5)/1072,1049,1050,913,914/,
	1		WSPD(5)/889,658,659,647,648/
C
	INTEGER*4	TONSQ(2)/564,565/,
	1		GASQ(2)/862,863/,
	1		OILQ(2)/522,547/,
	1		COALQ(2)/521,546/,
	1		GTONSQ(2)/864,865/,
	1		OTONSQ(2)/868,869/,
	1		CTONSQ(2)/866,867/
C
	INTEGER*4	BGAS(2)/617,618/,PHGAS(2)/525,549/,LGAS(2)/862,863/
	INTEGER*2	TEMP(2)/115,283/,PRESS(2)/116,284/
C
	INTEGER*4	GPT(50),M,N,GPTX(40)
C
	REAL*4		ANVAL(1200),ANVALX(1000),CRS_ANVAL(1000)
	REAL*4		ACTH(12),	!ACTIVE HOUR STORAGE
	1		LASTH(12),	!LAST HOUR STORAGE
	1		ACTD(12),	!ACTIVE DAY STORAGE
	1		LASTD(12)	!LAST DAY STORAGE
	REAL*4		AA(5)/-0.0146,0.0,0.0,0.0,0.0/
	REAL*4		BB(5)/3.326,2.18,2.794,2.794,2.794/
	REAL*4		CC(5)/2.876,2.882,-2.278,-2.278,-2.278/
	REAL*4		STKTMP,STKPRES,MSCFM,BARP,DENSITY
C
	REAL*4	TONS,GMBTUS,OMBTUS,TMBTUS,WMBTUS,CMBTUS
	REAL*4	HOLD,TX,PX
C
	CHARACTER*8	TIMEX,		!ASCII TIME
	1		TIM/'0 0:0:30'/	!30 SEC RUN TIME
	CHARACTER*14	FILE/'GP:MAINGAS.DAT'/
	CHARACTER*11	PRGNAM/'LOGS:TOTGAS'/	!LOG PROGRAM
	CHARACTER*6	PRCNAM/'TOTGAS'/
C
	EXTERNAL	UFO_OPEN
C
	COMMON/ANVALTBL/ANVAL
	COMMON/GOODPTTBL/GPT
	COMMON/AG3_ANVALTBL/ANVALX
	COMMON/CRS_ANVALTBL/CRS_ANVAL
	COMMON/AG3_GOODPTTBL/GPTX
C
5	CONTINUE
C
	CALL	TIME(TIMEX)
C
	DECODE	(2,100,TIMEX(1:2))HR
100	FORMAT	(I2)
	DECODE	(2,100,TIMEX(4:5))MIN
	DECODE	(2,100,TIMEX(7:8))SEC
C
	IF (HR .LT. 9)THEN
		DCNTR=24-(9-HR)	!DAY COUNTER IF BEFORE 12:00
	ELSE
		DCNTR=HR-9		!DAY COUNTER IF AFTER 12:00
	END IF
C
	HCNTR=(MIN*2)+(SEC/30)			!1 HR COUNTER
C
	CALL	SYS$BINTIM(TIM,ADRS)
	CALL	SYS$SCHDWK(,,ADRS,ADRS)	!SCHEDULE 30 SEC WAKEUP
C
300	CONTINUE
C
	OPEN	(UNIT=2,NAME=FILE,FORM='UNFORMATTED',SHARED,
	1	ACCESS='DIRECT',STATUS='OLD',RECL=48,
	1	RECORDTYPE='FIXED',USEROPEN=UFO_OPEN)
C
	READ	(2,REC=1)ACTH,LASTH,ACTD,LASTD	!READ IN FILE
C
	DO 400	I=1,6
		ACTH(I)=ACTH(I)+ANVAL(LIST(I))	!ACCUM HR GAS
		ACTD(I)=ACTD(I)+ANVAL(LIST(I))	!ACCUM DAY GAS
400	CONTINUE
C
	ACTH(7)=ACTH(7)+1	!BUMP OBSER FOR TURBINE TEMP
	ACTH(8)=ACTH(8)+1	!BUMP OBSER FOR TURBINE PRESS
	ACTD(7)=ACTD(7)+1
	ACTD(8)=ACTD(8)+1
C
	DO 450	I=1,2
		ACTH(I+8)=ACTH(I+8)+ANVALX(LGAS(I))	!ACCUM HR GAS LINE 6,7
		ACTD(I+8)=ACTD(I+8)+ANVALX(LGAS(I))	!ACCUM DAY GAS 6,7
450	CONTINUE
C
	HCNTR=HCNTR+1		!BUMP HR COUNTER
	IF (HCNTR .NE. 120)GOTO 800	!IF NOT END OF HOUR GO HERE
C
	DO 500 I=1,12
		LASTH(I)=ACTH(I)	!MOVE ACT HR TO LAST HR
		ACTH(I)=0		!ZERO ACTIVE HR
500	CONTINUE
C
	HCNTR=0		!RESET HR COUNTER
	DCNTR=DCNTR+1	!BUMP DAY COUNTER
	IF (DCNTR .NE. 24)GOTO 800	!IF NOT END OF DAY GO HERE
C
	DO 600	I=1,12
		LASTD(I)=ACTD(I)	!MOVE ACTIVE DAY TO LAST DAY
		ACTD(I)=0		!ZERO ACTIVE DAY
600	CONTINUE
C
	DCNTR=0		!RESET DAY COUNTER
C
800	CONTINUE
C
	WRITE	(2,REC=1)ACTH,LASTH,ACTD,LASTD	!WRITE FILE BACK
	CLOSE	(UNIT=2)
C
	IF (HCNTR .NE. 0)GOTO 1000	!NOT TIME FOR LOG
C
C	TURN ON PROGRAM TO LOG RESULTS
C
	CALL	SYS$CREPRC(,PRGNAM,,,,,,PRCNAM,%VAL(4),,,
	1		%VAL(PRC$M_DETACH))
C
1000	CONTINUE
C
	DO 1200	I=1,3   	!PROCESS LINES 3 4 AND 5
C
		IF (ANVAL(WSPD(I)) .LT. 0)THEN
			ANVAL(WOODX(I))=0
		ELSE
C			ANVAL(WOODX(I))=(((AA(I)*(ANVAL(WSPD(I))**2))+
C	1				(BB(I)*ANVAL(WSPD(I)))+
C	1				CC(I))/2)*1.05!NEW FACS 12-18-97 RAY P.
			ANVAL(WOODX(I))=ANVAL(WSPD(I))/2
		END IF
C
		IF (I .EQ. 1)THEN
			GPT(34)=JIBSET(GPT(34),15)
		ELSE
			GPT(33)=JIBSET(GPT(33),(I+21))
		END IF
C
		TONS=ANVAL(TONSX(I))		!LINE TONS
		GMBTUS=ANVAL(GASX(I))*1000	!GAS MBTUS
C
		M=(OILX(I)/32)+1
		N=MOD(OILX(I),32)
C
		IF (BJTEST(GPT(M),N))THEN	!IF OIL PULSE OK
			OMBTUS=ANVAL(OILX(I))*139	!OIL MBTUS
		ELSE
			OMBTUS=0			!NO  OIL MBTUS
		END IF
C
		WMBTUS=ANVAL(WOODX(I))*8.35  !WOOD MBTUS CHAD STEWART 11-4-03
		TMBTUS=GMBTUS+OMBTUS+WMBTUS		!TOTAL MBTUS
		IF (TMBTUS .EQ. 0)THEN
			ANVAL(GTONS(I))=0
			ANVAL(OTONS(I))=0
			ANVAL(WTONS(I))=0
		ELSE
			ANVAL(GTONS(I))=(TONS*GMBTUS)/TMBTUS
			ANVAL(OTONS(I))=(TONS*OMBTUS)/TMBTUS
			ANVAL(WTONS(I))=(TONS*WMBTUS)/TMBTUS
		END IF
C
		IF (I .EQ. 1)THEN
C
			M=(WTONS(I)/32)+1
			N=MOD(WTONS(I),32)
			GPT(M)=JIBSET(GPT(M),N)
			GPT(M)=JIBSET(GPT(M),N+1)
			GPT(M)=JIBSET(GPT(M),N+2)
		ELSE
C
			M=(GTONS(I)/32)+1
			N=MOD(GTONS(I),32)
			GPT(M)=JIBSET(GPT(M),N)
			GPT(M)=JIBSET(GPT(M),N+2)
			GPT(M)=JIBSET(GPT(M),N+8)
		END IF
C
1200	CONTINUE
C
	DO 1500	I=1,2   	!PROCESS LINES 6 AND 7
C
		IF (ANVALX(WSPD(I+3)) .LT. 0)THEN
			ANVALX(WOODX(I+3))=0
		ELSE
C			ANVALX(WOODX(I+3))=(((AA(I+3)*(ANVALX(WSPD(I+3))**2))+
C	1				(BB(I+3)*ANVALX(WSPD(I+3)))+
C	1				CC(I+3))/2)*1.05!NEW FACS 12-18-97 RDP
			ANVALX(WOODX(I+3))=ANVALX(WSPD(I+3))/2
		END IF
C
		M=(WOODX(I+3)/32)+1
		N=MOD(WOODX(I+3),32)
C
		GPTX(M)=JIBSET(GPTX(M),(N))
C
		TONS=ANVALX(TONSQ(I))		!LINE TONS
		GMBTUS=ANVALX(GASQ(I))*1000	!GAS MBTUS
C
		M=(OILQ(I)/32)+1
		N=MOD(OILQ(I),32)
C
		IF (BJTEST(GPTX(M),N))THEN	!IF OIL PULSE OK
			OMBTUS=ANVALX(OILQ(I))*139	!OIL MBTUS
		ELSE
			OMBTUS=0			!NO  OIL MBTUS
		END IF
C
C		CMBTUS=ANVALX(COALQ(I))*13.9		!COAL MBTUS
		CMBTUS=ANVALX(COALQ(I))*9.350		!NEW FAC 2-13-95
C
		WMBTUS=ANVALX(WOODX(I+3))*8.35 !WOOD MBTUS CHAD STEWART 11-4-03
C
		TMBTUS=GMBTUS+OMBTUS+CMBTUS+WMBTUS	!TOTAL MBTUS
C
		IF (TMBTUS .EQ. 0)THEN
			ANVALX(GTONSQ(I))=0
			ANVALX(OTONSQ(I))=0
			ANVALX(CTONSQ(I))=0
			ANVALX(WTONS(I+3))=0
		ELSE
			ANVALX(GTONSQ(I))=(TONS*GMBTUS)/TMBTUS
			ANVALX(OTONSQ(I))=(TONS*OMBTUS)/TMBTUS
			ANVALX(CTONSQ(I))=(TONS*CMBTUS)/TMBTUS
			ANVALX(WTONS(I+3))=(TONS*WMBTUS)/TMBTUS
		END IF
C
		M=(GTONSQ(I)/32)+1
		N=MOD(GTONSQ(I),32)
		GPTX(M)=JIBSET(GPTX(M),N) 	!SET GOODPT FOR GAS TONS
		GPTX(M)=JIBSET(GPTX(M),N+2) 	!SET GOODPT FOR COAL TONS
		GPTX(M)=JIBSET(GPTX(M),N+4)   	!SET GOODPT FOR OIL TONS
		M=(WTONS(I+3)/32)+1
		N=MOD(WTONS(I+3),32)
		GPTX(M)=JIBSET(GPTX(M),N) 	!SET GOODPT FOR WOOD TONS
C
1500	CONTINUE
C
	DO 1800	I=1,2	!CONVERT LINE GAS TO STANDARD FOR LINES 6 AND 7
C
		TX=520/(460+ANVALX(TEMP(I)))	!CALC TEMP FACTOR
		PX=(ANVALX(PRESS(I))+14.7)/(14.73*120)	!CALC PRESS FACTOR
C		HOLD=(ANVALX(BGAS(I)))*TX*PX	!CONVERT TO STANDARD GAS
C	PER RAY POTTS AND PAUL HERRING A NEW KILN GAS METER IS INSTALLED 
C	WHICH GIVES ME SMCF VIA A PULSE 11-13-1996
C
		HOLD=(ANVALX(BGAS(I)))		!NO NEED TO CONVERT LINE GAS
		HOLD=HOLD+(ANVALX(PHGAS(I)))	!ADD PREHEAT GAS
		ANVALX(LGAS(I))=HOLD		!STUFF INTO ANVAL
		M=(LGAS(I)/32)+1
		N=MOD(LGAS(I),32)
		GPTX(M)=JIBSET(GPTX(M),N) 	!SET GOODPT FOR LINE GAS 
C
1800	CONTINUE
C
	ANVAL(1075)=ANVALX(564)
	ANVAL(1076)=ANVALX(565)
	M=(1075/32)+1
	N=MOD(1075,32)
	GPT(M)=JIBSET(GPT(M),N) 	!SET GOODPT FOR LINE 6 PEL TONS
	GPT(M)=JIBSET(GPT(M),N+1) 	!SET GOODPT FOR LINE 7 PEL TONS
C
	BARP=CRS_ANVAL(491)	!GRAB BAROMETRIC PRESSURE
	STKTMP=ANVALX(637)+460	!GRAB STACK CAP TEMPAND ADD 460
	STKPRES=ANVALX(630)	!GRAB STACK CAP AIR FLOW PRESSURE
C
	DENSITY=.075*(530/STKTMP)*(BARP/29.98)		
	IF (STKTMP .LT. 0)STKTMP=0
	STKTMP=SQRT(STKTMP)
	IF (STKPRES .LT. 0)STKPRES=0
	STKPRES=SQRT(STKPRES)
	MSCFM=28926.94*STKTMP*STKPRES*DENSITY
	ANVALX(904)=MSCFM
	M=(904/32)+1
	N=MOD(904,32)
	GPTX(M)=JIBSET(GPTX(M),N) 	!SET GOODPT FOR LINE 6 MASS FLOW
C
	CALL	SYS$HIBER()	!DELAY TILL WAKEUP
	GOTO 300
C
	END
