C	********************************************************
C	PRINT_FILTER_STATUS
C
C	PRINT THE STATUS OF ALL THE CURRENT FILTERS
C		RUN FROM THE REPORTS MENU
C	9-JUN-1989
C
C	27-JAN-1995	ALPHA VERSION
C	*********************************************************
C
C	  RELATED FILES:
C		1- AGGL_HRS:AGGL_EQUIP_2.DAT       !EQUIPMENT OPERATING HRS
C		2- AGGL_HRS:FILTER1.DAT	   	!FILTER HISTORY FILE
C		3- AGGL_HRS:FILTER_VEND.DAT	   !VENDOR INFO FILE
C		4- AGGL_HRS:AGGL2_DAY_HRS.DAT   !30 DAY CIRCULAR FILE OF
C			EQUIPMENT HOURS BY DAY, USED TO BACK CALCULATE
C			WHEN A CHANGE WAS MADE.
C		5- AGGL_HRS:FILTER_REF.DAT     !FILE CONTAINING THE
C			EQUIPMENT NUMBERS AND REFERENCE NUMBERS INTO THE
C			OPERATING HOURS FILE
C	*********************************************************
C	LINK COMMAND LINK PRINT_FILTER_STATUS,USER3:[RJW.LIB]GENERAL/LIB
C	*********************************************************
C
	IMPLICIT	INTEGER(A-Z)
	EXTERNAL	UFO_OPEN
C
	STRUCTURE/BAG_CHANGE/
		BYTE		VENDOR1	   !VENDOR # OF INTERMEDIATE CHANGE
		BYTE		NO_BAGS    !NUMBER OF BAGS CHANGED
		INTEGER*2	HRS_SINCE  !HOURS SINCE FULL CHANGE
		INTEGER*4	DATE(2)    !BINARY DATE REF OF INTER. CHANGE
	END STRUCTURE
C              
	STRUCTURE/FILTER_FILE/
		BYTE		FLAG	   !0=CURRENT 1=HISTORY
		INTEGER*4	EQUIP_REF  !EQUIPMENT REF NUMBER
		INTEGER*4	DATE(2)	   !BINARY DATE REF. TOTAL CHANGE OUT
		REAL		START_HRS  !EQUIP HRS AT INSTALLATION
		REAL		LIFE_HRS   !BAG LIFE HRS 
		REAL		EXPEC_HRS  !EXPECTED LIFE
		BYTE		VENDOR	   !VENDOR NUMBER TOTAL CHANGE
		INTEGER*2	DUM1	   !
	RECORD/BAG_CHANGE/BAGS(25)	
	END STRUCTURE
	RECORD/FILTER_FILE/FILTER,TEMP
C
C
	STRUCTURE/DIGFILE/
		INTEGER		POINT_REF  !POINT REFERENCE NO.
		INTEGER		COUNT	   !ACCUMULATED TIME COUNTS
		INTEGER		COUNT_1    !RESET COUNTER
		INTEGER		COUNT_2    !COUNT DOWN COUNTER
		INTEGER		COUNT_3
		CHARACTER*11	POINT_NO   !POINT NUMBER
		CHARACTER*32	DESCR      !ENGLISH DESCRIPTION
	END STRUCTURE
	RECORD/DIGFILE/POINT
C
C
	STRUCTURE/FILT_REF/
		CHARACTER*8	EQUIP_NO
		INTEGER*4	POINT_REF
		CHARACTER*16	TYPE
		INTEGER*4	DUM
	END STRUCTURE
	RECORD/FILT_REF/REF
C
	CHARACTER*16	VENDOR_NAME(24),VENDOR_NAME1              
	CHARACTER*4	SCREEN_80_1/'[?3l'/
	CHARACTER*4     SCREEN_132_1/'[?3h'/
	CHARACTER*5	SCREEN_80,SCREEN_132
	CHARACTER*3     CLEAR/'[2J'/ 	!CLEAR THE SCREEN
	CHARACTER*2	HOME/'[H'/  	!HOME THE CURSOR
	CHARACTER*1	ANS,ESC/27/
	CHARACTER*4	AUTO_PRINT_ON1/'[?5i'/
	CHARACTER*5	AUTO_PRINT_ON
	CHARACTER*4	AUTO_PRINT_OFF1/'[?4i'/
	CHARACTER*5	AUTO_PRINT_OFF
	CHARACTER*1	BELL/7/,FF/12/
	CHARACTER*11	DATE
	CHARACTER*10	EQUIP_NO
	CHARACTER*23	CURRENT_TIME,DATE1
	CHARACTER*132	DASH/'------------------------------------
	1---------------------------------------------------------
	1-------------------------------------'/
C	*** STORAGE ARRAYS FOR PRINTING REPORTS ****
	CHARACTER*11	PDATE(40)
	REAL*4 		CURRENT(40)
	REAL*4		SINCE(40)
	REAL*4		EXPECTED(40)
	REAL*4		TOTAL_LIFE(40)
	INTEGER*4	EVENTS(40)		!NUMBER OF CHANGE OUTS
	INTEGER*4	BAGS_TOT(40)
	INTEGER*4	VENDOR(40)
	INTEGER*4	POINT_REF(40)
	INTEGER*4	TOT_BAGS
C
	INTEGER*4	RECORD,BAGS,REF_SAVE
	INTEGER		REC_NUM
	INTEGER		FLAG,FLAG_1,NEW
	BYTE		HRS(32)		!DAILY RUNNING TIME
	INTEGER		BIN(2)
	INTEGER		STATUS,DATE_REF,DATE_REF1
	BYTE		VEND
C
	REAL		AVG,HOURS,HRS_CURRENT,LEFT
	REAL		START,EXPEC,HOURS_SINCE,OFFSET
	REAL		TOTAL_HRS
C
	CHARACTER*24	DESCR_REF(40)
	CHARACTER*1	REF_TEMP,LF/10/
C
	SCREEN_80=CHAR(27)//SCREEN_80_1
	SCREEN_132=CHAR(27)//SCREEN_132_1
	AUTO_PRINT_ON=ESC//AUTO_PRINT_ON1
	AUTO_PRINT_OFF=ESC//AUTO_PRINT_OFF1
	WIDTH=132
	REF_TEMP=DESCR_REF(1)(6:6)
C	*** OPEN TERMINAL AS UNIT 5 TO ALLOW RUNNING FROM A COMMAND PROC
	OPEN(UNIT=5,FILE='SYS$COMMAND',STATUS='UNKNOWN')
	CALL TERM_SET(WIDTH)		!SET TERM BUFFER TO 132 CHARS
C
	OPEN(1,FILE='AGGL_HRS:AGGL_EQUIP_2.DAT',
	1    STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=16,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C
	OPEN(2,FILE='AGGL_HRS:FILTER1.DAT',STATUS='UNKNOWN',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=82,
	1    USEROPEN=UFO_OPEN,SHARED,
	1    FORM='UNFORMATTED')
C
	OPEN(3,FILE='AGGL_HRS:VENDOR.DAT',STATUS='UNKNOWN',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='SEQUENTIAL',
	1    RECORDTYPE='FIXED',
	1    RECL=4,
	1    USEROPEN=UFO_OPEN,SHARED,
	1    FORM='UNFORMATTED')
C
C
	OPEN(5,FILE='AGGL_HRS:FILTER_REF.DAT',STATUS='OLD',
	1	FORM='UNFORMATTED',
	1	ACCESS='KEYED',
	1	SHARED)
C
	I=1
10001	ACCESS=0
10005	READ(5,IOSTAT=IOS,ERR=10900,END=10002)REF
	POINT_REF(I)=REF.POINT_REF
	DESCR_REF(I)(1:8)=REF.EQUIP_NO
	DESCR_REF(I)(9:9)=' '
	DESCR_REF(I)(10:)=REF.TYPE
	I=I+1
	GOTO 10001
C
C	*** ERROR READING EQUIPMENT NUMBER ***************    
10900	IF(IOS .EQ. 52)THEN  !ERROR RECORD LOCKED
		CALL LIB$WAIT(1.)
		ACCESS=ACCESS+1
		IF(ACCESS .GT. 10)THEN
			GOTO 9000
		END IF 
		GOTO 10005
	ELSE
		GOTO 9000
	END IF
10002	CLOSE(5)
C	**** READ IN THE VENDOR NAMES ******
	DO I=1,24
	  READ(3,ERR=3)VENDOR_NAME(I) 
	END DO
3	CLOSE(3)
C
	WRITE(5,10)ESC//CLEAR,ESC//HOME
10	FORMAT(' ',A4,A3)
C	*** GET CURRENT HOURS FOR ALL FILTERS *****
2000	CONTINUE
2002	RECORD=3
2004	READ(1,REC=RECORD,ERR=2006)POINT
 		DO I=1,40
			IF(POINT.POINT_REF .EQ. POINT_REF(I))THEN
			  CURRENT(I)=FLOAT(POINT.COUNT)/12.
			  RECORD=RECORD+1
			  GOTO 2004
			END IF
		END DO
	RECORD=RECORD+1
	GOTO 2004	
C	**** READ FILTER FILE TO ACCUMULATE HISTORY AND GET CURRENT ***
2006	RECORD=1
2008	READ(2,REC=RECORD,ERR=2020)FILTER
	IF(FILTER.FLAG .EQ. 0) THEN	!CURRENT FILTER
	  DO I=1,40
		IF(FILTER.EQUIP_REF .EQ. POINT_REF(I))THEN
		  S=SYS$ASCTIM(,DATE1,FILTER.DATE,)
		  PDATE(I)=DATE1(1:11)
		  SINCE(I)=CURRENT(I)-FILTER.START_HRS
		  EXPECTED(I)=FILTER.EXPEC_HRS
		  VENDOR(I)=FILTER.VENDOR
		  DO J=1,25         !ACCUMULATE INTERMEDIATE BAG CHANGES
			BAGS_TOT(I)=BAGS_TOT(I)+FILTER.BAGS(J).NO_BAGS
		  END DO
		  RECORD=RECORD+1
		  GOTO 2008
		END IF
	  END DO
	  RECORD=RECORD+1
	  GOTO 2008
	ELSE
	  DO I=1,40
		IF(FILTER.EQUIP_REF .EQ. POINT_REF(I))THEN
		  EVENTS(I)=EVENTS(I)+1
		  TOTAL_LIFE(I)=TOTAL_LIFE(I)+FILTER.LIFE_HRS
		  RECORD=RECORD+1
		  GOTO 2008
		END IF
	  END DO
	END IF
C	**** PRINT THE RESULTS ****************	  
C	***** GET CURRENT TIME *******************
2020	STATUS=SYS$ASCTIM(,CURRENT_TIME,,)
	WRITE(5,10)ESC//CLEAR,ESC//HOME
	WRITE(5,2022)SCREEN_132
2022	FORMAT(' ',A5)
	WRITE(5,2023)AUTO_PRINT_ON
2023	FORMAT(' ',A5)
	WRITE(5,2025)FF
2025	FORMAT(' ',A1)
	WRITE(5,2024)CURRENT_TIME(1:17)
2024	FORMAT(' ',A17)
	WRITE(5,2026)
2026	FORMAT('0','EQUIPMENT NUMBER',T27,'NUMBER OF',T38,'AVG',
	1       T44,'EXPECT',T52,'HRS SINCE',T62,'LIFE',T69,
	1       'BAGS',T81,'DATE')                         
	WRITE(5,2028)
2028	FORMAT(' ',T28,'CHANGES',T37,'LIFE',T45,'LIFE',T53,'CHANGE',
	1      T62,'LEFT',T68,'CHANGED',T78,'INSTALLED',T93,'VENDOR')
	WRITE(5,2030)DASH
2030	FORMAT(' ',A132)
C
	DO I=1,40
	  IF(POINT_REF(I) .EQ. 0) GOTO 2800  !DONE
	  IF(EVENTS(I) .GT. 0) THEN
	  	AVG=TOTAL_LIFE(I)/EVENTS(I)                
	  ELSE
		AVG=0.
	  END IF
	  LEFT=EXPECTED(I)-SINCE(I)
	  IF(VENDOR(I) .LT. 1 .OR. VENDOR(I) .GT. 24)VENDOR(I)=24
	IF(DESCR_REF(I)(6:6) .NE. REF_TEMP)THEN
		WRITE(5,2041)LF
2041	FORMAT(' ',A1)
	END IF
	  WRITE(5,2040,ERR=2043)DESCR_REF(I),
	1		EVENTS(I),
	1		AVG,
	1		EXPECTED(I),
	1		SINCE(I),
	1		LEFT,
	1		BAGS_TOT(I),
	1		PDATE(I),
	1		VENDOR_NAME(VENDOR(I))
C
2043	REF_TEMP=DESCR_REF(I)(6:6)
	END DO                         
C
2040	FORMAT(' ',A24,T28,I4,T37,F5.0,T44,F5.0,T53,F5.0,
	1	T61,F5.0,T70,I3,T77,A11,T90,A16)
C	************************
2800	WRITE(5,2023)AUTO_PRINT_OFF
	WIDTH=80              
	CALL TERM_SET(WIDTH)
	WRITE(5,211)SCREEN_80
211	FORMAT(' ',A5)

9000	END
C	******* SUBROUTINE  TERM_SET   TO CHANGE IO BUFFER TO 132
C	         CHARACTERS FOR DISPLAY *******************************
C
	SUBROUTINE TERM_SET(WIDTH)
C
	IMPLICIT INTEGER(A-Z)
	INCLUDE	'($IODEF)'
	CHARACTER*11	TERMINAL/'SYS$COMMAND'/
	INTEGER*2	TERM_CHAN
	BYTE	WIDTH
	BYTE	IN_BUF(8)
C
	STATUS=SYS$ASSIGN(TERMINAL,TERM_CHAN,,)
	IF(.NOT. STATUS)CALL LIB$SIGNAL(%VAL(STATUS))
C
	STATUS=SYS$QIOW(%VAL(1),%VAL(TERM_CHAN),
	1               %VAL(IO$_SENSEMODE),,,,
	1               %REF(IN_BUF),,,,,)
	IN_BUF(3)=WIDTH
	STATUS=SYS$QIOW(%VAL(1),%VAL(TERM_CHAN),
	1              %VAL(IO$_SETMODE),,,,
	1              %REF(IN_BUF),,,,,)
C
	RETURN
	END
