C
	PROGRAM		PSMUX
C
C	PROGRAM PUTS EACH NEW PSM SAMPLE FROM LINES 4 THRU 18
C	INTO A FILE FOR LATER AUDITING.  THE PROGRAM RUNS EVERY 
C	10 SECONDS
C
C	LINK PSMUX,PSMUX/OPT
C
C
C	REVISION 04-08-2005 CHANGES MADE TO READ PSM SELECTOR SWITCH FOR LINES
C	7 AND 8 AND USE THE VFLAG PARAMETER TO INDICATE WHICH PSM READ THE
C	SAMPLE.  A FACTOR OF 10 IS ADDED TO VFLAG FOR LINES 7 AND 8 IF
C	THESE LINES WERE PUMPED TO THE STEP 1 PSM
C
	IMPLICIT NONE
C
	REAL*4		ANVAL(1900),VAR
	REAL*4		OLDTIM(16),SOLX,SIZX,HI(3),LO(3)
C
	INTEGER*4	SIZE(16)/957,959,961,963,964,966,
	1			 968,970,972,974,976,
	1			 978,980,982,984,986/
	INTEGER*4	SOLS(16)/1326,958,960,962,965,967,
	1			 969,971,973,975,977,
	1			 979,981,983,985,987/
	INTEGER*4	TIMEX(16)/1327,1173,1174,1175,1176,1177,
	1			  1178,1179,1180,1181,1182,
	1			  1183,1184,1185,1186,1187/
	INTEGER*4	SFLAG,MM,DD,YY,ADDRESS(2),TM,VFLAG(3),VCNTR(3)
	INTEGER*4	I,J,K,L,M,N
	INTEGER*4	CXSTS(100),BIT,BIT7,BIT8
	INTEGER*4	PSM(3)/236,360,384/
	INTEGER*4	VALV1(4)/768,772,776,780/
	INTEGER*4	VALV2(6)/784,788,792,796,800,804/
	INTEGER*4	VALV3(6)/808,812,816,820,824,828/
	INTEGER*4	VAXTM,HRX,MNX,DIFF
	INTEGER*4	UFO_OPEN
	INTEGER*4	SEL7/1905/,SEL8/1906/
C
	CHARACTER*23	DT
	CHARACTER*8	TIME/'0 0:0:10'/	!PROGRAM RUN FREQUENCY
	CHARACTER*12	FILEX
	CHARACTER*12	FILES(3)/'ANA:PSM1.DAT',
	1			 'ANA:PSM2.DAT',
	1			 'ANA:PSM3.DAT'/
C
	COMMON/CNC_ANVALTBL/ANVAL	!ANVAL TABLE
	COMMON/CONTACTSCNC/CXSTS	!CONTACT STATUS TABLE
C
	EXTERNAL	UFO_OPEN
C
	SFLAG=0		!INDICATE NEW START
	VFLAG(1)=0	!INDICATE NO VARIABILITY
	VFLAG(2)=0	
	VFLAG(3)=0	
	VCNTR(1)=-1	!INDICATE NOT TO CHECK FOR VARIABILITY YET
	VCNTR(2)=-1
	VCNTR(3)=-1
C
	DO 100	I=1,16
C
		OLDTIM(I)=ANVAL(TIMEX(I))	!LOAD UP SAMPLE TIMES
C
100	CONTINUE
C
	CALL	SYS$BINTIM(TIME,ADDRESS)	!CONVERT ASCII TIME TO BINARY
	CALL	SYS$SCHDWK(,,ADDRESS,ADDRESS)	!PUT PROG ON 10 SEC SCHED
C
200	CONTINUE
C
	IF (SFLAG .EQ. 0)GOTO 5000	!GO WAIT ON FIRST PASS
C
	J=(SEL7/32)+1	!EXTRACT CXSTS LONGWORD LINE 7 SEL SW
	K=MOD(SEL7,32)	!EXTRACT CORRECT BIT
	BIT7=JIBITS(CXSTS(J),K,1)	!EXTRACT BIT COND
C
	J=(SEL8/32)+1	!EXTRACT CXSTS LONGWORD LINE 8 SEL SW
	K=MOD(SEL8,32)	!EXTRACT CORRECT BIT
	BIT8=JIBITS(CXSTS(J),K,1)	!EXTRACT BIT COND
C
	CALL	LIB$DATE_TIME(DT)
C
	CALL	OTS$CVT_TI_L(DT(1:2),DD,,%VAL(1))	!DAY
	CALL	OTS$CVT_TI_L(DT(8:11),YY,,%VAL(1))	!YY
	CALL	OTS$CVT_TI_L(DT(13:14),HRX,,%VAL(1))	!HOUR
	CALL	OTS$CVT_TI_L(DT(16:17),MNX,,%VAL(1))	!MINUTES
C
	VAXTM=(HRX*100)+MNX	!CALCULATE VAX MILITARY TIME
C
	IF (DT(4:6) .EQ. 'JAN')MM=1
	IF (DT(4:6) .EQ. 'FEB')MM=2
	IF (DT(4:6) .EQ. 'MAR')MM=3
	IF (DT(4:6) .EQ. 'APR')MM=4
	IF (DT(4:6) .EQ. 'MAY')MM=5
	IF (DT(4:6) .EQ. 'JUN')MM=6
	IF (DT(4:6) .EQ. 'JUL')MM=7
	IF (DT(4:6) .EQ. 'AUG')MM=8
	IF (DT(4:6) .EQ. 'SEP')MM=9
	IF (DT(4:6) .EQ. 'OCT')MM=10
	IF (DT(4:6) .EQ. 'NOV')MM=11
	IF (DT(4:6) .EQ. 'DEC')MM=12
C
	DO 1000	I=1,16	!PROCESS 16 LINES
		IF (OLDTIM(I) .EQ. ANVAL(TIMEX(I)))THEN
			GOTO 1000	!NO NEW SAMPLE
		ELSE
			TM=ANVAL(TIMEX(I))	!NEW SAMPLE TIME
			OLDTIM(I)=ANVAL(TIMEX(I))	!CHANGE TIME TABLE
			SIZX=ANVAL(SIZE(I))	!PSM SIZE
			SOLX=ANVAL(SOLS(I))	!PSM SOLIDS
			J=2			!ASSUME STEP 2 PSM
			IF (I .LE. 4)J=1	!MUST BE STEP 1 PSM
			IF (I .GE. 11)J=3	!MUST BE STEP 3 PSM
			FILEX=FILES(J)		!SET UP FILE NAME
C
			OPEN	(UNIT=1,FILE=FILEX,ACCESS='APPEND',
	1			RECORDTYPE='FIXED',RECL=8,SHARED,
	1			FORM='UNFORMATTED',STATUS='OLD',
	1			USEROPEN=UFO_OPEN)
C
				M=I+2	!INDICATE LINE NUMBER
C
				DIFF=TM-VAXTM	!IF TIMES ARE TOO FAR APART
				IF (ABS(DIFF) .GT. 100)TM=VAXTM !USE VAX TIME
C
				IF (M .EQ. 7)THEN	!CHECL SEL SW
					IF (BIT7 .EQ. 0)VFLAG(1)=
	1					VFLAG(1)+10 !IND STEP1 PSM
				WRITE	(1)M,SIZX,SOLX,TM,MM,DD,YY,VFLAG(1)
C
				CLOSE	(UNIT=1)
C
				VCNTR(1)=0	!INDICATE OK TO START VAR CHECK
				HI(1)=0	!CLEAR HI READING
				LO(1)=0	!CLEAR LOW READING
				GOTO 777
C
				END IF
C
				IF (M .EQ. 8)THEN	!CHECL SEL SW
					IF (BIT8 .EQ. 0)VFLAG(1)=
	1					VFLAG(1)+10 !IND STEP1 PSM
				WRITE	(1)M,SIZX,SOLX,TM,MM,DD,YY,VFLAG(1)
C
				CLOSE	(UNIT=1)
C
				VCNTR(1)=0	!INDICATE OK TO START VAR CHECK
				HI(1)=0	!CLEAR HI READING
				LO(1)=0	!CLEAR LOW READING
				GOTO 777
C
				END IF
C
				WRITE	(1)M,SIZX,SOLX,TM,MM,DD,YY,VFLAG(J)
C
				CLOSE	(UNIT=1)
C
				VCNTR(J)=0	!INDICATE OK TO START VAR CHECK
				HI(J)=0	!CLEAR HI READING
				LO(J)=0	!CLEAR LOW READING
C
777				CONTINUE
C
			END IF
C
1000	CONTINUE
C
C	HERE WE WILL PUT THE SECTION FOR CHECKING IF EACH PSM IS RUNNING
C	AND IF SO THEN DO THE VAR CHECK
C
	DO 3000	I=1,3	!PROCESS EACH PSM
C
		IF (VCNTR(I) .EQ. -1)GOTO 3000	!NOT IN SEQ YET FOR THIS PSM
C
		IF (I .EQ. 1)THEN	!FIND OUT IF ANY LINE PUMPING TO PSM
C
		DO 1200	N=1,4		!CHECK FOR 3 LINES IN STEP 1
C
			J=(VALV1(N)/32)+1	!EXTRACT CXSTS LONGWORD
			K=MOD(VALV1(N),32)	!EXTRACT CORRECT BIT
			BIT=JIBITS(CXSTS(J),K,1)	!EXTRACT BIT COND
			IF (BIT .EQ. 1) GOTO 2000	!REL CX CLOSED
C
1200			CONTINUE
C
			GOTO 3000	!IF NO LINES SKIP THIS PSM
C
		END IF
C
		IF (I .EQ. 2)THEN	!FIND OUT IF ANY LINE PUMPING TO PSM
C
		DO 1400	N=1,6		!CHECK FOR 6 LINES IN STEP 2
C
			J=(VALV2(N)/32)+1	!EXTRACT CXSTS LONGWORD
			K=MOD(VALV2(N),32)	!EXTRACT CORRECT BIT
			BIT=JIBITS(CXSTS(J),K,1)	!EXTRACT BIT COND
			IF (BIT .EQ. 1) GOTO 2000	!REL CX CLOSED
C
1400			CONTINUE
C
			GOTO 3000	!IF NO LINES SKIP THIS PSM
C
		END IF
C
		IF (I .EQ. 3)THEN	!FIND OUT IF ANY LINE PUMPING TO PSM
C
		DO 1600	N=1,6		!CHECK FOR 6 LINES IN STEP 3
C
			J=(VALV3(N)/32)+1	!EXTRACT CXSTS LONGWORD
			K=MOD(VALV3(N),32)	!EXTRACT CORRECT BIT
			BIT=JIBITS(CXSTS(J),K,1)	!EXTRACT BIT COND
			IF (BIT .EQ. 1) GOTO 2000	!REL CX CLOSED
C
1600			CONTINUE
C
			GOTO 3000	!IF NO LINES SKIP THIS PSM
C
		END IF
C
2000		IF (VCNTR(I) .LT. 12)THEN	!IF IN 2 MIN FLUSH SKIP
			VCNTR(I)=VCNTR(I)+1
			GOTO 3000
		END IF
C
		IF (VCNTR(I) .EQ. 12)THEN	!IF START OF 3 MIN SAMPLE
			VCNTR(I)=VCNTR(I)+1
			HI(I)=ANVAL(PSM(I))	!INITIALIZE HI GRIND
			LO(I)=ANVAL(PSM(I))	!INITIALIZE LO GRIND
			GOTO 3000
		END IF
C
		IF (VCNTR(I) .GT. 12)THEN	!CHECK FOR VARIABILITY
			IF (ANVAL(PSM(I)) .GT. HI(I))HI(I)=ANVAL(PSM(I))
			IF (ANVAL(PSM(I)) .LT. LO(I))LO(I)=ANVAL(PSM(I))
			VFLAG(I)=0	!ASSUME NO VARIABILITY
			VAR=HI(I)-LO(I)
			IF (VAR .GE. 1.0)VFLAG(I)=1	!SET VARIABILITY FLAG
			VCNTR(I)=VCNTR(I)+1
		END IF
C
3000	CONTINUE
C
5000	CONTINUE
C
	CALL	SYS$HIBER() 	!DELAY TILL NEXT TURN ON
	SFLAG=1			!INDICATE FIRST RUN COMPLETE
	GOTO 200
C
	END
