C       **********************************************************
C	READ_PHONE
C
C	PROGRAM TO READ THE PHONE DATA SENT FROM THE "DIMENSION" 
C	PHONE COMPUTER
C
C	CONNECTS TO LAT PORT LTA101: CREATED  BY THE LATCP PROGRAM
C
C	NOTE: RECORDS NEAR MIDNIGHT MAY BE IN THE NEXT DAY'S OR THE
C	PREVIOUS DAYS'S FILE BECAUSE THE TWO CLOCKS MAY NOT BE IN SYNC
C	**************************************************************
C       LINK READ_PHONE,USER3:[RJW.LIB]GENERAL
C	***************************************************************
C	17-jan-1995	Alpha version
C	11-AUG-199	NEW VERSION FOR NEW PHONE SWITCH
C
C	*************************************************************
	IMPLICIT	INTEGER (A-Z)
	EXTERNAL	UFO_OPEN
C
	INCLUDE	'($IODEF)'
	INCLUDE '($SSDEF)'
	INCLUDE	'($PRCDEF)'
C
	CHARACTER*80	INPUT
	CHARACTER*48	OUT
C
	CHARACTER*7	DEVICE/'LTA101:'/
	CHARACTER*23	FILE_NAME/'PH:27-OCT-1988PH.DAT'/
	CHARACTER*23	CURRENT,CURRENT_SAVE
	CHARACTER*11	NOW
	CHARACTER*1	TRANS/'0'/,MATCH/' '/
	INTEGER*2	CHAN,IOSB(4),FUNC
C
	S=SYS$ASCTIM(,CURRENT,,)
	CURRENT_SAVE=CURRENT
C
	NOW=CURRENT(1:11)
	CALL STR$TRANSLATE(NOW,NOW,TRANS,MATCH)
	FILE_NAME(4:14)=NOW
C	*** OPEN THE FILE; IF IT ALREADY EXISTS USE OLD FILE ***
	OPEN(1,FILE=FILE_NAME,ERR=50,STATUS='UNKNOWN',
	1	FORM='UNFORMATTED',
	1	RECORDTYPE='FIXED',
	1	RECL=16,
	1	ACCESS='SEQUENTIAL')
	GOTO 51
50	OPEN(1,FILE=FILE_NAME,STATUS='NEW',
	1	FORM='UNFORMATTED',
	1	RECORDTYPE='FIXED',
	1	RECL=16,
	1	ACCESS='SEQUENTIAL')
C	*** MUST CLOSE AND REOPEN THE FILE TO USE UFO_OPEN ***
51	CLOSE(1)
	OPEN(1,FILE=FILE_NAME,STATUS='OLD',
	1	FORM='UNFORMATTED',
	1	RECORDTYPE='FIXED',
	1	RECL=16,
	1	USEROPEN=UFO_OPEN,SHARED,
	1	ACCESS='APPEND')
C	*** ESTABLISH A CHANNEL TO THE LAT PORT ***
	STATUS=SYS$ASSIGN(DEVICE,CHAN,,)
C	IF(.NOT. STATUS)CALL LIB$SIGNAL(%VAL(STATUS))
C
	COUNT=0
C	*** CONNECT TO THE LAT PORT *****
	STATUS=SYS$QIOW(,%VAL(CHAN),
	1	%VAL(IO$_TTY_PORT.OR.IO$M_LT_CONNECT),
	1	IOSB,,,
	1	,,,,,)
C
10	STATUS=SYS$QIOW(,%VAL(CHAN),
	1	%VAL(IO$_READVBLK),
	1	IOSB,,,
	1	%REF(INPUT),%VAL(80),,,,)
C
C	IF(.NOT. STATUS)CALL LIB$SIGNAL(%VAL(STATUS))
C
C	*** CHECK FOR NEW DAY STARTING OR OTHER SHORT RECORD ****
	IF(IOSB(2) .LT. 10) GOTO 10  !DATE SENT SO SKIP THIS RECORD
	S=SYS$ASCTIM(,CURRENT,,)
C
	IF(CURRENT(1:11).NE. CURRENT_SAVE(1:11))THEN   !NEW DAY ?
C		IF(CURRENT(4:7) .NE.CURRENT_SAVE(4:7))THEN  !NEW MONTH
C		STATUS=SYS$CREPRC(,'PH:PHONE_REPORT.EXE',  !SO GENERATE
C	1	,,'PH:REPORT.ERR',,,'PH_REPORT',%VAL(4),,,  !MONTH REPORT
C	1	%VAL(PRC$M_DETACH))   
C		END IF
		CLOSE(1)  !CLOSE THE OLD FILE
		CURRENT_SAVE=CURRENT
		NOW=CURRENT(1:11)
		CALL STR$TRANSLATE(NOW,NOW,TRANS,MATCH)
		FILE_NAME(4:14)=NOW(1:11)
C
		OPEN(1,FILE=FILE_NAME,STATUS='NEW',
	1		FORM='UNFORMATTED',
	1		RECORDTYPE='FIXED',
	1		RECL=16,
	1		ACCESS='SEQUENTIAL')
		CLOSE(1)
55		OPEN(1,FILE=FILE_NAME,STATUS='OLD',
	1		FORM='UNFORMATTED',
	1		RECORDTYPE='FIXED',
	1		RECL=16,
	1		USEROPEN=UFO_OPEN,SHARED,
	1		ACCESS='APPEND')
	END IF
C	*** SAVE THE RECORD *****
	WRITE(1)INPUT(1:51)
	COUNT=COUNT+1
C	*** CLOSE THE FILE AFTER 20 RECORDS TO UPDATE THE FILE ***
	IF(COUNT .EQ. 20)THEN
		CLOSE(1,ERR=60)
		OPEN(1,FILE=FILE_NAME,STATUS='OLD',
	1		FORM='UNFORMATTED',
	1		RECORDTYPE='FIXED',
	1		RECL=16,
	1		USEROPEN=UFO_OPEN,SHARED,
	1		ACCESS='APPEND')
60		COUNT=0
	END IF
C
	GOTO 10
	END
