CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONFIDENTIAL
C	Property of United States Steel Corporation
C	Copyright 2014 United States Steel Corporation
C	All rights reserved.
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	PROGRAM	REDLITE
C
C	THIS PROGRAM CALCULATES THE FOLLOWING OPERATING TIMES 
C	FOR THE CRUSHER AND STUFFS THEM INTO THE CRUSHER ANVAL 
C	TABLE FOR ACCUMULATION BY THE CRUSHER ANALOG SCANNER
C	PROGRAM (CRSSCN).
C
C	1. HANGUP, REDLITE IDLE TIME
C
C	2. PLANT DELAY, REDLITE IDLE TIME
C
C	3. 600T DELAY, REDLITE IDLE TIME
C
C	4. 070 BIN DELAY,REDLITE IDLE TIME
C
C	5. FC CONTROL ROOM DELAY, REDLITE IDLE TIME
C
C	6. CC ATTDNT DELAY,REDLITE IDLE TIME
C
C	7. NUMBER OF TRUCKS DUMPED
C
C	LINK REDLITE,REDLITE/OPT
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	Revision History:
C	20140129: PC491 Edit the motor contact for primary crusher pan feeder
C		motor contact from 2173 to 2392
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
	IMPLICIT NONE
C
	INTEGER*4	SBUT(4)/2274,2275,2272,2273/,
	1		RLIT(4)/2176,2390,2171,2391/,
	1		HBUT(4)/26,35,14,17/,
	1		IDSW(4)/28,37,16,19/,
	1		T600(4)/25,34,8,11/,
	1		B070(4)/24,33,7,7/,
	1		FCSW(4)/22,31,9,12/,
	1		CCSW(4)/298,315,254,258/,
	1		EMCX(4)/277,317,177,220/,
c	1		PMCX(4)/2173,2344,2322,2323/,
	1		PMCX(4)/2392,2344,2322,2323/,
	1		PMCY(4)/2343,2345,0,0/,
	1		AMBR(4)/0,2385,0,2379/,
	1		TRKCX(4)/2395,2384,0,2381/
	INTEGER*4	GPT(40),ADRS(2),BIT,BITX
	INTEGER*4	I,J,K,L,M,N,LTRK(4),SBUTX(4),TFLG(4)
	INTEGER*4	CXSTS(100),PNT(7)
	INTEGER*4	HU(4)/950,951,952,976/,
	1		PDEL(4)/953,954,955,977/,
	1		X600(4)/956,957,958,978/,
	1		X070(4)/959,960,961,979/,
	1		FC(4)/962,963,964,980/,
	1		CC(4)/965,966,967,981/,
	1		TRK(4)/1000,998,0,999/
C
	REAL*4		ANVAL(1000)
C
	CHARACTER*8	TIM/'0 0:0:10'/	!10 SEC RUN TIME
C
	COMMON/CRS_ANVALTBL/ANVAL
	COMMON/CRS_GOODPTTBL/GPT
	COMMON/CONTACTSCRS/CXSTS	!CONTACT STATUS TABLE
C
	CALL	SYS$BINTIM(TIM,ADRS)
	CALL	SYS$SCHDWK(,,ADRS,ADRS)	!SCHEDULE 30 SEC WAKEUP
C
100	CONTINUE
C
	DO 3000	I=1,4	!PROCESS 4 PRIMARY CRUSHERS
C
		CALL	CHKCX(SBUT(I),BIT)	!CHECK SCHED BUTTON
		SBUTX(I)=BIT	!SAVE SCHEDULE BUTTON
C
		IF (BIT .EQ. 0)THEN	!IF CRUSHER NOT SCHEDULED
C
200			CONTINUE
C
			ANVAL(HU(I))=0		!NO HANGUP TIME
			ANVAL(PDEL(I))=0	!NO PLANT DELAY
			ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
			ANVAL(X070(I))=0	!NO 070 BIN DELAY
			ANVAL(FC(I))=0		!NO FINES CRUSHER DELAY
			ANVAL(CC(I))=0		!NO COARSE CRUSHER DELAY
C
			GOTO 2500	!GO SET GOODPT FOR THESE POINTS
C
		END IF
C
		CALL	CHKCX(RLIT(I),BIT)	!CHECK RED LITE
C
		IF (BIT .EQ. 1)GOTO 200	!LITE IS GREEN GET OUT
C
		CALL	CHKCX(IDSW(I),BIT)	!CHECK IDLE SWITCH
C
		IF (BIT .EQ. 1)GOTO 200	!CRUSHER NOT IDLING GET OUT
C
		CALL	CHKCX(EMCX(I),BIT)	!SEE IF CRUSHER IS ON
C
		IF (BIT .EQ. 0)GOTO 200	!CRUSHER NOT RUNNING GET OUT
C
		CALL	CHKCX(HBUT(I),BIT)	!CHECK FOR HANGUP
C
		IF (BIT .EQ. 1)THEN	!WE HAVE A HANGUP
C
			ANVAL(HU(I))=0.002777	!10 SEC OF TIME
			ANVAL(PDEL(I))=0	!NO PLANT DELAY
			ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
			ANVAL(X070(I))=0	!NO 070 BIN DELAY
			ANVAL(FC(I))=0		!NO FINES CRUSHER DELAY
			ANVAL(CC(I))=0		!NO COARSE CRUSHER DELAY
			GOTO 2500
		ELSE
			ANVAL(HU(I))=0
		END IF
C
		CALL	CHKCX(B070(I),BIT)	!CHECK FOR HI 070 BIN
C
		IF (BIT .EQ. 1)THEN	!WE HAVE HI 070 BIN
C
			ANVAL(X070(I))=0.002777	!10 SEC OF TIME
			ANVAL(PDEL(I))=0	!NO PLANT DELAY
			ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
			ANVAL(HU(I))=0		!NO HANGUP DELAY
			ANVAL(FC(I))=0		!NO FINES CRUSHER DELAY
			ANVAL(CC(I))=0		!NO COARSE CRUSHER DELAY
			GOTO 2500
		ELSE
			ANVAL(X070(I))=0
		END IF
C
		CALL	CHKCX(PMCX(I),BIT)	!SEE IF PAN IS RUNNING
C
		IF (BIT .EQ. 1)GOTO 300	!IF PAN IS ON NO PLANT DELAY
C
		IF (I .GE. 3)GOTO 290	!IF CRUSH 3&4 ONLY ONE PAN
C
		CALL	CHKCX(PMCY(I),BIT)	!SEE IF SEC PAN IS RUNNING
C
		IF (BIT .EQ. 1)GOTO 300	!IF PAN IS ON NO PLANT DELAY
C
290		CONTINUE
C
		ANVAL(PDEL(I))=0.002777	!PANS ARE OFF WE HAVE PLANT DELAY
		ANVAL(HU(I))=0		!NO HANGUP DELAY
		ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
		ANVAL(X070(I))=0	!NO 070 BIN DELAY
		ANVAL(FC(I))=0		!NO FINES CRUSHER DELAY
		ANVAL(CC(I))=0		!NO COARSE CRUSHER DELAY
		GOTO 2500
C
300		CONTINUE
C
		ANVAL(PDEL(I))=0	!NO PLANT DELAY
C
		CALL	CHKCX(T600(I),BIT)	!SEE IF HIGH 600 TON BIN
C
		IF (BIT .EQ. 1)THEN	!HIGH 600 TON BIN
C
			ANVAL(X600(I))=0.002777	!10 SEC OF TIME
			ANVAL(PDEL(I))=0	!NO PLANT DELAY
			ANVAL(HU(I))=0		!NO HANGUP DELAY
			ANVAL(X070(I))=0	!NO 070 BIN DELAY
			ANVAL(FC(I))=0		!NO FINES CRUSHER DELAY
			ANVAL(CC(I))=0		!NO COARSE CRUSHER DELAY
			GOTO 2500               !WE HAVE 600 TON BIN DELAY
		ELSE
			ANVAL(X600(I))=0
		END IF
C
		CALL	CHKCX(CCSW(I),BIT)	!SEE IF ATTEN HAS PUT NO DUMP
C
		IF (BIT .EQ. 0)THEN	!ATTEN HAS SWITCHED TO RED LITE
C
			ANVAL(CC(I))=0.002777	!10 SEC OF TIME
			ANVAL(PDEL(I))=0	!NO PLANT DELAY
			ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
			ANVAL(X070(I))=0	!NO 070 BIN DELAY
			ANVAL(FC(I))=0		!NO FINES CRUSHER DELAY
			ANVAL(HU(I))=0		!NO HANGUP DELAY
			GOTO 2500               !WE HAVE CC ATTEN DELAY
		ELSE
			ANVAL(CC(I))=0
		END IF
C
		IF (AMBR(I) .EQ. 0)GOTO 2400
C
		CALL	CHKCX(AMBR(I),BIT)	!SEE IF AMBER LIGHT IS ON
C
		IF (BIT .EQ. 1)THEN	!ATTEN HAS SWITCHED TO AMBER LITE
C
			ANVAL(CC(I))=0.002777	!10 SEC OF TIME
			ANVAL(PDEL(I))=0	!NO PLANT DELAY
			ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
			ANVAL(X070(I))=0	!NO 070 BIN DELAY
			ANVAL(FC(I))=0		!NO FINES CRUSHER DELAY
			ANVAL(HU(I))=0		!NO HANGUP DELAY
			GOTO 2500               !WE HAVE CC ATTEN DELAY
		ELSE
			ANVAL(CC(I))=0
		END IF
C
2400		CONTINUE
C
		CALL	CHKCX(FCSW(I),BIT)	!SEE IF FC HAS PUT NO DUMP
C
		IF (BIT .EQ. 1)THEN	!FC HAS SWITCHED TO RED LITE
C
			ANVAL(FC(I))=0.002777	!10 SEC OF TIME
			ANVAL(PDEL(I))=0	!NO PLANT DELAY
			ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
			ANVAL(X070(I))=0	!NO 070 BIN DELAY
			ANVAL(HU(I))=0		!NO HANGUP DELAY
			ANVAL(CC(I))=0		!NO COARSE CRUSHER DELAY
			GOTO 2500               !WE HAVE FC ATTEN DELAY
		ELSE
			ANVAL(FC(I))=0
		END IF
C
		ANVAL(FC(I))=0		!NO FC DELAY
		ANVAL(PDEL(I))=0	!NO PLANT DELAY
		ANVAL(X600(I))=0	!NO 600 TON BIN DELAY
		ANVAL(X070(I))=0	!NO 070 BIN DELAY
		ANVAL(HU(I))=0		!NO HANGUP DELAY
		ANVAL(CC(I))=0		!NO COARSE CRUSHER DELAY
C
2500		CONTINUE
C
		IF (TRKCX(I) .EQ. 0)GOTO 2575	!COUNT TRUCKS ON #1 #2 & #4
C
		CALL	CHKCX(TRKCX(I),BIT)	!SEE IF TRUCK AT CRUSHER
C
		IF (SBUTX(I) .EQ. 0)THEN	!IF SCHED BUTTON OFF SKIP
			ANVAL(TRK(I))=0	!ZERO OUT TRUCK
			TFLG(I)=0	!ZERO TRUCK TIMER
			GOTO 2550
		END IF
C
		IF (BIT .EQ. 1)THEN     !IF NO EQUIPMENT AT CRUSHER
			ANVAL(TRK(I))=0	!ZERO OUT TRUCK
			TFLG(I)=0	!ZERO TRUCK TIMER
			GOTO 2550
		END IF
C
		TFLG(I)=TFLG(I)+1	!BUMP TRUCK TIMER
C
		IF (TFLG(I) .EQ. 4)THEN	!IF BEAM BROKE FOR AT LEAST 40 SECS
			ANVAL(TRK(I))=1	!COUNT A TRUCK
		ELSE
			ANVAL(TRK(I))=0	!ZERO OUT TRUCK
		END IF
C
2550		CONTINUE
C
		LTRK(I)=BIT	!SAVE LAST INDICATION
C
2575		CONTINUE
C
		PNT(1)=HU(I)	!LOAD POINT TABLE
		PNT(2)=PDEL(I)
		PNT(3)=X600(I)
		PNT(4)=X070(I)
		PNT(5)=FC(I)
		PNT(6)=CC(I)
		PNT(7)=TRK(I)
C
		DO 2600	J=1,7
C
			IF (PNT(J) .EQ. 0)GOTO 2600
C
			M=(PNT(J)/32)+1
			N=MOD(PNT(J),32)        !SET GOODPOINT FOR ALL SIX
			GPT(M)=JIBSET(GPT(M),N)	!POINTS FOR THIS CRUSHER
C
2600		CONTINUE
C
3000	CONTINUE
C
	CALL	SYS$HIBER()	!DELAY TILL WAKEUP
	GOTO 100
C
	END
C
	SUBROUTINE	CHKCX(POINT,BIT)
C
C	SUBROUTINE WILL RETURN THE STATUS OF A CONTACT (0 OR 1)
C
	INTEGER*4	BIT,POINT,I,J,CXSTS(100)
C
	COMMON/CONTACTSCRS/CXSTS
C
	I=(POINT/32)+1		!WORD IN TABLE
	J=MOD(POINT,32)		!BIT IN WORD
	BIT=JIBITS(CXSTS(I),J,1)!EXTRACT BIT
	RETURN
	END
