C
	PROGRAM	RFCAKE
C
	REAL*4		VALUS(2),NUM
C
	INTEGER*4	LEN,UFO_OPEN
C
	EXTERNAL	UFO_OPEN
C
	OPEN	(UNIT=6,FILE='SYS$COMMAND',STATUS='UNKNOWN')
C
	OPEN	(UNIT=1,FILE='ANA:FCAKE.DAT',STATUS='OLD',
	1	RECL=2,RECORDTYPE='FIXED',FORM='UNFORMATTED',
	1	ACCESS='DIRECT',SHARED,USEROPEN=UFO_OPEN)
C
	READ	(1,REC=1)VALUS	!BRING IN FILTER CAKE SIO2S
C
	WRITE	(6,100)VALUS(1)
100	FORMAT	(' ','STEP 2 FILTER CAKE SILICA',F5.2)
C
	WRITE	(6,700)VALUS(2)
700	FORMAT	(' ','STEP 3 FILTER CAKE SILICA',F5.2)
C
	CLOSE	(UNIT=1)
	CLOSE	(UNIT=6)
C
	CALL	EXIT
C
	END
