C
	PROGRAM		SAVMRF	!SAVE MORNING REPORT FILE
C
	IMPLICIT NONE
C
	INTEGER*4	I
	INTEGER*4	UFO_OPEN
C
	STRUCTURE	/RECX/
C
		CHARACTER*3	ORIG	!ORIGINATOR INITIALS
		CHARACTER*32	ED	!ENGLISH DESCRIPTION
		CHARACTER*6	UNITS	!UNIT OF MEASURE
		CHARACTER*11	DATEX	!DATE IN FORM DD-MMM-YYYY
		CHARACTER*1	SHIFT	!SHIFT IF NECESSARY
		REAL*8		VALUE	!VALUE
		CHARACTER*32	SPARE	!SPARE ROOM
C
	END STRUCTURE
C
	RECORD/RECX/RECX
C
	CHARACTER*22	FILEX/'LOGS:MRDD-MMM-YYYY.DAT'/
C
	EXTERNAL	UFO_OPEN
C
25	CONTINUE
C
	OPEN	(UNIT=1,FILE='LOGS:MINNTAC.DAT',STATUS='OLD',
	1	RECORDTYPE='FIXED',FORM='UNFORMATTED',RECL=24,
	1	SHARED,ACCESS='DIRECT',USEROPEN=UFO_OPEN)
C
	READ	(1,REC=132)RECX
	IF (RECX.DATEX(1:1) .EQ. ' ')RECX.DATEX(1:1)='0'
C
	FILEX(8:18)=RECX.DATEX	!DATE OF LAST 24 HOUR UPDATE
C
	OPEN	(UNIT=2,FILE=FILEX,STATUS='NEW',
	1	RECORDTYPE='FIXED',FORM='UNFORMATTED',RECL=24,
	1	SHARED,ACCESS='DIRECT')
C
	DO 333	I=1,200
C
		READ	(1,REC=I)RECX
		WRITE	(2,REC=I)RECX
C
333	CONTINUE
C
	CLOSE	(UNIT=1)
	CLOSE	(UNIT=2)
C
	CALL 	SYS$HIBER()	!HIBERNATE UNTIL WAKEUP
	GOTO 25			!GO RUN AGAIN
C
	END
