C
	STRUCTURE/FILTER_FILE/
		CHARACTER*18	FILTER_REF ! EX. 208-06-1+ DATE_REF
		INTEGER*4	FLAG	   !0=CURRENT 1=HISTORY 2=DELETED
		INTEGER*4	EQUIP_REF  !EQUIPMENT REF NUMBER
		INTEGER*8	DATE_IN	   !
		INTEGER*8	DATE_OUT
		REAL*4		HRS  	   !EQUIP HRS AT INSTALLATION
		REAL*4		LIFE       !LIFE HOURS (WHEN CHANGED)
		INTEGER*4	VENDOR	   !VENDOR NUMBER 
		CHARACTER*80	COMMENT
	END STRUCTURE
	RECORD/FILTER_FILE/FILTER
C
	J=SIZEOF(FILTER)
	TYPE*,J
	END
