
	CHARACTER*4	PRINTON/' [5i'/,PRINTOF/' [4i'/

	PRINTON(1:1) = CHAR(27)
	PRINTOF(1:1) = CHAR(27)

4	FORMAT ('+',A4)

!	OPEN (UNIT=6,FILE='SYS$COMMAND',STATUS='UNKNOWN')

	WRITE (6,4) PRINTON

	WRITE (6,305)
305	FORMAT(' REDUCTION PERIOD')

	WRITE (6,4) PRINTOF

	CLOSE (UNIT=6)

	END
