C
	PROGRAM	THKNER_CLOCK	!THICKNER CLOCK
C
C	LINK THKNER_CLOCK,THKNER_CLOCK/OPT
C
	IMPLICIT NONE
C
	INCLUDE	'($PRCDEF)'
C
	INTEGER*4	I,J,K,L,M,N
	INTEGER*4	CXSTS(100),BIT,UFO_OPEN
	INTEGER*4	SECS,PM2230/81000/,PM2400/86400/
	INTEGER*4	CNTR,FIVMIN/300/,TEMP,ADRS(2)
	INTEGER*4	CX(9)/1431,1433,1434,1435,1436,1437,1438,1439,1440/
C
	REAL*4		RSECS,OHRS(2)
C
	CHARACTER*8	TIM/'0 0:5:00'/
	CHARACTER*16	PRGNAM/'THICKNERS:THKNRZ'/
	CHARACTER*6	PRCNAM/'THKNRZ'/
	CHARACTER*23	DATETIME
C
	COMMON/CONTACTSCNC/CXSTS
C
	EXTERNAL	UFO_OPEN
C
	RSECS=SECNDS(0.0)	!SECONDS SINCE MIDNIGHT
	SECS=RSECS		!CONVERT TO INTEGER
	TEMP=PM2230-SECS	!CALCULATE FIVE MINUTE SCANS TILL 10:30PM
	IF (TEMP .LT. 0)TEMP=TEMP+PM2400
	CNTR=(TEMP/FIVMIN)
C
	CALL	SYS$BINTIM(TIM,ADRS)
	CALL	SYS$SCHDWK(,,ADRS,ADRS)	!SCHEDULE 5 MIN WAKEUP
C
200	CONTINUE
C
	OPEN	(UNIT=1,FILE='THICKNERS:THKNER_CLOCK.DAT',
	1	STATUS='OLD',FORM='UNFORMATTED',ACCESS='DIRECT',
	1	RECL=2,RECORDTYPE='FIXED',SHARED,USEROPEN=UFO_OPEN)
C

	DO 1000	I=1,9	!FOR EACH THKNER
C
		READ	(1,REC=I)OHRS	!OPER TIME FOR THIS THKNER
C
		J=(CX(I)/32)+1	!EXTRACT CXSTS LONGWORD
		K=MOD(CX(I),32)	!EXTRACT CORRECT BIT
		BIT=JIBITS(CXSTS(J),K,1)	!EXTRACT BIT CONDITION
C
		IF (BIT .EQ. 1)THEN
			OHRS(1)=OHRS(1)+(24.0/288.0)	!5 MIN OF OPER TIME
			WRITE	(1,REC=I)OHRS	!CHANGE RECORD
		END IF
C
1000	CONTINUE
C
	CLOSE	(UNIT=1)
C

	CNTR=CNTR-1	!DECREMENT SCAN COUNTER
C
	IF (CNTR .LT. 0)THEN
		CNTR=288	!RESET SCAN COUNTER
C
		OPEN	(UNIT=1,FILE='THICKNERS:THKNER_CLOCK.DAT',
	1		STATUS='OLD',FORM='UNFORMATTED',ACCESS='DIRECT',
	1		RECL=2,RECORDTYPE='FIXED',SHARED,USEROPEN=UFO_OPEN)
C
		DO 1200	I=1,9
			READ	(1,REC=I)OHRS
			OHRS(2)=OHRS(1)  	!SAVE 24 HR RESULTS
			OHRS(1)=0		!ZERO NEW 24 HR PERIOD
			WRITE	(1,REC=I)OHRS
1200		CONTINUE
C
		CLOSE	(UNIT=1)
C
		CALL	SYS$CREPRC(,PRGNAM,,,,,,PRCNAM,%VAL(4),,,
	1		%VAL(PRC$M_DETACH.OR.PRC$M_NOACNT))
C
	END IF
C
	CLOSE	(UNIT=1)
C
	CALL	SYS$HIBER()
	GOTO 200
C
	END
