C
C	UFO_OPEN
C
C	USEROPEN ROUTINE TO INDICATE TO RMS TO IGNORE
C	RECORDLOCKING
C
	INTEGER	FUNCTION UFO_OPEN(FAB,RAB,LUN)
	INTEGER LUN
C
	INCLUDE	'($SYSSRVNAM)'
	INCLUDE	'($FABDEF)'
	INCLUDE '($RABDEF)'
C
	RECORD /FABDEF/ FAB, /RABDEF/ RAB
C
	FAB.FAB$B_SHR=FAB.FAB$B_SHR .OR. FAB$M_UPI
	UFO_OPEN=SYS$OPEN(FAB)
	IF (.NOT. UFO_OPEN) RETURN
	UFO_OPEN=SYS$CONNECT(RAB)
	IF (.NOT. UFO_OPEN) RETURN
C
	RETURN
	END
