CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONFIDENTIAL
C	Property of United States Steel Corporation
C	Copyright 2014 United States Steel Corporation
C	All rights reserved.
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	PROGRAM	WGS
C
C	COMPILE STATEMENT
C
C       FORT/ALIGN=NONE/WARN=NOALIGN/FLOAT=D_FLOAT/LIST WGS
C
C	LINK STATEMENT
C
C       LINK WGS,WGS/OPT
C
C	RUN COMMAND FOR PROGRAM
C
C	RUN/DET/NOACC/ERR=ANA:WGS.ERR/PROC=WGS ANA:WGS
C
C       HELPFUL INFORMATION: RUN RWGS5
C	THIS PROGRAM RWGS5.EXE IS USED TO SHOW THE CURRENT 
C	STATUS OF THE COUNTER VALUES FOR LINES 3, 4, 5, 6,  AND 7
C	WHEN THE VALUE IS 540 THEN ORACLE MACT15M GETS A GOOD STATUS
C	FOR THE RUN INDICATION OF THE LINE.
C
C
C	REVISION HISTORY
C
C
C       PROCESS CHANGE: 1491
C       REVISION DATE:  08-16-2021
C       MODIFIED BY:    BLA1122, CTZ1859
C       DESCRIPTION OF CHANGES
C       COMMENTED OUT 1A, 1B, 3A, 3B FAN LOGIC
C
C
C 	PROCESS CHANGE: 1466                                    
C 	REVISION DATE:  01-26-2021, 02-03-2021                             
C 	MODIFIED BY:    BLA1122                       
C 	DESCRIPTION OF CHANGES                                 
C 	CHANGED COUNT VALUE FROM 540 TO 1
C       CHANGED BALLING COUNT FROM 4 TO 2 (LINE 3)
C       CHANGED BALLING COUNT FROM 5 TO 2 (LINES 4,5,6,7)
C       CHANGED BALLING COUNT FROM NE TO LT (NOT EQUAL) (LESS THAN)
C              
C	PROCESS CHANGE:	753 
C	REVISION DATE:	02-18-2015
C	MODIFIED BY:	BLA1122, CAN7407 
C	DESCRIPTION OF CHANGES
C	ADDED THE MOTOR CONTACTS FOR THE 1A, 1B, 3A, 3B FANS
C
C	ADDED RUN FLAG FOR 247-03-1 WET SCRUBBER PRS #2048
C
C	ADDED BALLING DRUM LOGIC 
C
C	PROJECT REQUEST SYSTEM NUMBER: 2170
C	SERVICE CENTER TICKET NUMBER:  PM569603
C	PLANVIEW ID NUMBER:            40916
C	PROGRAM AUTHOR:	BILL BABICH
C
	IMPLICIT NONE
C
	INTEGER*4	GRATE(5)/1229,362,569,349,356/
	INTEGER*4	KILN(5)/1214,368,575,399,421/
	INTEGER*4	COOLER(5)/1220,373,580,453,458/
	INTEGER*4	WGF(5)/1010,1656,571,371,373/
	INTEGER*4	WGD(5)/788,127,244,96,267/
C
C       !08-16-2021
C       !COMMENTED OUT 1A, 1B, 3A, 3B FAN VARIABLES
C	INTEGER*4	PHF1A(5)/1212,366,573,375,379/
C	INTEGER*4	PHF1B(5)/1213,1017,574,377,380/
C	INTEGER*4	CF3A(5)/1222,375,582,382,384/
C	INTEGER*4	CF3B(5)/1223,376,583,383,385/
C
	INTEGER*4	FLAG(5),I,J,K,L,M,N,BIT
	INTEGER*4	CXSTS(100),GB
	INTEGER*4	CXSTS_AG3(100)
	INTEGER*4	UFO_OPEN,ADRS(2)
	INTEGER*4	GB3(4)/1005,1006,1007,1008/
	INTEGER*4	GB4(5)/1578,1579,1580,1581,1582/
	INTEGER*4	GB5(5)/1583,1584,1585,1586,1587/
	INTEGER*4	GB6(5)/74,77,78,80,83/
	INTEGER*4	GB7(5)/86,89,90,92,94/
C
	REAL*4		ANVAL(1200)
	REAL*4		ANVAL_AG3(1000)
	REAL*4		VALU
C
	CHARACTER*8	TIM/'0 0:0:10'/	!10 SEC RUN TIME

C
	EXTERNAL	UFO_OPEN
C
	COMMON/ANVALTBL/ANVAL
	COMMON/AG3_ANVALTBL/ANVAL_AG3
C
	COMMON/CONTACTS/CXSTS
	COMMON/CONTACTSAG3/CXSTS_AG3
C
	CALL	SYS$BINTIM(TIM,ADRS)
	CALL	SYS$SCHDWK(,,ADRS,ADRS)	!SCHEDULE 10 SEC WAKEUP
C
100	CONTINUE
C
	OPEN	(UNIT=1,FILE='ANA:WGS.DAT',STATUS='OLD',
	1	ACCESS='DIRECT',RECL=5,RECORDTYPE='FIXED',
	1	FORM='UNFORMATTED',SHARED,USEROPEN=UFO_OPEN)
C
	READ	(1,REC=1)FLAG	!READ IN INDICATIONS
C
	DO 555	I=1,5	!CHECK TO SEE IF LINE IS RUNNING NORMAL
C
		M=(GRATE(I)/32)+1		!WORD IN CX TABLE
		N=MOD(GRATE(I),32)		!BIT IN WORD
		IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
		IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
		IF (BIT .EQ. 0)THEN
			FLAG(I)=0	!GRATE IS OFF
			GOTO 555
		END IF
C
		M=(KILN(I)/32)+1		!WORD IN CX TABLE
		N=MOD(KILN(I),32)		!BIT IN WORD
		IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
		IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
		IF (BIT .EQ. 0)THEN
			FLAG(I)=0	!KILN IS OFF
			GOTO 555
		END IF
C
		M=(COOLER(I)/32)+1		!WORD IN CX TABLE
		N=MOD(COOLER(I),32)		!BIT IN WORD
		IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
		IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
		IF (BIT .EQ. 0)THEN
			FLAG(I)=0	!COOLER IS OFF
			GOTO 555
		END IF
C
		M=(WGF(I)/32)+1		!WORD IN CX TABLE
		N=MOD(WGF(I),32)		!BIT IN WORD
		IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
		IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
		IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
		IF (BIT .EQ. 0)THEN
			FLAG(I)=0	!WASTE GAS FAN IS OFF
			GOTO 555
		END IF
C
C       !08-16-2021
C       !REMOVED 1A, 1B, 3A, 3B FAN AS PER OPEX AND ENVIRONMENTAL 
C
C	!ADDED 02-18-2015
C
C                M=(PHF1A(I)/32)+1               !WORD IN CX TABLE
C                N=MOD(PHF1A(I),32)              !BIT IN WORD
C                IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
C                IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
C                IF (BIT .EQ. 0)THEN
C                        FLAG(I)=0       !PREHEAT FAN 1A IS OFF
C                        GOTO 555
C                END IF
C
C                M=(PHF1B(I)/32)+1               !WORD IN CX TABLE
C                N=MOD(PHF1B(I),32)              !BIT IN WORD
C                IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
C                IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
C                IF (BIT .EQ. 0)THEN
C                        FLAG(I)=0       !PREHEAT FAN 1B IS OFF
C                        GOTO 555
C                END IF
C
C                M=(CF3A(I)/32)+1               !WORD IN CX TABLE
C                N=MOD(CF3A(I),32)              !BIT IN WORD
C                IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
C                IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
C                IF (BIT .EQ. 0)THEN
C                        FLAG(I)=0       !COOLING FAN 3A IS OFF
C                        GOTO 555
C                END IF
C
C                M=(CF3B(I)/32)+1               !WORD IN CX TABLE
C                N=MOD(CF3B(I),32)              !BIT IN WORD
C                IF (I .EQ. 1)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 2)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 3)BIT=JIBITS(CXSTS(M),N,1)
C                IF (I .EQ. 4)BIT=JIBITS(CXSTS_AG3(M),N,1)
C                IF (I .EQ. 5)BIT=JIBITS(CXSTS_AG3(M),N,1)
C
C                IF (BIT .EQ. 0)THEN
C                        FLAG(I)=0       !COOLING FAN 3B IS OFF
C                        GOTO 555
C                END IF
C       !08-16-2021
C       !COMMENTED OUT 1A, 1B, 3A, 3B
C
C	!ADDED 02-18-2015
C
		IF (I .EQ. 1)VALU=ANVAL(WGD(I))
		IF (I .EQ. 2)VALU=ANVAL(WGD(I))
		IF (I .EQ. 3)VALU=ANVAL(WGD(I))
		IF (I .EQ. 4)VALU=ANVAL_AG3(WGD(I))
		IF (I .EQ. 5)VALU=ANVAL_AG3(WGD(I))
C
		IF (VALU .LT. 25)THEN
			FLAG(I)=0
			GOTO 555
		END IF
C
		IF (I .EQ. 1)THEN      !CHECK LINE 3 BALLING DRUMS
			GB=0	!COUNTER FOR BALLING DRUM CIRCUITS
			DO 333	J=1,4
				M=(GB3(J)/32)+1	 !WORD IN CX TABLE
				N=MOD(GB3(J),32) !BIT IN WORD
				BIT=JIBITS(CXSTS(M),N,1)
				IF (BIT .EQ. 1)GB=GB+1
333			CONTINUE
C
C			IF (GB .NE. 4)THEN   !ORIGINAL NOT EQUAL TO 4
                        IF (GB .LT. 2)THEN   !LESS THAN 2
				FLAG(I)=0
				GOTO 555
			END IF
C
			GOTO 999
C
		END IF
C
		IF (I .EQ. 2)THEN	!CHECK LINE 4 BALLING DRUMS
			GB=0	!COUNTER FOR BALLING DRUM CIRCUITS
			DO 444	J=1,5
				M=(GB4(J)/32)+1	 !WORD IN CX TABLE
				N=MOD(GB4(J),32) !BIT IN WORD
				BIT=JIBITS(CXSTS(M),N,1)
				IF (BIT .EQ. 1)GB=GB+1
444			CONTINUE
C
C			IF (GB .NE. 5)THEN    !ORIGINAL NOT EQUAL TO 5
                        IF (GB .LT. 2)THEN    !LESS THAN 2
				FLAG(I)=0
				GOTO 555
			END IF
C
			GOTO 999
C
		END IF
C
		IF (I .EQ. 3)THEN	!CHECK LINE 5 BALLING DRUMS
			GB=0	!COUNTER FOR BALLING DRUM CIRCUITS
			DO 500	J=1,5
				M=(GB5(J)/32)+1	 !WORD IN CX TABLE
				N=MOD(GB5(J),32) !BIT IN WORD
				BIT=JIBITS(CXSTS(M),N,1)
				IF (BIT .EQ. 1)GB=GB+1
500			CONTINUE
C
C			IF (GB .NE. 5)THEN     !ORIGINAL NOT EQUAL TO 5
                        IF (GB .LT. 2)THEN     !LESS THAN 2
				FLAG(I)=0
				GOTO 555
			END IF
C
			GOTO 999
C
		END IF
C
		IF (I .EQ. 4)THEN	!CHECK LINE 6 BALLING DRUMS
			GB=0	!COUNTER FOR BALLING DRUM CIRCUITS
			DO 600	J=1,5
				M=(GB6(J)/32)+1	 !WORD IN CX TABLE
				N=MOD(GB6(J),32) !BIT IN WORD
				BIT=JIBITS(CXSTS_AG3(M),N,1)
				IF (BIT .EQ. 1)GB=GB+1
600			CONTINUE
C
C			IF (GB .NE. 5)THEN  !ORIGINAL NOT EQUAL TO 5
                        IF (GB .LT. 2)THEN  !LESS THAN 2
				FLAG(I)=0
				GOTO 555
			END IF
C
			GOTO 999
C
		END IF
C
		IF (I .EQ. 5)THEN	!CHECK LINE 7 BALLING DRUMS
			GB=0	!COUNTER FOR BALLING DRUM CIRCUITS
			DO 700	J=1,5
				M=(GB7(J)/32)+1	 !WORD IN CX TABLE
				N=MOD(GB7(J),32) !BIT IN WORD
				BIT=JIBITS(CXSTS_AG3(M),N,1)
				IF (BIT .EQ. 1)GB=GB+1
700			CONTINUE
C
C			IF (GB .NE. 5)THEN    !ORIGINAL NOT EQUAL TO 5
                        IF (GB .LT. 2)THEN    !LESS THAN 2  
				FLAG(I)=0
				GOTO 555
			END IF
C
			GOTO 999
C
		END IF
C
999	CONTINUE
C
C
C               IF (FLAG(I) .LT. 540)FLAG(I)=FLAG(I)+1 !10 SECONDS OF RUN TIME
C 
		IF (FLAG(I) .LT. 1)FLAG(I)=FLAG(I)+1 !10 SECONDS OF RUN TIME
C
555	CONTINUE
C
	WRITE	(1,REC=1)FLAG	!WRITE OUT INDICATIONS
C
	CLOSE	(UNIT=1)
C
	CALL	SYS$HIBER()	!DELAY TILL WAKEUP
C
	GOTO 100
C
	END
C
