CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONFIDENTIAL
C	Property of United States Steel Corporation
C	Copyright 2011 United States Steel Corporation
C	All rights reserved.
C******************************************************************************
C	WRITE_AGGL_EQUIP_2.FOR
C******************************************************************************
C Revisions:
C	IM813566 20110511 SPA6635 New Scratch program to edit the data file:
C				  AGGL_HRS:WRITE_AGGL_EQUIP_2.DAT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

	PROGRAM	WRITE_AGGL_EQUIP_2
C
	IMPLICIT NONE
C
	INTEGER*4	UFO_OPEN,I,J,K
C
C
C	** AAGL_HOURS:AGGL_EQUIP_2.DAT**
	STRUCTURE/DIGFILE/
		INTEGER		POINT_REF  !POINT REFERENCE NO.
		INTEGER		COUNT	   !ACCUMULATED TIME COUNTS
		INTEGER		COUNT_1    !RESET COUNTER
		INTEGER		COUNT_2    !COUNT DOWN COUNTER
		INTEGER		COUNT_3
		CHARACTER*11	POINT_NO   !POINT NUMBER
		CHARACTER*32	DESCR      !ENGLISH DESCRIPTION
	END STRUCTURE
	RECORD/DIGFILE/POINT

	BYTE		HRS1(32)
	REAL*4		CURRENT
	INTEGER*4	REF,REC
C
	EXTERNAL	UFO_OPEN
C
	OPEN(1,FILE='AGGL_HRS:AGGL_EQUIP_2.DAT',
	1    STATUS='OLD',
	1    ORGANIZATION='SEQUENTIAL',
	1    ACCESS='DIRECT',
	1    RECORDTYPE='FIXED',
	1    RECL=16,
	1    FORM='UNFORMATTED',
	1    USEROPEN=UFO_OPEN,SHARED)
C
	TYPE*,'ENTER POINT_REF NUMBER: '
 	READ(5,99)REF
99	FORMAT(I)
	REC=1
10	READ(1,REC=REC,ERR=900)POINT
	IF (POINT.POINT_REF .EQ. REF)THEN
C *write record to screen
	WRITE	(6,100)POINT.POINT_REF
100	FORMAT(' ',I25)
	WRITE	(6,100)POINT.COUNT
	WRITE	(6,100)POINT.COUNT_1
	WRITE	(6,100)POINT.COUNT_2
	WRITE	(6,100)POINT.COUNT_3
	WRITE	(6,200)POINT.POINT_NO
200	FORMAT(' ',A)
	WRITE	(6,200)POINT.DESCR
	REC=REC+1
	GOTO 10
C
	END IF
	REC=REC+1
	GOTO 10

	CLOSE	(UNIT=1)
C
900	CALL	EXIT
C
	END
